### ISSUE TITLE
Some suggestions for TCPStreamFollower

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#102]
I spent the week playing with TCPStreamFollower. A few suggestions to make it easier :

- i've not been able to perfectly match a C++ ForwardIterator with a python iterator (cause of subtle glitches with Python GIL and threads... when executing a long C++ follow_streams method in cython, other python threads are stalled because of the GIL). So i have to give each PDU to the follower one by one. It would be nice if there could be a public helper method to do it, like :

TCPStreamFollower::follow_streams(PDU*, DataFunctor data_fun, EndFunctor end_fun) 

- usually i will give the client and server payloads to some parser (eg HTTP). The TCPStreamFollower gives back the full payloads to data_fun and end_fun each time. Sometimes this is too much: for memory efficiency i'd rather use an incremental parser, only using the last chunk of data. Hence another class IncrementalTCPStreamFollower would be needed for that. The underlying IncrementalTCPStream would only store the last chunk of data, avoiding spending too much memory in client_payload_ and server_payload_.

- when parsing a TCP stream, i could decide that i had enough data for the job, and may not be interested in the next chunks for this stream. The data_fun and end_fun functors could return a boolean indicating whether i want to be notified with the next chunks or not. After one of the functors returns false, TCPStreamFollower and IncrementalTCPStreamFollower would just ignore the next PDUs for that stream. (again, think memory efficiency).

- by the way, in libtins 3.2, the following line seems suspect: if(!callback(Utils::dereference_until_pdu(start), data_fun, end_fun))

the callback method always returns true, so the if statement is weird.

- if you're curious, bridging python and Functors is not totally trivial :) but that's ok
https://github.com/stephane-martin/cycapture/blob/master/cycapture/libtins/py_tcp_stream_functor.cpp

Thanks in advance,
Stephane

**Comment by mfontanini** [comment]
Hey! I've been wanting to change the TCPStreamFollower for a while (or maybe write a new class for this). This was a small class that I added without putting too much thought into it: I just wanted to be able to reassemble a stream.

But anyway, until that's working:

* You can clear the data on the data functor. So if you only want the last chunk, you can call .clear() on the client/server payload so the next time you get data, you'll only get the latest data and not the whole stream.
* About the callback, yes, it's basically useless to check if it's false. But well, I guess at some point it might have (or might) return something different. 
* Regarding iterators, you can already provide just one PDU*. PDU* are actually random access iterators already :)

```c++
PDU* my_pdu = ...;
TCPStreamFollower follower;
follower.follow_streams(my_pdu, my_pdu + 1, ...);
```

**Comment by stephane-martin** [comment]
thx !

to clear the data in the functor, the functor would need to know if we are working on an updated client payload or on an updated server payload... that piece of information could be returned by TCPStream::update (int instead of bool return value) and be passed to the functor.

**Comment by mfontanini** [comment]
Hey, I started writing a completely new implementation of this during the weekend. I'm keeping the old classes for backwards compatibility but eventually they'll probably go away.

If you want, you can have a look at it, it's on [this branch](https://github.com/mfontanini/libtins/tree/tcp-stream). See [this example](https://github.com/mfontanini/libtins/blob/tcp-stream/examples/http_dump.cpp) for usage (classes are on tcp_ip.h/cpp). I will surely use your suggestion of letting the user stop following a stream somehow (maybe adding a `Stream::ignore_client/server_payload`?).

If you have any other please let me know as I'm pretty excited about re-writing this in a more usable way. TCPStreamFollower is really simple and doesn't let the user do much.

Thanks!

**Comment by mfontanini** [comment]
Closing this as the new `TCPIP::StreamFollower` class deals with all of these issues.
