### ISSUE TITLE
NetworkInterfaces on Windows platforms

### ISSUE THREAD

**Issue by LegITdevel** [mfontanini/libtins#103]
Example from the "Sniffing basics" (http://libtins.github.io/tutorial/sniffing/)

It's quite easy to handle on Linux distros and OSX, but getting valid network interface names on windows platforms is a mess. Especially matching them to the right adapters, including their virtual parts. Any suggestions on this, or a way to make it easier?

Sniffer sniffer("eth0");

**Comment by mfontanini** [comment]
I don't usually use Windows, so I haven't had this problem. Maybe you could iterate through all adapters using ```NetworkInterface::all()``` and then match based on interface IP address/gateway using ```NetworkInterface::info()```?

**Comment by LegITdevel** [comment]
Yeah that's fine and works. Tho to give a decent output in a GUI, it requires to include windows specific code like explained at http://stackoverflow.com/questions/17288908/get-network-interface-name-from-ipv4-address

Would be awesome if you could add these vars to NetworkInterface::info

**Comment by mfontanini** [comment]
I pushed a fix for this on the develop branch. Now you can use `NetworkInterface::friendly_name`, which should return the adapter's name on Windows (e.g. Local Area Connection 2).
