### ISSUE TITLE
gcc thinks there is no default constructor for PKTAP

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#106]
hi,

in pktap.h, a default constructor is declared : PKTAP();
after compiling the python wrapper, i get an error with dlopen: Symbol not found: __ZN4Tins5PKTAPC1Ev

So one object related to PKTAP is missing in tins.so.
If i remove reference to the default PKTAP constructor in python code, the error goes away.

So my guess is that gcc needs the PKTAP constructor to be not only declared, but also defined.
Could you add that default constructor definition ?

Thanks,
Stephane

**Comment by mfontanini** [comment]
Nice catch, the definition of the default constructor is missing. I'll fix that now.

**Comment by stephane-martin** [comment]
IIRC the PPI class doesn't have a constructor too (neither declared nor
defined, in this case). would be handy to add one.
Le 16 oct. 2015 18:30, "Matias Fontanini" <notifications@github.com> a
écrit :

**Comment by mfontanini** [comment]
PPi is somehow special. I mean, you're not going to craft a packet holding a PPI layer, since it's AFAIK only appended by the kernel/pcap when sniffing on "any". Is this causing troubles for you?

**Comment by stephane-martin** [comment]
troubles, no. but in cython c++ classes can't be instantiated on the stack
unless they have a default constructor. so you're forced to use tiny picky
smelly new and delete operators and allocate on the heap. that's what I do
with PDU classes anyway.
Le 16 oct. 2015 19:07, "Matias Fontanini" <notifications@github.com> a
écrit :

**Comment by mfontanini** [comment]
Well that's the thing, you shouldn't ever construct a PPI yourself. It should always be the Sniffer class the one that does this (and it does this by constructing it over a payload, which is fine).
