### ISSUE TITLE
deserialize IP packet + serialize => different buffer

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#108]
Hello,

im translating your unittests to python so that i can check the wrapper correctness.
One of them fails for IP PDU.

```c++
const uint8_t IPTest::expected_packet[] = { 
    40, 127, 0, 32, 0, 122, 0, 67, 21, 1, 0, 0, 84, 52, 254, 5, 192, 
    168, 9, 43, 130, 11, 116, 106, 103, 171, 119, 171, 104, 101, 108, 0
};

TEST_F(IPTest, Serialize) {
    IP ip1(expected_packet, sizeof(expected_packet));
    PDU::serialization_type buffer = ip1.serialize();
    ASSERT_EQ(buffer.size(), sizeof(expected_packet));
    EXPECT_TRUE(std::equal(buffer.begin(), buffer.end(), expected_packet));
}
```

which gives me in python:

```python
def test_serialize(self):
    ip1 = IP.from_buffer(expected_packet)
    buf = ip1.serialize()
    self.assertEquals(expected_packet, buf)
```
indeed ip1.serialize() returns :

{ 
    40, 127, 32, 0, 0, 122, 0, 67, 21, 1, 0, 0, 84, 52, 254, 5, 192, 
    168, 9, 43, 130, 11, 116, 106, 103, 171, 119, 171, 104, 101, 108, 0
}

The 3rd and 4th bytes have been inversed. That's the total length if i don't err.

In IP::write_serialization, some lines have caught my eyes : 

```c++
#if __FreeBSD__ || defined(__FreeBSD_kernel__) || __APPLE__
    if(!parent)
        total_sz = Endian::host_to_be<uint16_t>(total_sz);
#endif
```
Ahah. Im compiling on MacOSX. Inversion of bytes ? Endianness ?!!!

Anyway either the unit test has a bug, or the IP PDU class has a bug. (Or i made a mistake somewhere...)

**Comment by mfontanini** [comment]
Yeah, for some mysterious reason (I think I looked it up, don't remember if I found why) on FreeBSD and OSX, the total size has to be flipped. It's only flipped when the lowest layer is IP (hence the ```!parent```).

How are you handling serialization?

**Comment by stephane-martin** [comment]
it's a wrapper, only... i don't *do* things, i just use your work

cpdef serialize(self):
    cdef vector[uint8_t] v = self.base_ptr.serialize()
    cdef uint8_t* p = &v[0]
    return <bytes> (p[:v.size()])

self.base_ptr is a PDU* pointer. so the python serialize is: "get the
wrapped C++ object, apply native serialize method, convert the vector to a
native python bytes object"

same for deserialization, i just pass the buffer to the right PDU
constructor


2015-10-20 22:11 GMT+02:00 Matias Fontanini <notifications@github.com>:

**Comment by stephane-martin** [comment]
So forget about the wrapper, just run the normal libtins unit tests on
MacOSX, and you most probably get the same error...

2015-10-20 22:24 GMT+02:00 houbaastef . <stef.martin@gmail.com>:

**Comment by mfontanini** [comment]
The test seems to be fine. I mean, the total length seems to be in big endian on the expected results, so that should be fine.

OSX is working though, see [travis.ci](https://travis-ci.org/mfontanini/mfontanini/libtins/builds/85774655).

**Comment by mfontanini** [comment]
If you're using OSX, can you run them on it? You just need to get google mock (git submodule update --init --recursive) and that should be it.

**Comment by mfontanini** [comment]
Wait, where is that test? It's not there anymore

**Comment by stephane-martin** [comment]
Currently i work on the basis of libtins 3.2. in tests/src/ip.cpp:

TEST_F(IPTest, Serialize) {
    IP ip1(expected_packet, sizeof(expected_packet));
    PDU::serialization_type buffer = ip1.serialize();
    ASSERT_EQ(buffer.size(), sizeof(expected_packet));
    EXPECT_TRUE(std::equal(buffer.begin(), buffer.end(), expected_packet));
}



2015-10-20 22:32 GMT+02:00 Matias Fontanini <notifications@github.com>:

**Comment by stephane-martin** [comment]
i can't run the C++ tests, "make test" only insults me ("Unable to find
executable: TCPTest" and so on for every test)

so...

with libtins 3.2, compiled normally and installed normally : test.cpp

#include <iostream>
#include <cstring>
#include <string>
#include <stdint.h>
#include <vector>
#include "tins/tins.h"

const uint8_t expected_packet[] = {
        40, 127, 0, 32, 0, 122, 0, 67, 21, 1, 0, 0, 84, 52, 254, 5, 192,
            168, 9, 43, 130, 11, 116, 106, 103, 171, 119, 171, 104, 101, 108, 0
};

int main()
{
    std::cout << "Hello\n\n";
    Tins::IP ip1(expected_packet, sizeof(expected_packet));
    std::vector<uint8_t> buffer = ip1.serialize();
    std::cout << "expected_packet: " << int(expected_packet[0]) << " "
<< int(expected_packet[1]) << " " << int(expected_packet[2]) << " " <<
int(expected_packet[3]) << std::endl << std::endl;
    std::cout << "after serialize: " << int(buffer[0]) << " " <<
int(buffer[1]) << " " << int(buffer[2]) << " " << int(buffer[3]) <<
std::endl << std::endl;
}


stdout :

Hello

expected_packet: 40 127 0 32

after serialize: 40 127 32 0



I don't know if it is the correst behaviour or not, but  TEST_F(IPTest,
Serialize) in libtins 3.2 will fail.




2015-10-20 22:38 GMT+02:00 houbaastef . <stef.martin@gmail.com>:

**Comment by mfontanini** [comment]
You have to compile tests first:

```
make tests
make test
```

But yes, that test was basically always failing for OSX. Now it's gone (although again, maybe I should just swap those 2 expected bytes on OSX rather than removing the test :P ).

**Comment by stephane-martin** [comment]
while you're there... :)

another strange thing with the tests: they fail when im offline (shutdown
wifi), with runtime exception "Error looking up interface".

The strange thing is that the exception happens in IP::serialize. Why
serialize needs to look for a network interface ?!

2015-10-21 22:34 GMT+02:00 Matias Fontanini <notifications@github.com>:

**Comment by mfontanini** [comment]
When you serialize a packet for which the lowest layer is IP, you need to fill the source address field with a valid address (this is, the address that will be used when actually sending the packet). This is because you need a valid source address to calculate the UDP/TCP checksum (due to the pseudo-header used in both protocols when doing the checksum).

So even though the kernel is going to calculate the checksum itself (meaning the IP checksum will always be calculated by the kernel once you actually send the packet), the TCP/UDP checksum has to be calculated by libtins correctly, and in order to calculate that, we need the source address to be set to the same that will be used on the actual out-going packet (that is, whatever the kernel decides to use depending on which route/interface the packet takes). 

In order to do that, we basically get the interface on which the packet should be sent depending on the destination address used and the current routing table. That's why you need to have a valid interface.

Now, if you check newer tests (this was changed when I added travis.ci and appveyor to build the library and run tests), you'll see that serialization is a bit changed. I think all IP tests now will use 127.0.0.1 as the destination IP, so I think they should always succeed when serializing. Not completely sure though, as I always run tests when being online :)

**Comment by stephane-martin** [comment]
you can close the ticket, i'll add a workaround in my tests

2015-10-21 22:47 GMT+02:00 Matias Fontanini <notifications@github.com>:

**Comment by mfontanini** [comment]
Thanks!
