### ISSUE TITLE
Unable to capture packets through WPA2 DecryptProxy

### ISSUE THREAD

**Issue by bobbygryzynger** [mfontanini/libtins#110]
I am unable to get the following minimal example to produce any captured packets; and my handler function is never called:

    bool hdlr(Tins::PDU &pdu){

        std::cout <<  "capture"  << std::endl;
        return true;
    }
    
    int main(){    
    
        auto decrypt_proxy = Tins::Crypto::make_wpa2_decrypter_proxy(&hdlr);
        decrypt_proxy.decrypter().add_ap_data(CONFIG_MY_PSK, CONFIG_MY_SSID);

        Tins::Sniffer sniffer("wlan0", Tins::Sniffer::PROMISC);
        sniffer.sniff_loop(decrypt_proxy);
  
        return 0;

    }

I let this program run for several minutes and also tried disconnecting and reconnecting to my network while the program ran, but I still did not get any output. When I run the program without the use of the decrypter, my handler function is called and I get the output I expect. I'm running this revised program as follows:

    Tins::Sniffer sniffer("wlan0", Tins::Sniffer::PROMISC);
    sniffer.sniff_loop(hdlr);

I ran the tests (on Ubuntu 14.04) provided with version 3.2 and all of them passed. Is there any reason why I'm getting no output whatsoever while running sniff_loop with my decrypt_proxy?

**Comment by mfontanini** [comment]
Is wlan0 set to monitor mode? You need to do that if you're trying to capture 802.11 packets.

If it is in monitor mode, you should also set it to the right channel (the channel in which the access point you're trying to sniff is). Otherwise the driver is probably going to start jumping between channels and you are likely to lose the packets you want to capture (if you're trying to decrypt WPA2 and you don't capture the handshake, you won't be able to decrypt anything).

**Comment by bobbygryzynger** [comment]
That took care of it, thank you. 

One quick follow-up question: when using the library with WPA2 decryption, is it necessary for the the access point to broadcast its SSID? Because in addition to giving my access point a fixed channel and putting my adapter in monitor mode on that channel, I didn't see any traffic until I switched on the broadcasting on my AP (previously I had it disabled).

**Comment by mfontanini** [comment]
So, there's 2 overloads of ```WPA2Decrypter::add_ap_data```:

* The one that you're using, which takes the PSK and the SSID. This one will keep monitoring SSID broadcast to know which BSSIDs are broadcasting that SSID. Once it finds a new one, it will keep track of the packets sent by/to it to attempt to decrypt them.
* Another one that takes the PSK, the SSID and a BSSID. This one basically assumes that the BSSID you provide would be associated to the SSID provided. So this means that this works the same as the other overload, except that it won't monitor SSID broadcasts. If you're not broadcasting the SSID in your AP, you should use this overload, providing your AP's BSSID as the third argument.

**Comment by bobbygryzynger** [comment]
I'm reopening this because I'm still finding the decryption unreliable. I've tried incorporating the second overloaded version of `add_ap_data` into a larger program and am rarely seeing any traffic and certainly seeing less traffic than I would expect on the network.

I'm constructing the sniffer like this in a wrapper class
```cpp
void MySnifferWrapper::startSniffing() {

    auto decrypt_proxy = Crypto::make_wpa2_decrypter_proxy(boost::bind(&MySnifferWrapper::processPacket, this, _1));
    decrypt_proxy.decrypter().add_ap_data(std::get<0>(this->accessPtCreds), // PSK
                                              std::get<1>(this->accessPtCreds), // SSID
                                              std::get<2>(this->accessPtCreds)); // BSSID

    Sniffer sniffer("wlan0", this->tinsConfig);
    sniffer.sniff_loop(decrypt_proxy);
}

```

Above I am constructing `this->tinsConfig` like this
```cpp
Tins::SnifferConfiguration snifferConfig;
snifferConfig.set_filter(CONFIG_SNIFFER_FILTER); // "tcp port 80"
snifferConfig.set_promisc_mode(CONFIG_SNIFFER_PROMISC); // 1

//in MySnifferWrapper's c'tor    
this->tinsConfig = snifferConfig;

```

And calling this processing function
```cpp
bool MySnifferWrapper::processPacket(PDU &pkt){
    
    IP *ipData = pkt.find_pdu<IP>();
    TCP *tcpData = pkt.find_pdu<TCP>();
    cout << "Packet captured: " << ipData->dst_addr().to_string() << endl;
    return true;
}
```

I have set my access point to use channel 6 and have tried running my application both with and without broadcasting its SSID. Additionally, I have put my adapter in monitor mode on channel 6. Here's the output for `iwconfig`
```
wlan0     IEEE 802.11bgn  Mode:Monitor  Frequency:2.437 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

```

Is there anything else I should be trying here or doing differently?

**Comment by bobbygryzynger** [comment]
I've also tried added the following config lines, but this hasn't changed my results
```cpp
snifferConfig.set_rfmon(true);
snifferConfig.set_timeout(5000);
```

**Comment by mfontanini** [comment]
A good way to test this is to run tcpdump and libtins (decrypting packets) at the same time, generating a pcap with all captured packets. Then load the pcap file generated by tcpdump using wireshark and configure the AP data so it can decrypt the traffic. Then compare both captures.

**Comment by bobbygryzynger** [comment]
I still haven't been able to get this working correctly, but I suspect the issues I'm experiencing are mostly related to the fact that I'm attempting to run the sniffer within a hypervisor virtual machine and gaining access to the wireless interface is problematic. I'm going to look for an interface that is more compatible with my host system. In the meantime, I'm going to close this issue until I can verify this is actually an issue with libtins and not my system/hardware. Thanks for your help with this.
