### ISSUE TITLE
can libtins support 1000M network card?

### ISSUE THREAD

**Issue by omengye** [mfontanini/libtins#112]
i wrote some code to test my 1000M network card, and i found that it could recevie about 10,000 packets per second. but my network card send about 200,000 packets per second. so i don't no how to deal with it. thank you.

here is my code:
```
#include <iostream>
#include <tins/tins.h>
#include <tins/sniffer.h>
#include <tins/tcp.h>
#include <string>
#include <stdint.h>
#include "tins/tcp_stream.h"
using namespace Tins;

clock_t t1;

int sumCount  = 0;

bool callback(const PDU &pdu) {

	++sumCount;

	if (sumCount % 10000 == 0) {
		std::cout<<sumCount<<std::endl;
		std::cout<<"=======\nSUM:  "<<(clock() - t1)/1000<<std::endl;
	}

	return true;
}

int main() {

	t1 = clock();

	std::string interfaceName = "{6600FEF3-ABCD-488D-CDEF-34DDE2B3E101}";
	
	Sniffer(interfaceName).sniff_loop(callback);

	return 0;
} 
```

**Comment by mfontanini** [comment]
10k pps is way to slow. Have you built libtins in release mode? That can make a huge difference.

**Comment by omengye** [comment]
@mfontanini release is perfect, got 170k pps. thanks.

**Comment by James-stdy-app** [comment]
Hey I’m having the same issue. What did you mean by “release mode” is it just pulling the latest release rather then the last push? 

Thanks,
James
