### ISSUE TITLE
How to free memory after Tcp reassembled

### ISSUE THREAD

**Issue by omengye** [mfontanini/libtins#113]
I use the method "TCPStreamFollower::follow_streams	(BaseSniffer & 	sniffer, DataFunctor 	data_fun, EndFunctor 	end_fun )" to make tcp reassembled. In the end_fun, i wrote tcp.client_payload().clear() and tcp.server_payload().clear(), but memory was keepping increasing, what should i do to free memory?

**Comment by mfontanini** [comment]
If you have a long-standing connection, e.g downloading something, the stream might not reach the end for a while, so memory would keep increasing.

Also keep in mind memory can increase a bit initially until it stabilizes, even if you're clearing the data frequently.

**Comment by mfontanini** [comment]
In case you're still using TCPStreamFollower, I recently added a new, much better interface to parse TCP streams. See http://libtins.github.io/tutorial/tcp-streams/

**Comment by mfontanini** [comment]
Also closing this, as the new `TCPIP::StreamFollower` already fixes this.

**Comment by omengye** [comment]
@mfontanini Thank you for your work!
