### ISSUE TITLE
TCPStream: add_sequence_numbers modular arithmetic incorrect

### ISSUE THREAD

**Issue by ecatmur** [mfontanini/libtins#115]
The calculation of `add_sequence_numbers` is incorrect if the result is equal to `std::numeric_limits<uint32_t>::max()`.

For example, `add_sequence_numbers(4294967290, 5)` will result in `0` but should result in `4294967295`.

This is because `addition_modulo` is defined to equal `std::numeric_limits<uint32_t>::max()` i.e. `2^32 - 1` when it should be `2^32` (not representable in `uint32_t`).

This can be fixed by redefining `addition_modulo` as:
```
static const uint64_t addition_modulo = static_cast<uint64_t>(std::numeric_limits<uint32_t>::max()) + 1u;
```

Or, alternatively, by removing it entirely as C++ unsigned arithmetic is defined to be modular (**[basic.fundamental]**/4 "*Unsigned integers, declared `unsigned`, shall obey the laws of arithmetic modulo 2^* n *where* n *is the number of bits in the value representation of that particular size of integer.*"):
```
// Sequence number add as defined by RFC 1982
uint32_t add_sequence_numbers(uint32_t seq1, uint32_t seq2) {
    return seq1 + seq2;  // C++ unsigned arithmetic is modular
}

// Subtract sequence numbers
uint32_t subtract_sequence_numbers(uint32_t seq1, uint32_t seq2) {
    return seq1 - seq2;  // C++ unsigned arithmetic is modular
}
```

**Comment by mfontanini** [comment]
Sorry I never replied to this issue! You are absolutely right about this. I've just fixed this on the develop branch.

Thank you!
