### ISSUE TITLE
packet changes payload_type after serialize()

### ISSUE THREAD

**Issue by horahh** [mfontanini/libtins#116]
I observed there was a test about the type remaining after a serialization, but this is slightly different case.

The issue is:
I set a payload type (0x800) for an ethernet header that has a RawPDU inner header.
I call the method serialize(), then check the value of the payload type and it is set to 0 ( I am expecting it to remain as 0x800)
If I check the serialization of the packet, the field for the ethernet type would be 0 as well, rather than the expected 0x800.

The problem was also seen when using the = operator in assignment to another packet, reseting the value to 0.

I think this test would reproduce the issue.
~~~{.cpp}
TEST_F(EthernetIITest, Serialize) {
    EthernetII eth(dst_addr, src_addr);
    uint32_t payload_size = 100;
    uint8_t payload[100] = {0};
    eth/=RawPdu(payload, payload_size);
    eth.payload_type(p_type);
    PDU::serialization_type serialized = eth.serialize();
    ASSERT_EQ(serialized.size(), sizeof(expected_packet));
    EXPECT_TRUE(std::equal(serialized.begin(), serialized.end(), expected_packet));
}
~~~

**Comment by horahh** [comment]
Explaining better myself,

The issue is: I set a payload type (0x800) for an ethernet header that has a RawPDU inner header.
I call the method serialize(), then check the value of the payload type and it is set to 0 ( I am expecting it to remain as 0x800)
If I check the serialization of the packet, the field for the ethernet type would be 0 as well, rather than 0x800.
As said before, the test before would catch the bug.

**Comment by mfontanini** [comment]
Thanks for the report!
