### ISSUE TITLE
Space-pad output in example/dns_stats.cpp

### ISSUE THREAD

**Issue by gvanem** [mfontanini/libtins#118]
I've just discovered this cool project and built it using MSVC 2015. Here is a simple fix to the output in `dns_stats.cpp`;  When the previous output-line is longer than the current, the `Count:` value is seemingly wrong.  E.g. it could jump from `Count: 104` to `Count: 1050`. 
So just pad over with some extra spaces on the current line:
```
--- a/examples/dns_stats.cpp  2015-12-24 21:18:23
+++ b/examples/dns_stats.cpp  2015-12-25 18:44:33
@@ -189,7 +189,7 @@
             auto info = monitor.stats().get_information();
             std::cout << "\rAverage " << info.average.count()
                         << "ms. Worst: " << info.worst.count() << "ms. Count: "
-                        << info.count;
+                        << info.count << "   ";
             std::cout.flush();
             std::this_thread::sleep_for(std::chrono::seconds(1));
         }
```

**Comment by mfontanini** [comment]
Thanks! If you want, you can make a pull request, that makes it easier for me to merge your code, and also makes you a contributor :)

Otherwise, I can push this patch later.

**Comment by gvanem** [comment]
>  If you want, you can make a pull request, 

Meaning create a fork, local change, git pull? No, thanks too complicated. Don't know how either.

**Comment by mfontanini** [comment]
Okay, no problem, I'll patch it later.
