### ISSUE TITLE
Crash in arpmonitor.exe

### ISSUE THREAD

**Issue by gvanem** [mfontanini/libtins#119]
Running `arpmonitor.exe \Device\NPF_{12735646-79BF-4583-8A95-35F25DE96B7E}`
causes a strange crash (build with MSVC 2015, Release on Win-10):
```
ucrtbase!abort+0x4b
ucrtbase!terminate+0x3b
arpmonitor!__scrt_unhandled_exception_filter+0x40
KERNELBASE!UnhandledExceptionFilter+0x111
ntdll!RtlSetCurrentTransaction+0x10e
ntdll!RtlSetCurrentTransaction+0x9f
```

 But running with a GUID, it off-course works:
```
arpmonitor.exe {12735646-79BF-4583-8A95-35F25DE96B7E}
```
Although I seem to get only *1* ARP-reply. 

Anybody know what this `__scrt_unhandled_exception_filter` is all about? Where and what triggers it? Here are some of my `CFLAGS` (MSVC 2015):
```
-MD -GF -GR -Zc:auto,threadSafeInit
```
Maybe WinPcap isn't able to handle the call:
```
 PacketOpenAdapter ("\Device\NPF_\Device\NPF_{12735646-79BF-4583-8A95-35F25DE96B7E}")
```
Same bug in dns_queries.exe too.

**Comment by mfontanini** [comment]
I fixed the crash issue, it was just not checking if creating the sniffer failed (which was failing because the provided interface is invalid).

I don't know about the "only one ARP" issue. Maybe it's yet another Windows limitation? Do you see more than that on wireshark?

**Comment by gvanem** [comment]
> I don't know about the "only one ARP" issue. 

I modified to arpmonitor.cpp to show `ARP::REQUEST` too. It seems to work as I hoped:
```
+    else if(arp.opcode() == ARP::REQUEST) 
+          std::cout << "[INFO] who has " << arp.target_ip_addr() << "   " << std::endl;
```
