### ISSUE TITLE
In order to make mingw64  with g++4.8.3. I must do these modify to make success. 

### ISSUE THREAD

**Issue by jiamo** [mfontanini/libtins#122]
diff --git a/src/ip_address.cpp b/src/ip_address.cpp
    index ce3e06e..3f676ed 100644
    --- a/src/ip_address.cpp
    +++ b/src/ip_address.cpp
    @@ -27,6 +27,17 @@
      *
      */
     
    +// add by ikfb
    +#ifndef WINVER
    +#define WINVER 0x0600
    +#endif
    +#ifndef _WIN32_WINNT
    +#define _WIN32_WINNT 0x0600
    +#endif
    +#ifndef NTDDI_VERSION
    +#define NTDDI_VERSION 0x06000000
    +#endif
    +
     #ifdef _WIN32
         #include <ws2tcpip.h>
     #else // _WIN32
    @@ -80,6 +91,7 @@ std::string IPv4Address::to_string() const {
     uint32_t IPv4Address::ip_to_int(const char* ip) {
         #ifdef _WIN32
             in_addr addr;
    +        //if(InetPtonA(AF_INET, ip, &addr)) {  // There is something 
             if(InetPtonA(AF_INET, ip, &addr)) {
                 return Endian::be_to_host(addr.s_addr);
             }
    diff --git a/src/ipv6_address.cpp b/src/ipv6_address.cpp
    index 44b9ac0..8f9f16e 100644
    --- a/src/ipv6_address.cpp
    +++ b/src/ipv6_address.cpp
    @@ -73,8 +73,10 @@ void IPv6Address::init(const char *addr) {
                 ULONG dummy1;
                 USHORT dummy2;
                 // Maybe change this, mingw doesn't have any other conversion function
    -            if(RtlIpv6StringToAddressExA(addr, (IN6_ADDR*)address, &dummy1, &dummy2) != NO_ERROR)
    -                throw malformed_address();
    +
    +// disable it
    +//            if(RtlIpv6StringToAddressExA(addr, (IN6_ADDR*)address, &dummy1, &dummy2) != NO_ERROR)
    +//                throw malformed_address();
             #endif
         #else
             if(inet_pton(AF_INET6, addr, address) == 0)
    @@ -91,8 +93,9 @@ std::string IPv6Address::to_string() const {
                     throw malformed_address();
             #else
                 ULONG sz = sizeof(buffer);
    -            if(RtlIpv6AddressToStringExA((const IN6_ADDR*)address, 0, 0, buffer, &sz) != NO_ERROR)
    -                throw malformed_address();
    +// disable by ikfb
    +//            if(RtlIpv6AddressToStringExA((const IN6_ADDR*)address, 0, 0, buffer, &sz) != NO_ERROR)
    +//                throw malformed_address();
             #endif
         #else
             if(inet_ntop(AF_INET6, address, buffer, sizeof(buffer)) == 0)
    diff --git a/src/network_interface.cpp b/src/network_interface.cpp
    index ab1dc76..fca0949 100644
    --- a/src/network_interface.cpp
    +++ b/src/network_interface.cpp
    @@ -118,7 +118,8 @@ struct InterfaceInfoCollector {
                 const IP_ADAPTER_UNICAST_ADDRESS *unicast = iface->FirstUnicastAddress;
                 if(unicast) {
                     info->ip_addr = IPv4Address(((const struct sockaddr_in *)unicast->Address.lpSockaddr)->sin_addr.s_addr);
    -                info->netmask = IPv4Address(host_to_be<uint32_t>(0xffffffff << (32 - unicast->OnLinkPrefixLength)));
    +                // info->netmask = IPv4Address(host_to_be<uint32_t>(0xffffffff << (32 - unicast->OnLinkPrefixLength)));
    +                info->netmask = IPv4Address(host_to_be<uint32_t>(0xffffffff << (32 - unicast->PrefixOrigin))); // modify by ik
                     info->bcast_addr = IPv4Address((info->ip_addr & info->netmask) | ~info->netmask);
                     info->is_up = (iface->Flags & IP_ADAPTER_IPV4_ENABLED) != 0;
                     found_ip = true;

Any ideas on it?

**Comment by jiamo** [comment]
If I add "export DESTDIR=/mingw64" on bash.
`make install` will install into "\mingw64\Program Files\libtins\lib"  not I want "\mingw64\lib"  .

**Comment by mfontanini** [comment]
Thanks, I'll have a look at this. 

If you want to change the install prefix, you need to use the `CMAKE_INSTALL_PREFIX` parameter when invoking CMake. e.g.:

```shell
cmake .. -DCMAKE_INSTALL_PREFIX=/mingw64
```

See the [documentation](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html) on that variable

**Comment by mfontanini** [comment]
Did you cross-compile this on Linux using mingw or did you run this on Windows? I'm building it on Linux using mingw and the only change I had to make was the `ip_address.cpp` macro definitions. The rest builds just fine.

**Comment by jiamo** [comment]
I try to build on Windows. I think it is no need any more. close it.
