### ISSUE TITLE
How to send IP packet ?

### ISSUE THREAD

**Issue by sherifmagdy** [mfontanini/libtins#124]
when i try to construct and send a packet like below it give me an error on windows ,

PacketSender sender;
IP pkt = IP("192.168.0.1") / TCP(22) / RawPDU("foo");
sender.send(pkt);

it work fine if i encapsulate that packet as ethernet frame

**Comment by mfontanini** [comment]
Is this fixed if you use admin privileges as well?

**Comment by sherifmagdy** [comment]
it still throw in L3_send with admin priv.

**Comment by mfontanini** [comment]
This is just how Windows works. See https://msdn.microsoft.com/en-us/library/windows/desktop/ms740548(v=vs.85).aspx

Quoting:

```
On Windows 7, Windows Vista, Windows XP with Service Pack 2 (SP2), and Windows XP with 
Service Pack 3 (SP3), the ability to send traffic over raw sockets has been restricted in 
several ways:

* TCP data cannot be sent over raw sockets.
```

**Comment by mfontanini** [comment]
You can send it using ethernet encapsulation because that ends up using `pcap_sendpacket` which uses the Winpcap driver, which bypasses those restrictions.

**Comment by mfontanini** [comment]
Closing this as it's an OS limitation, unrelated to libtins.
