### ISSUE TITLE
traceroute example crash on windows

### ISSUE THREAD

**Issue by sherifmagdy** [mfontanini/libtins#125]
when i run traceroute on windows it crash here 

void PacketSender::send_l3(PDU &pdu, struct sockaddr* link_addr, uint32_t len_addr, SocketType type) {
    open_l3_socket(type);
    int sock = _sockets[type];
    PDU::serialization_type buffer = pdu.serialize();
    if(sendto(sock, (const char*)&buffer[0], static_cast<int>(buffer.size()), 0, link_addr, len_addr) == -1)
        throw socket_write_error(make_error_string());
}

it throw the write error above ,,

**Comment by mfontanini** [comment]
Are you running this using administrator privileges?

**Comment by sherifmagdy** [comment]
thanks , it works now when i opened VS as admin

**Comment by mfontanini** [comment]
Great!
