### ISSUE TITLE
What "PDU *PDU::recv_response()" function do ??

### ISSUE THREAD

**Issue by sherifmagdy** [mfontanini/libtins#126]
i 'm trying to test specific port on my gateway whether it opened or not on a windows machine using this code from tutorial :

// The sender
	PacketSender sender;
	// The SYN to be sent.
	IP pkt = IP("11.0.0.1","11.0.0.77") / TCP(7777, 7777);
	NetworkInterface inf = NetworkInterface::default_interface() ;
	NetworkInterface::Info info= inf.addresses() ;
	
	EthernetII x = EthernetII("70:72:3C:39:60:34",info.hw_addr)/pkt ;
	pkt.rfind_pdu<TCP>().set_flag(TCP::SYN, 1);

	// Send and receive the response.
	std::unique_ptr<PDU> response(sender.send_recv(x,inf));
	// Did we receive anything?
	if(response) {
		TCP &tcp = response->rfind_pdu<TCP>();
		if(tcp.get_flag(TCP::RST)) 
			std::cout << "Port is closed!" << std::endl;
		else
			std::cout << "Port is open!" << std::endl;

the response is always empty and from debugging this function always return null , is there anything i'm missing ?? 

PDU *PDU::recv_response(PacketSender &, const NetworkInterface &) { 
    return 0; 
}

**Comment by mfontanini** [comment]
That method is implemented on derived classes to dispatch properly to PacketSender::recv_l2 and PacketSender::recv_l3. Unfortunately, capturing a L2 response on Windows doesn't work. I should probably make that throw an exception.

This is due to the send/capture response mechanism using sockets and Windows doesn't allowing capturing L2 packets. 

You should check the [portscan](https://github.com/mfontanini/libtins/blob/master/examples/portscan.cpp) example, which does more or less what you want.

**Comment by sherifmagdy** [comment]
portscan example still throw an exception when sending L3 BDU as usual ,
    for (set<uint16_t>::const_iterator it = ports_to_scan.begin(); it != ports_to_scan.end(); ++it) {
        // Set the new port and send the packet!
        tcp.dport(*it);
        sender.send(ip);   // Sending Here
    }

is n't there any method to accomplish this on windows ?

**Comment by mfontanini** [comment]
That should work, are you running it as admin? It doesn't work if you send data over TCP. SYN packets should be sent (I actually ran this portscan example on Windows 7 and it worked).

**Comment by sherifmagdy** [comment]
i ran it as admin on windows 10 using the same code except for pthread stuff  i removed them and still can't figure out the problem .

**Comment by mfontanini** [comment]
Okay I take that back, the portscan example doesn't compile on Windows, hence I never tried it.

I'll have a look at this later today, will let you know if this is a Windows limitation or just that the library is doing something wrong.

**Comment by mfontanini** [comment]
So, maybe I interpreted that Windows quote incorrectly. When it says:

`TCP data cannot be sent over raw sockets.`

I think it actually means that you can't even send TCP packets without any payload... It seems like the only way to send TCP packets on Windows is by using Ethernet encapsulation and using pcap_sendpacket.

**Comment by sherifmagdy** [comment]
so how i could accomplish my task using libtins ?

**Comment by mfontanini** [comment]
Use ethernet encapsulation or use another OS, like GNU/Linux where there are no ridiculous constraints to what you can do with a raw socket (you could use a vm for this).

**Comment by sherifmagdy** [comment]
my task must be done under windows ,and if i use ethernet encapsulation i don't capture any responses .

**Comment by mfontanini** [comment]
You can run a sniffer instance on one thread and send the packets on another, just like the portscan example does.

**Comment by sherifmagdy** [comment]
okay i will try that , thanks

**Comment by mfontanini** [comment]
Closing this as this is not an actual issue

**Comment by WorstCodeWay** [comment]
@sherifmagdy Hi, have you solved your problem? I meet this same problem on Win10 x64. I tried a lot and searched a lot, no good news. Totally, run `portscan.cpp` or `send_recv` (just as you do) giving me errors (10022 error-code).

So, could you share your solution to this problem?
