### ISSUE TITLE
SNAP org_code() bug - Can't set IOU correctly

### ISSUE THREAD

**Issue by asjadsyed** [mfontanini/libtins#127]
I was having trouble setting the Organization Code and the Protocol ID of a SNAP packet, and after a bit of debugging with Wireshark I noticed that org_code() was setting data in the wrong areas (off by a few bytes)

[snaporgcodebug.txt, rename to .cpp](https://github.com/mfontanini/libtins/files/115137/snaporgcodebug.txt)
I have attached a sample program, and as I'm sure you know, compile with
$ g++ snaporgcodebug.cpp -ltins -std=c++11 -o snaporgcodebug
run it with
$ ./snaporgcodebug
that will create a pcap, inspect that in Wireshark with
$ wireshark snaporgcodebug.pcap
There's some more explanation that is printed when you run the program

Thanks.

**Comment by mfontanini** [comment]
Without testing this, I think you shouldn't be adding LLC here. SNAP represents an LLC+SNAP frame, so the LLC part should be already there. Can you try doing it that way?

Thanks!

PS: thanks for the code to reproduce the issue, I really appreciate it!

**Comment by mfontanini** [comment]
Okay so yes, just use SNAP. There seems to be an issue though, the RSNEAPOL frame gets corrupted but that seems to be radiotap's fault. If you set `radiotap.flags(RadioTap::FrameFlags())` to disable the FCS-at-end option, it seems to work fine. 

I'm looking into the RadioTap issue now.

**Comment by mfontanini** [comment]
Okay I just fixed the RadioTap issue. Can you confirm if your issue is fixed by using the latest code?

Thanks!

**Comment by asjadsyed** [comment]
After updating libtins, setting the radiotap layer's flags, and removing the extra LLC layer, I am able to use with the lower layer correctly and verify it in Wireshark.

In case anyone gets here and is getting a Malformed Packet error in Wireshark, it is because the length field of the EAPOL PDU is initialized to 0. The .length(uint16_t) setter in an RSN EAPOL is inherited from Tins::EAPOL, so expand the "Public Member Functions inherited from Tins::EAPOL" section to see it in the docs.

Thank you again, you responded so quickly that I assumed the email I got was a notification from GitHub (that a new issue was created) and went off to sleep!

**Comment by mfontanini** [comment]
Great, thanks for the reply!
