### ISSUE TITLE
Unable to set capability_information on a Dot11ProbeResponse

### ISSUE THREAD

**Issue by derekpanderson** [mfontanini/libtins#128]
I need to set the values for capability_information on an 802.11 probe response. The functions seem to be present for a Dot11ManagementFrame. Is there a way to set the parameters like ess short preamble and so on? Currently they are all set to 0 when I send out a Dot11ProbeResponse using a PacketSender to send the traffic. 
![screenshot_021616_024714_pm](https://cloud.githubusercontent.com/assets/3999502/13088899/2f517b54-d4bc-11e5-8317-93d45036672c.jpg)

**Comment by mfontanini** [comment]
I think if you do this, it should work:

```c++
Dot11ProbeResponse response;
Dot11ProbeResponse:: capability_information& capability = response.capabilities();
capability.short_preamble(true);
capability.ess(true);
// ....
```

**Comment by derekpanderson** [comment]
Awesome that worked perfectly. 

One other thing I ran into(Let me know if it should be a new issue) In src/dot11/dot11_mgmt.cpp if a probe request is sent from a client without a SSID set you return the string "BROADCAST". But BROADCAST can be a valid SSID name, e.g like my neighbour had set. I changed it to return "" to mimic what scapy returns.

**Comment by mfontanini** [comment]
Hmmm I wonder why it wasn't that way in the first place. Is there no other case that you know of where the SSID can be a present and have length 0?

**Comment by mfontanini** [comment]
Actually, that shouldn't matter. If the SSID has length 0, then it should be an empty string.

**Comment by derekpanderson** [comment]
I have seen some clients send out a ' ' in the ssid field when probing. In that case scapy returnes a ' '.

**Comment by mfontanini** [comment]
Okay I just pushed a fix. If you find any other issues, please let me know

**Comment by derekpanderson** [comment]
Seems to work fine. Thanks for the fast response!
