### ISSUE TITLE
Please make a new release/tag

### ISSUE THREAD

**Issue by insomniacslk** [mfontanini/libtins#131]
Hello,

would it be possible to make a new release (v3.4) to include the latest changes? I am trying to release a brew formula for a package (dublin-traceroute) that depends on libtins (specifically, on this revision, https://github.com/mfontanini/libtins/commit/5d41316b9a952ea26f0f35e15b5ac5702d9fc973 ), but brew does not allow to depend on a HEAD target. A new minor release would override the problem - and there are definitely a lot of commits since the v3.3 :)

**Comment by mfontanini** [comment]
I still have a few things I want to implement before doing a new release. Are you using any features that weren't there on 3.3?

**Comment by mfontanini** [comment]
Oh right, I forgot you spotted the issue on OSX. I'll see what I can do about it tonight. Maybe I could wrap up a few things and push the new tag.

**Comment by insomniacslk** [comment]
Thanks - this is not urgent though, if you are near to a new release just follow your original schedule :)

**Comment by mfontanini** [comment]
Yeah, I'll check tonight what I still have left to do. Some stuff requires some time so I might just move them to the next release. I'll give you an update later today.

**Comment by mfontanini** [comment]
Just pushed the v3.4 tag :). Haven't build the brew formula yet though

**Comment by insomniacslk** [comment]
Awesome :) Thanks! I can make the pull request to homebrew to bump the version

**Comment by insomniacslk** [comment]
FYI created https://github.com/Homebrew/homebrew/pull/49956

**Comment by mfontanini** [comment]
Awesome, thank you!
