### ISSUE TITLE
Dot11 can't send packets

### ISSUE THREAD

**Issue by gj12** [mfontanini/libtins#136]
Hi,

I'm coding an software AP with libtins. Unfortunately I can't transmit packets.

Answering to probe requests or sending beacons doesn't work
eg:
```
				Dot11ProbeResponse probe_resp;
				probe_resp.addr1(probe_req.addr2()); //reply to sender
				probe_resp.addr2(this->if_addr);// my interface addr
				probe_resp.addr3(this->if_addr);
				probe_resp.ds_parameter_set(11);
				probe_resp.ssid("my SSID");
				probe_resp.supported_rates({1.0f, 2.0f, 5.5f, 11.0f, 6.0f, 9.0f, 12.0f, 18.0f});
				probe_resp.extended_supported_rates({4.0f, 36.0f, 48.0f, 54.0f});
				sender.send(probe_resp,"mon0");
```
I don't get an error/exeption etc. There are no packets from me in Wireshark/airodump-ng. Packet injection works with aircrack etc. 

Card: Atheros AR9271 ath9k_htc/htc_9271-1.4.0.fw
System: Linux 4.4.4 x86_64

**Comment by gj12** [comment]
After using ifconfig mon0 up I get packets, but they are corrupted:
[wireshark.zip](https://github.com/mfontanini/libtins/files/176193/wireshark.zip) (broadcasting beacons  with SSID:"myssid" )

**Comment by mfontanini** [comment]
You need to use RadioTap encapsulation on your packets. If you check the packets you're capturing (the ones not generated by you), you'll see they all have this encapsulation. 

This should work, although you might have to tweak some options on the radiotap header so your network driver/card likes your packets:

```c++
RadioTap actual_packet = RadioTap() / probe_resp;
sender.send(actual_packet, "mon0");
```

**Comment by gj12** [comment]
Thank you. It's working :)

**Comment by iambanh2** [comment]
Sorry. How to add rawPDU to probe request / response. T_T
