### ISSUE TITLE
Exception thrown on ICMPv6 packets

### ISSUE THREAD

**Issue by einarjon** [mfontanini/libtins#138]
Tins assumes that all MLD queries are MLDv2.
MLDv1 is shorter and ends after the IPv6 address, so trying to read the multicast_listener_query_message_fields fails
Below is a packet that was throwing a malformed_packet exception on my system

Further reading:
http://www.networksorcery.com/enp/protocol/mld.htm
https://www.ietf.org/rfc/rfc3810.txt

// failing test in tests/src/ipv6.cpp
TEST_F(IPv6Test, MDLv1Request) {
    const uint8_t mldv1[] = {
        51, 51, 0, 0, 0, 1, 100, 112, 2, 226, 169, 250, 134, 221, 96, 0, 0, 0, 0, 32, 0, 1, 254,
        128, 0, 0, 0, 0, 0, 0, 102, 112, 2, 255, 254, 226, 169, 250, 255, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 58, 0, 5, 2, 0, 0, 0, 0, 130, 0, 70, 203, 39, 16, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    EthernetII pkt(mldv1,  sizeof(mldv1));
    EXPECT_EQ(
        PDU::serialization_type(mldv1, mldv1+ sizeof(mldv1)),
        pkt.serialize()
    );
}

**Comment by mfontanini** [comment]
Oh damn. I'll look into this later today. Thanks!

**Comment by mfontanini** [comment]
Fixed! Thanks for the test case!

**Comment by einarjon** [comment]
That was fast. Thanks.

Your code is really elegant.
Easy to understand, and you make it look so simple.

On 18 March 2016 at 07:36, Matias Fontanini <notifications@github.com>
wrote:

> Fixed! Thanks for the test case!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mfontanini/libtins/issues/138#issuecomment-198228699>
>



-- 
Regards
Einar Jón
+43 650 291 3472

**Comment by mfontanini** [comment]
Thanks man!
