### ISSUE TITLE
Dot11 multiple SSIDs

### ISSUE THREAD

**Issue by gj12** [mfontanini/libtins#139]
Hi,
calling `someDot11Packet.ssid("some ssid");` multiple times, ads the SSID tag multiple times to the packet. Is this a bug or do I need to create a new packet everytime? Is there a way to remove the old tag?

Example packet: 
[wireshark2.zip](https://github.com/mfontanini/libtins/files/178044/wireshark2.zip)

**Comment by mfontanini** [comment]
libtins doesn't restrict the amount of times you add an option. If you want to remove one, use [`Dot11::remove_option`](http://libtins.github.io/docs/latest/d8/df1/classTins_1_1Dot11.html#a832cd9bc19962a2ff40f875251bbea30)

**Comment by gj12** [comment]
Thank you.

Ps: libtins made my life so much easier. Keep up the good work!

**Comment by mfontanini** [comment]
Thank you! If you find any other issue, please let me know. I haven't played too much with Dot11 so there might be some lying around :P
