### ISSUE TITLE
"IN" double define

### ISSUE THREAD

**Issue by LegITdevel** [mfontanini/libtins#141]
On Win32 platform with MSVC2013 and MSVC2015, you can not include libtins without adding "#undef IN" in line 42 in /tins/dns.h.

This seems to happen because IN is already defined in WinSock2.h

**Comment by mfontanini** [comment]
Hey. I think someone reported this a while back, I guess it's time to fix it, even though this is not an issue on libtins but it's whoever wrote that code in Windows and had the amazing idea of creating a macro name which is only 2 chars long. 

I'll probably rename IN to INTERNET, also keeping the old IN name but doing an undef at the beginning of the file... Eventually I'll remove IN and leave only INTERNET.

Thanks!

**Comment by LegITdevel** [comment]
Hey,

yeah I figured, tho it's easier and faster to get a fix here than on WinSock2 haha ;-)

It leads to a lot of following failures, so it should probably clear some of the other hotifxes I had to apply.
