### ISSUE TITLE
TINS_STATIC documentation or automatically included in config.h

### ISSUE THREAD

**Issue by rmbreak** [mfontanini/libtins#142]
When building with LIBTINS_BUILD_SHARED=0 on Windows platform, I had linker errors until I manually defined TINS_STATIC in my client code.

Should libtins automatically define or undef TINS_STATIC in the config.h during the makefile generation? If not, perhaps including a line in the documentation that states consumers of libtins must manually define TINS_STATIC when building a static version of the library.

**Comment by mfontanini** [comment]
See #120 for information about this. Apparently it's not good to include `TINS_STATIC` on the config.h file as it forces the user to have to run CMake again. 

I thought there was a mention of this macro somewhere but apparently there isn't. I'll add that now, thanks!

**Comment by rmbreak** [comment]
Oh I see. Suppose users have built libtins as both a static and dynamic library, in which case the user must specify which one to use on their project.

Thanks for the fantastic work on libtins!

**Comment by mfontanini** [comment]
Thanks! Pushed this to the website on the download section, "Using on Windows" subsection.
