### ISSUE TITLE
Several Unresolved Symbols - Windows

### ISSUE THREAD

**Issue by LegITdevel** [mfontanini/libtins#143]
For the following code, I get the 3 unresolved symbols. I'm linking against:

                -lshlwapi \
                -lpsapi \
                -lwpcap \
                -lws2_32 \
                -liphlpapi \
                -ltins

```
    Tins::NetworkInterface defaultInterface = Tins::NetworkInterface::default_interface();
    tinsInterfaces.push_back(defaultInterface);
    QString defaultIntf = QString::fromWCharArray(defaultInterface.friendly_name().c_str());
    ui->lanScanIntf->addItem(defaultIntf);
```

```
    std::vector<Tins::NetworkInterface> ifs = Tins::NetworkInterface::all();
    for (unsigned int i = 0; i < ifs.size(); i++)
    {
        if (true)
        {
            tinsInterfaces.push_back(ifs.at(i));
            QString Intf = QString::fromWCharArray(ifs.at(i).friendly_name().c_str());
            ui->lanScanIntf->addItem(Intf);
        }
    }

```

Any idea is welcome!

**Comment by mfontanini** [comment]
Which undefined symbols do you get? Also note that the order in which you specify libraries to link matters. Since libtins uses libpcap, then libtins should appear before libpcap

**Comment by LegITdevel** [comment]
mainwindow.obj:-1: error: LNK2019: undefined external symbol ""__declspec(dllimport) public: static class Tins::NetworkInterface __cdecl Tins::NetworkInterface::default_interface(void)" (__imp_?default_interface@NetworkInterface@Tins@@SA?AV12@XZ)" in Funktion ""private: void __thiscall MainWindow::updateInterfacesList(void)" (?updateInterfacesList@MainWindow@@AAEXXZ)".

mainwindow.obj:-1: error: LNK2019: undefined external symbol ""__declspec(dllimport) public: static class std::vector<class Tins::NetworkInterface,class std::allocator<class Tins::NetworkInterface> > __cdecl Tins::NetworkInterface::all(void)" (__imp_?all@NetworkInterface@Tins@@SA?AV?$vector@VNetworkInterface@Tins@@V?$allocator@VNetworkInterface@Tins@@@std@@@std@@XZ)" in Funktion ""private: void __thiscall MainWindow::updateInterfacesList(void)" (?updateInterfacesList@MainWindow@@AAEXXZ)".

mainwindow.obj:-1: error: LNK2019: undefined external symbol ""__declspec(dllimport) public: class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __thiscall Tins::NetworkInterface::friendly_name(void)const " (__imp_?friendly_name@NetworkInterface@Tins@@QBE?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ)" in Funktion ""private: void __thiscall MainWindow::updateInterfacesList(void)" (?updateInterfacesList@MainWindow@@AAEXXZ)".

**Comment by mfontanini** [comment]
You need to define `TINS_STATIC` when you're using a static build on windows. See [this](http://libtins.github.io/download/#using-windows)

**Comment by LegITdevel** [comment]
I know, but this is not a static build... It's just a normal MSVC2015/MSVC2013 compilation. Didn't try static, yet.

**Comment by mfontanini** [comment]
So, if it's not static then you've built a DLL, right? Is the DLL on Windows/system32? I think that's the place were it should be.

**Comment by LegITdevel** [comment]
Nope, you always place em with your app's binary. System32 should not be used as directory for third party libraries. https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

**Comment by LegITdevel** [comment]
Just tried a static build and it results in the same error messages.

**Comment by mfontanini** [comment]
Exactly which erros do you get? Are you defining `TINS_STATIC`?
