### ISSUE TITLE
PCAP filter not working properly

### ISSUE THREAD

**Issue by rabinnh** [mfontanini/libtins#145]
Running the example dns query capture program, I saw some output. 

I then modifed the filter to use the following line to capture dns traffic hitting the local dns proxy, a slight mod to the example:

    config.set_filter("udp and (dst host 127.0.1.1) and (dst port 53)");

Then ran 'dig @127.0.1.1 www.test.com'

No traffic appeared.  I then copied and pasted the same filter into Wireshark and saw the expected traffic, for example:

1	0.000000000	127.0.0.1	127.0.1.1	DNS	85	Standard query 0x0835  A www.test.com

**Comment by mfontanini** [comment]
Are you capturing on `lo`? Are you using Windows?

**Comment by rabinnh** [comment]
No I'm using Linux.  This is embarrassing; you're right.  I forgot to switch it to lo from eth0.

**Comment by mfontanini** [comment]
No problem!
