### ISSUE TITLE
Bug on MacOS (and xBSD)

### ISSUE THREAD

**Issue by Pflanzgurke** [mfontanini/libtins#147]
Hi,

I might have found a bug. It seems that send_recv in packet_sender.cpp is not always working correctly on Mac OS and BSDs. I think I know why: the defines for BSD trying to read from a bpf device in recv_match_loop which has not been opened I guess. It appears the bfp devices are used for L2 "things". But there is a path into recv_match_loop which will open a plain old socket through recv_l3. This is the offending code:

```
     #if defined(BSD) || defined(__FreeBSD_kernel__)             
                        size = ::read(*it, buffer, buffer_size_);               
                        const uint8_t* ptr = buffer;                            
                        // We might see more than one packet                    
                        while (ptr < (buffer + size)) {                         
                            const bpf_hdr* bpf_header = reinterpret_cast<const bpf_hdr*>(ptr);
                            const uint8_t* pkt_start = ptr + bpf_header->bh_hdrlen;
                            if (pdu.matches_response(pkt_start, bpf_header->bh_caplen)) {
                                return Internals::pdu_from_flag(pdu.pdu_type(), pkt_start, bpf_header->bh_caplen);
                            }                                                   
                            ptr += BPF_WORDALIGN(bpf_header->bh_hdrlen + bpf_header->bh_caplen);
                        }                                                       
                    #else 
```

Commenting the code out (and the other BSD specifics in that function) works for me as a quick fix for my purposes, but a propper fix would be great. In addition to the defines, there needs to be some runtime checking to see what kind of underlying socket is open I guess. Here is a small test program to reproduce the behavior:

```                                                                                                             
using namespace std;                                                            
using namespace Tins;                                                           
                                                                                
int main () {                                                                   
    //NetworkInterface std_if("en0");                                           
    PacketSender sender;                                                        
                                                                                
    IP pkt = IP("192.168.4.1") / ICMP(ICMP::ECHO_REQUEST);                      
                                                                                
    unique_ptr<PDU> response(sender.send_recv(pkt));                            
                                                                                
    if (response) {                                                             
        cout << "Jolly good" << endl;                                           
    } else {                                                                    
        cout << "Wat" << endl;                                                  
    }                                                                           
}     

```

BTW, is there any reason for this

```
#ifdef BSD                                                              
            throw runtime_error("Receiving L3 packets not supported on this platform");
#endif
```
in recv_l3() in packet_sender.cpp? This means it will also not work on Mac OS since BSD is defined in sys/param.h

**Comment by mfontanini** [comment]
Thanks, I'll look into this later today!

**Comment by mfontanini** [comment]
I can't make this thing work, even if I use the opened ICMP socket in the proper way. I'll look a bit more into this tomorrow.

BTW, apparently on OSX you can't read from TCP/UDP sockets, so that's why that `throw` is there. See http://sock-raw.org/papers/sock_raw. Specifically:

````
b. FreeBSD
**********

FreeBSD takes another approach. It *never* passes TCP or UDP packets to raw
sockets. Such packets need to be read directly at the datalink layer by using
libraries like libpcap or the bpf API. It also *never* passes any fragmented 
datagram. Each datagram has to be completeley reassembled before it is passed
to a raw socket.
FreeBSD passes to a raw socket:
    a) every IP datagram with a protocol field that is not registered in
    the kernel
    b) all IGMP packets after kernel finishes processing them
    c) all ICMP packets (except echo request, timestamp request and address
    mask request) after kernel finishes processes them
```

**Comment by mfontanini** [comment]
Okay, I pushed a fix for this to the develop branch. That code is really crappy and should probably changed soon, it's pretty hard to see what's being done on each platform.

Thanks for the report!

**Comment by Pflanzgurke** [comment]
I am not so sure the above holds for Mac OS. At least "man ip" says:

If proto is 0, the default protocol IPPROTO_RAW is used for outgoing packets, and only incoming packets destined for that protocol are received.  If proto is non-zero, that protocol number will be used on outgoing packets and to filter incoming packets.

Also, Mac OS has ICMP sockets for a few ICMP types (man icmp), which would allow libtins to send e.g. ECHO REQUESTS without special privileges, i.e. without having root privileges. But that would require a bit of work which is probably not worth the code complexity it introduces.
