### ISSUE TITLE
TFTP as a PDU?

### ISSUE THREAD

**Issue by nelsonw2014** [mfontanini/libtins#150]
Hi there, currently developing a TFTP ([Trivial File Transfer Protocol](https://en.wikipedia.org/wiki/Trivial_File_Transfer_Protocol)) PDU type for libtins to be used with another project of mine. Is there desire for this PDU to be included in libtins? Or is this functionality outside the scope of the typical use cases?

Code base for the pdu isn't done quite yet, but just wanted to get a feel for if I should start gearing development towards a potential pull request. Thanks!

**Comment by mfontanini** [comment]
Hi! Even though I really appreciate PRs and contributions, I don't really want to start adding application layer protocols to libtins. The only ones supported right now (DNS, DHCP, I think that's it) are protocols that you'll see on every network and basically make some aspect of the network work.

If we start adding some other unrelated app layer protocols, the library could start being bloated with lots of protocols which could rarely be seen. 

This could be a separate project though, as having some parser for other protocols would be nice.

**Comment by nelsonw2014** [comment]
That's kinda the feeling I got. Either way, wanted to offer it. Thanks for the quick response :)
