### ISSUE TITLE
Issue with undefined symbol associated with custom PDU class in library

### ISSUE THREAD

**Issue by foreverska** [mfontanini/libtins#156]
I am trying to define my own PDU class in a library.  When I try to compile my test code the linker complains about a missing symbol in my library, _ZN8profinet4LLDP8pdu_flagE.  This is the pdu_flag of my custom PDU.  The library is compiled with -ltins (version 3.4/installed by apt-get on debian sid) and the header where pdu_flag is defined is a copy and paste of the example except for changing the name of the class to LLDP.

I'm sure it's something I'm doing wrong so any help would be greatly appreciated.

**Comment by mfontanini** [comment]
Did you give the `pdu_flag` a value or did you just declare it on the header file?

**Comment by foreverska** [comment]
That was a part I was really confused about.  I do register_allocator in another part of my code but I never pdu_flag = because what that was supposed to be set to is a bit unclear.

**Comment by foreverska** [comment]
I did just try pdu_flag = PDU::USER_DEFINED_PDU and that didn't clear up the linker error.  Even if it did it would probably cause more questions than answers regarding how one is supposed to define multiple custom PDU.

**Comment by mfontanini** [comment]
You're supposed to use `USER_DEFINED_PDU`, then `USER_DEFINED_PDU + 1`, etc. Each PDU needs a unique flag. 

Try defining the flag on the cpp file (e.g. declare it inside the .h and then give it a value on the cpp).

**Comment by foreverska** [comment]
>You're supposed to use USER_DEFINED_PDU, then USER_DEFINED_PDU + 1, etc. Each PDU needs a unique flag.

That makes sense.

> Try defining the flag on the cpp file (e.g. declare it inside the .h and then give it a value on the cpp).

This worked and produced the expected packet.  Thanks a bunch.

**Comment by foreverska** [comment]
>You're supposed to use USER_DEFINED_PDU, then USER_DEFINED_PDU + 1, etc. Each PDU needs a unique flag.

Clarification on this point, when I do this the compiler complains about invalid conversion from int to Tinst::PDU::PDUType:
src/profinet_dcp.cpp:6:60: error: invalid conversion from ‘int’ to ‘Tins::PDU::PDUType’ [-fpermissive]
 const PDU::PDUType dcp::pdu_flag = PDU::USER_DEFINED_PDU + 1;

**Comment by mfontanini** [comment]
Yes, just cast it back:

```c++
const PDU::PDUType dcp::pdu_flag = static_cast<PDU::PDUType>(PDU::USER_DEFINED_PDU + 1);
```
