### ISSUE TITLE
Exception using PacketSender with IPv6 PDU

### ISSUE THREAD

**Issue by sluser** [mfontanini/libtins#166]
When using PacketSender with an IPv6 PDU, the call to PacketSender::open_l3_socket() throws on the call to setsockopt, corresponding to an ERRON value OF ENOPROTOOPT.

This is because the "level" parameter of setsockopt is always IPPROTO_IP. For an IPv6 PDU this should be IPPROTO_IPV6.

Suggest adding, just before the call, something like:

    const int level = (type == IPV6_SOCKET) ? IPPROTO_IPV6 : IPPROTO_IP;

Thanks!

**Comment by mfontanini** [comment]
Thanks!
