### ISSUE TITLE
Dot11QoSData bug

### ISSUE THREAD

**Issue by yavuzmert** [mfontanini/libtins#167]
Hi, i think that is a small typo. Didn't create a pull request as it is just a one line difference.
Dot11QoSData throws when it is empty (Qos No data)
On line 139, we should check stream not total_sz

    InputMemoryStream stream(buffer, total_sz);
    stream.skip(Dot11Data::header_size());
    stream.read(qos_control_);
    if (total_sz) { // THIS SHOULD BE "if (stream) {" 
        // If the wep bit is on, then just use a RawPDU
        if (wep()) {
            inner_pdu(new Tins::RawPDU(stream.pointer(), stream.size()));
        }
        else {
            inner_pdu(new Tins::SNAP(stream.pointer(), stream.size()));
        }
    }

**Comment by mfontanini** [comment]
Good catch. This was introduced when adding that `InputMemoryStream` class :/. If you want to create a PR it's fine, otherwise I'll fix this when I have some time.
