### ISSUE TITLE
C++11 Features unsupported when cross-compiling for ARM

### ISSUE THREAD

**Issue by NTAuthority98** [mfontanini/libtins#169]
Hello, I've been tiredlessly trying to cross-compile libtins for armv8 using crosstool-ng toolchain but I just can't wrap my head around a weird issue that arises whenever I issue the "cmake ../" command. The makefile gets generated but the log says some C++11 features are unsupported (namely decltype, functional and some other C++11 features) even though they're all supported. I even tried compiling a c++11 program using <functional> and it compiled just fine. Any help is highly appreciated!

**Comment by mfontanini** [comment]
Hi, sorry for the delay on the response. Apparently the script that checks the C++11 features requires you to use the `-DCROSS_COMPILE=1` flag when building. I just added that to the [tutorial](http://libtins.github.io/cross-compile/) on how to cross compile the library. Thanks!

**Comment by NTAuthority98** [comment]
Thanks! Great job as always, I really love libtins.

Il 23/Ott/2016 20:35, "Matias Fontanini" <notifications@github.com> ha
scritto:
