### ISSUE TITLE
FreeBSD 11 RTF_WASCLONED and RTF_PRCLONING

### ISSUE THREAD

**Issue by johndickinson** [mfontanini/libtins#174]
Building on FreeBSD11 make complains that RTF_PRCLONING and RTF_WASCLONED are undefined. AFAIK they were removed in FreeBSD 8.. They are commented out in /usr/include/net/route.h.

`/home/jad/libtins/src/utils.cpp:247:31: error: use of undeclared identifier
      'RTF_WASCLONED'
        if ((rtm->rtm_flags & RTF_WASCLONED) == 0 || (rtm->rtm_flags & R...
                              ^
/home/jad/libtins/src/utils.cpp:247:72: error: use of undeclared identifier
      'RTF_PRCLONING'
        if ((rtm->rtm_flags & RTF_WASCLONED) == 0 || (rtm->rtm_flags & RTF_PRCLO...
                                                                       ^`

**Comment by mfontanini** [comment]
Yay for backwards compatibility. Thanks, I'll try to fix that later today.

**Comment by banburybill** [comment]
That does look like the correct fix.
