### ISSUE TITLE
Very slow packet sending/sniffing of outgoing packets on Raspberry Pi

### ISSUE THREAD

**Issue by steven-chien** [mfontanini/libtins#180]
I am working with a network measurement tool on a Raspberry Pi and am hopping to incorporate libtins into out implementation so we can leverage libtin's awesomeTCP/IP infrastructure rather than maintaining our own. One of our requirement is that we have to timestamp our outgoing packets when it actually leaves the computer. Our method is to send it through a raw socket on the measurement thread and capture the packet on a pcap thread. The program will only assume the packet has been sent when it is captured by the pcap thread (and timestamped). The issue I have encountered is that the packet sending/sniffing is so slow that it takes more or less one second between the send() call is invoked to the outgoing packet being sniffed by the sniffer_loop(). For the purpose of illustration I have made a gist to showcase what I'm trying to do:
[https://gist.github.com/steven-chien/9dd9e3a762d3e1fccce20d1098f80d4e](https://gist.github.com/steven-chien/9dd9e3a762d3e1fccce20d1098f80d4e)

For illustration, the program sends a TCP packet to my router every one second and I will try to capture the outgoing pkt in the sniffer_loop(). The following is the result:

```
sent packet @ 1483715514.524460
Sniffed pkt @ 1483715515.481349
sent packet @ 1483715515.525529
Sniffed pkt @ 1483715516.481207
sent packet @ 1483715516.526524
Sniffed pkt @ 1483715517.481195
sent packet @ 1483715517.527574
Sniffed pkt @ 1483715518.481200
sent packet @ 1483715518.528619
Sniffed pkt @ 1483715519.481195
```

The issue does not exist on my silly implementation with libpcap capturing and raw socket. I have enabled c++11 and am using libtins v3.4 and libpcap 1.8.1. I realize that the Raspberry Pi is not exactly a fast machine but having a delay of almost one second between sending and sniffed seems very awkward, especially the delay is negligible with a homemade raw socket + libpcap implementation.

**Comment by mfontanini** [comment]
Pcap uses buffering as of version 1.5 (IIRC). This means packets will take a bit of time before being delivered to your application.

If you want to get packets right away, you should use immediate mode:

```c++
sniff_config.set_immediate_mode(true);
```

I just tried that and the timings look okay after doing so (they looked the same as yours before using immediate mode):

```
sent packet @ 1484500053.894187
Sniffed pkt @ 1484500053.898122
sent packet @ 1484500054.895085
Sniffed pkt @ 1484500054.897907
```

Anyway, if you wanted to timestamp the packet, you should probably use the one in the `Packet` class, which is the time at which the packet was actually captured.

**Comment by ngkokkee** [comment]
Would using a newer version of libpcap improve the speed?

I am working on spoofing a wifi client with Dot11 and encounters a few retry frames from the AP due to delay in the acknowledgement frame (spoofed using a faked MAC address). The reason for using a fake MAC address is that I want to scale it up to spoof multiple devices with one dongle.

set_immediate_mode seems to help but there are still some retries so I am wondering if there is anyway to speed it up further (both receive and transmit).

**Comment by mfontanini** [comment]
Are you capturing and sending the packets on the same thread or are you sniffing into some packet queue on one and consuming it/sending packets on another? Also, are you using pcap filters to reduce the amount of packets that make it to your application? You could also consider delaying the parsing of the packets by using `Sniffer::set_extract_raw_pdus` so you get a `RawPDU` (unparsed packet) out of it, then push it into the queue and then parsing/processing/sending the response on the consumer thread.

libpcap is already fast enough, updating it shouldn't change much.

**Comment by ngkokkee** [comment]
I am running it as a single thread at the moment, will try having a separate thread for sending.

Is there a lot of latency with two sniffers running in parallel, was thinking about spawning a dedicated process that sniff for only wlan management packets and send acknowledgement responses.

**Comment by mfontanini** [comment]
I don't know if that's going to improve performance, but you can try.

You can always have one sniffer and then multiple consumers on the sniffed packets queue. Or even have a dedicated consumer for specific types of packets if that's what you need.

**Comment by steven-chien** [comment]
For my use case I am sniffing packets on a dedicated sniffer thread and giving them to consumer threads. I have tested the implementation of enabling immediate mode. I am definately going to try your suggestion of extracting RawPDU instead of parsing the packet in place on the sniffer thread. Thank you.
