### ISSUE TITLE
Filtering by Probe Response

### ISSUE THREAD

**Issue by wilson18** [mfontanini/libtins#185]
Hi 

I seem to be having trouble using the sniffer to filter by probe responses. The filter I am using is wlan.fc.type_subtype eq 5 which works in wireshark (wlan.fc.type_subtype eq 4 works correctly for requests). 

If I then do a sniffer.loop(function), that then sends pdu's to the function mentioned.

In this function I have the following:

```
cout <<"Got pckt\n";
const Dot11ProbeResponse response = pdu->rfind_pdu<Dot11ProbeResponse>();
cout << "Addr1: " << response.addr1() << "\nAddr2: " << response.addr2() << "\nAddr3: "<<response.addr3() << "\nAddr4: "<<response.addr4() <<"\n\n";
```
    

This will print plenty of 'Got pckt's but nothing else. Is this an issue with the rfind_pdu when searching for responses? Do you have any suggestions as to what the issue could be? Thanks :D

**Comment by mfontanini** [comment]
That's not a valid pcap filter syntax. Wireshark has a much richer (and incompatible) syntax, so you need to tweak it a bit. You can have a loock at the manpage for `pcap-filter` for examples but I think what you want is something like:

```
wlan type mgt subtype probe-resp
```

**Comment by wilson18** [comment]
Ah that seems to have fixed it. My apologies. Thanks :D

**Comment by iambanh2** [comment]
I got problems. Thanks for your solution.
