### ISSUE TITLE
Partial decryption using libtins

### ISSUE THREAD

**Issue by cooperarichardson** [mfontanini/libtins#190]
Using libtins 3.4 (package version [3.4-2](https://packages.debian.org/sid/libtins-dev)) on debian testing, decryption is not decrypting all packets. I made a capture file using tcpdump then processed it with libtins and compared it to Wireshark decryption. With libtins, I can see a few packets missing here and there as you can see on the following picture:

![not_all_decrypted](https://cloud.githubusercontent.com/assets/25858768/23090658/8e876122-f560-11e6-8555-84997de732d2.png)

The file on the left, ```Testing_password1.pcap```, is the original capture file, done with tcpdump (encrypted, passphrase is 'password1' without the quotes). On the right, ```decrypted.pcap```, the capture file decrypted with libtins using the following code:

```
#include <stdio.h>
#include <tins/tins.h>


using namespace std;
using namespace Tins;


PacketWriter * packet_writer = NULL;


bool handler(PDU &pdu) {
    // pdu here is not encrypted!
    packet_writer->write(pdu);
    return true;
}


int main(int argc, char **argv)
{
 if (argc != 6) {
     printf("%s PCAP_file ESSID BSSID key output_filename\n", argv[0]);
     return 1;
 }
 
 printf("Input PCAP: %s\n", argv[1]);
 printf("ESSID: %s\n", argv[2]);
 printf("BSSID: %s\n", argv[3]);
 printf("Key: %s\n", argv[4]);
 printf("Output file: %s\n", argv[5]);


 packet_writer = new PacketWriter(string(argv[5]), DataLinkType<RadioTap>());


 // This creates a decrypter proxy class. 
 auto decrypt_proxy = Crypto::make_wpa2_decrypter_proxy(&handler);
 // Same as in the previous example.
 decrypt_proxy.decrypter().add_ap_data(string(argv[4]), string(argv[2]), string(argv[3]));


 // We only need data
 SnifferConfiguration config;
 config.set_filter("type data");


 // Create a sniffer
 FileSniffer sniffer(string(argv[1]), config);
 // Sniff and decrypt!
 sniffer.sniff_loop(decrypt_proxy);


 delete packet_writer;

 printf("Decryption done\n");

 return 0;
}
```

You can find download both capture files shown in the picture above [here](https://expirebox.com/download/32966f2b6c7edac3d8b21488524c802b.html) (GitHub doesn't allow uploading them or uploading a ZIP file with them). Password for the zip file is password1.

Here is how to decrypt WPA with Wireshark, follow [this link](https://wiki.wireshark.org/HowToDecrypt802.11).

It looks like #110 might be related

**Comment by mfontanini** [comment]
Sorry, I've been busy lately but I'll make sure to look into this tomorrow. I did reproduce this behavior locally, so I'll try to find the issue.

Thanks for the report!

**Comment by mfontanini** [comment]
The files expired... Could you upload them again? I fetched them but only on `/tmp` and now they're gone.

**Comment by cooperarichardson** [comment]
Here is a new link: https://expirebox.com/download/4c38681921029cd91d8485762de9dd99.html

**Comment by cooperarichardson** [comment]
Any update on the issue?

**Comment by mfontanini** [comment]
I haven't had time to look into this but I did download the file. I'll look into it as soon as I have some free time.

**Comment by mfontanini** [comment]
So, I finally had some time to look into this. The code wasn't using the QoS TID when building the AAD buffer. I just pushed a fix for this into branch `develop`. Could you try it?

Sorry for the  delay!

**Comment by cooperarichardson** [comment]
It fixes most of the issue. Some packets (from the pcap files uploaded) are still skipped and in Wireshark, you can find them using the display filter "wlan.seq >= 1891" (None of those displayed with this filter are decrypted).
The only common thing about those is those sequence numbers are out of order.

Let me know if you need the original pcap again.

**Comment by mfontanini** [comment]
I did see those ones but I didn't bother checking them as wireshark doesn't seem to be either to decrypt them either and I assume they're doing the right thing.

**Comment by cooperarichardson** [comment]
Wireshark (2.2.4) decrypted them just fine (2.2.5 should work just fine too). Decrypted, each of them are pretty much very similar to the packet before.

**Comment by mfontanini** [comment]
Oh alright, I'll check using a newer version then. I'll keep you posted.

**Comment by cooperarichardson** [comment]
Awesome. Thanks a lot ;)

**Comment by mfontanini** [comment]
So the issue with those packets is they're encrypted using the Group Temporal Key (GTK) and libtins has no support for this yet. I'll see how hard it'd be to actually implement this, as it would require tracking keys over time and it's not trivial for sure.

**Comment by cooperarichardson** [comment]
Would you like me to open another issue (GTK) so this one can be marked as resolved (since the patch works)?

**Comment by mfontanini** [comment]
Sure, that would be nice! You can link this issue, I already have the files
