### ISSUE TITLE
mDNS support?

### ISSUE THREAD

**Issue by atonkyra** [mfontanini/libtins#191]
Would be cool if tins could support multicast DNS.

**Comment by mfontanini** [comment]
Isn't the mDNS header format the same as DNS?

**Comment by atonkyra** [comment]
Mostly yes, but payload is UTF-8. Not sure if that is the cause but when I tried to inspect mDNS using tins, I encountered several segfaults :)

**Comment by mfontanini** [comment]
Can you provide some pcap to reproduce the issues? I've actually parsed some mDNS and didn't find any issues. But also I don't think hostnames where I tested it had UTF8 characters.

**Comment by atonkyra** [comment]
Okay looks like I am unable to reproduce the issue at the moment but I'll run few more tests, can you confirm that this is the way I am supposed to accomplish my goal (see below)?

```
where udp is Tins::UDP*
Tins::DNS d = static_cast<Tins::RawPDU*>(udp->inner_pdu())->to<Tins::DNS>();
```

**Comment by mfontanini** [comment]
That's okay but it's probably safer if you do:

```c++
Tins::DNS d = udp->rfind_pdu<RawPDU>().to<Tins::DNS>();
```

As your code is both assuming there's an inner pdu and that it's a `RawPDU` (which are probably true but it's better to be safe).

**Comment by atonkyra** [comment]
Alright, thanks for the tip! I also discovered my original failure, this code triggered segfault
```
// presume d is valid Tins::DNS
Tins::DNS d = ...;
for(auto it = d.answers().begin(); it != d.answers().end(); ++it) {
  std::cout << (*it).dname() << std::endl;
}
```

Which is clearly invalid. Below code is correct:
```
// presume d is valid Tins::DNS
Tins::DNS d = ...;
auto answers = d.answers();
for(auto it = answers.begin(); it != answers.end(); ++it) {
  std::cout << (*it).dname() << std::endl;
}
```

So closing as invalid :)
