### ISSUE TITLE
gettng Error	42	error C2059: syntax error : 'constant'	d:\data\libtins-vs2013-x64-release\libtins\include\tins\dns.h on line number 106

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#193]
Hi i am getting following error while integrating with existing code.

Error	42	error C2059: syntax error : 'constant'	d:\data\libtins-vs2013-x64-release\libtins\include\tins\dns.h	106	1	SystemAdapter

**Comment by mfontanini** [comment]
I see you created another issue. Did you fix this issue?

**Comment by bipindas123** [comment]
Yes , i have fixed that.


thanks
bipin
