### ISSUE TITLE
1 Second to write UDP packet

### ISSUE THREAD

**Issue by foreverska** [mfontanini/libtins#195]
I have a process in which I have a sniffer watching for UDP packets of a certain type and a PacketSender (per client) pumping out responses.  Because the filter is pretty loose it can hear itself talk.  I've learned to live with this but it does highlight a problem.  From a logger message directly after PacketSender.Send() to when the applicable sniffer (with immediate mode on) hears it being sent is almost exactly 1 second every time.  Wireshark corroborates this story.  Also the turn around from when I am sent a response to when I respond again is small change beyond 1 second despite no delay on my part.  So my question is, is this a normal send time for 150-500 byte UDP packets using libtins?  

Some implementation details:
PacketSender is created when a client is registered and is kept until the connection closes
The packet is a IP = IP / UDP / CUSTOMCLASS
The idea of the send line is:  pClient->sender.send(IP);
The timing mark is after this line
The sniffer watching this has a filter for UDP on Port X or Y, promisc, snap_len 8000 and immediate mode

I have some L2 packets libtins has great response on (tenths of a millisecond turn around) so it has served well there but this UDP performance is less than desirable.

Machine:
Debian Stable
i5/8gb ram
Libtins-3.4

Thanks

**Comment by mfontanini** [comment]
Hi! I wrote this tiny thing to test this. It basically sends a packet every second and captures it, printing the time difference between:

* The time it was sent vs the time it was captured (using clocks).
* The time it was sent vs the time it was captured according to the kernel (using the packet timestamp).

It always prints times close to 50 microseconds for me, on both timings. Could you run it and see what your output is? Make sure to choose the right interface (it's hardcoded to be wlan0 now).

e.g. my output is:

```
Time difference: 122us (real) 56us (against packet ts)
Time difference: 26us (real) 28us (against packet ts)
Time difference: 21us (real) 53us (against packet ts)
Time difference: 58us (real) 52us (against packet ts)
Time difference: 49us (real) 55us (against packet ts)
Time difference: 25us (real) 54us (against packet ts)
Time difference: 63us (real) 80us (against packet ts)
Time difference: 50us (real) 56us (against packet ts)
```

This is the code:

```c++
#include <tins/tins.h>
#include <iostream>
#include <unordered_map>
#include <mutex>
#include <thread>

using namespace std;
using namespace std::chrono;
using namespace Tins;

class Tester {
public:
    void run() {
        thread th([&] {
            SnifferConfiguration config;
            config.set_immediate_mode(true);
            Sniffer sniffer("wlan0", config);
            sniffer.sniff_loop(bind(&Tester::callback, this, placeholders::_1));
        });
        while (true) {
            send_packet();
            this_thread::sleep_for(seconds(1));
        }
        th.join();
    }
private:
    using time_point = high_resolution_clock::time_point;
    static time_point now() {
        return high_resolution_clock::now();
    }

    void send_packet() {
        string payload(500, 'A');
        payload[0] = counter_;
        IP packet = IP("1.2.3.4") / UDP(8888, 9999) / RawPDU(payload);
        
        lock_guard<mutex> _(timings_mutex_);
        sender_.send(packet);
        timings_[counter_] = now();
        counter_++;
    }
    
    bool callback(const Packet& packet) {
        const auto& udp = packet.pdu()->rfind_pdu<UDP>();
        const auto& raw = packet.pdu()->rfind_pdu<RawPDU>();
        // Make sure it's our packet
        if (udp.sport() != 9999 || udp.dport() != 8888) {
            return true;
        }
        if (raw.payload().size() != 500) {
            return true;
        } 
        uint8_t index = raw.payload()[0];
        lock_guard<mutex> _(timings_mutex_);
        auto iter = timings_.find(index);
        if (iter != timings_.end()) {
            auto real_time_diff = duration_cast<microseconds>(now() - iter->second);
            auto ts_time_diff = duration_cast<microseconds>(iter->second.time_since_epoch() - static_cast<microseconds>(packet.timestamp()));
            cout << "Time difference: " << real_time_diff.count() << "us (real) "
                 << ts_time_diff.count() << "us (against packet ts)" << endl;
            timings_.erase(iter);
        }
        return true;
    }

    PacketSender sender_;
    unordered_map<uint8_t, time_point> timings_;
    uint8_t counter_{0};
    mutex timings_mutex_;
};

int main() {
    Tester tester;
    tester.run();
}
```

**Comment by foreverska** [comment]
I'm incredibly sorry to have bothered you with this.  The test ran perfect, it was a copy paste accident on my part which caused immediate mode to not be set on that sniffer.
