### ISSUE TITLE
How to get complete raw 200 bytes  ip packet from libtins IP object

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#196]
Hi , 

Anybody help me to get complete 200 bytes of ip packet from libtins IP object.
i need to store complete IP packet into 200 byte char array.
Is there any way to get it.

**Comment by mfontanini** [comment]
Did you try using the `PDU::serialize` method? e.g.

```c++
IP packet = ...;
// This is a vector<uint8_t>
PDU::serialization_type buffer = packet.serialize();
```

**Comment by bipindas123** [comment]
Thanks a lot. it is working fine after using your solution.
