### ISSUE TITLE
how to reassemble fragmented  IP packets.

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#198]
Hi , i am getting some fragmented IP packets. 
Is there any way  i can reassemble all IP packets into single IP packet using libtins before sending to destination.

thanks
Bipin

**Comment by mfontanini** [comment]
You can have a look at [this example](https://github.com/mfontanini/libtins/blob/9593cf4cf657c876ba36e1d405d2c538ceb79c6d/examples/defragmenter.cpp) and the [IPv4Reassembler class documentation](http://libtins.github.io/docs/latest/d4/dbb/classTins_1_1IPv4Reassembler.html).
