### ISSUE TITLE
Obtain data link type when reading pcap

### ISSUE THREAD

**Issue by cooperarichardson** [mfontanini/libtins#199]
It would be nice if FileSniffer had a method to get the link type, even if it's just the DLT type number. It can easily be obtained when reading the pcap header which is always going to be there no matter if there is a packet or not in the capture file.

Right now, we have to read a packet and figure out the link type based on what is in the PDU.

**Comment by mfontanini** [comment]
That's already there actually: http://libtins.github.io/docs/latest/d2/d96/classTins_1_1BaseSniffer.html#a6db4824653994120468955df1aa3a8bd. That's the DLT flag.
