### ISSUE TITLE
pcap sniffer buffer size, receiving packets as a chunk of packets on linux

### ISSUE THREAD

**Issue by DontKnowMy** [mfontanini/libtins#202]
Hi,

I am sending packets every 30ms but the receiver doesn´t deliver the right system timestamp because the data gets logged as a chunk of data. What I want is that the sniffer gives me the packet as soon as possible and doesn´t wait for more to fill the buffer or something. Right now only about every second I get the data chunk.

Does anyone know what to do. Thanks!

**Comment by mfontanini** [comment]
That's the behavior you'll see when not using immediate mode (this is the
default after pcap 1.5 IIRC). You can enable immediate mode using
`SnifferConfiguration::set_immediate_mode` before constructing your Sniffer

**Comment by DontKnowMy** [comment]
perfect thanks!
