### ISSUE TITLE
how to extract IPv6 or IP packet from Packet object.

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#204]
Hi 

i have a Packet object. How can i know that , packet object hold IPv4 packet or IPv6 packet so that i can directly extract IP packet using following method.

Packet pdu
IPv6 &ip = pdu.pdu()->rfind_pdu<IPv6>();

**Comment by bipindas123** [comment]
could you look this issue. i am block for this.

**Comment by mfontanini** [comment]
If you look at the documentation/tutorial you can figure this out yourself. Just go through all PDUs in a packet (call `PDU::inner_pdu`) and check the type of each of them (call `PDU::pdu_type`). If any of those is either `PDU::IP` or `PDU::IPv6` then cast it and use it as the right type. There's no generic class to cover both protocols so you'll have to deal with them separately.
