### ISSUE TITLE
Sniffer stops and seems to cause NIC problems

### ISSUE THREAD

**Issue by DontKnowMy** [mfontanini/libtins#205]
Hi,

I am sending packages every 10ms with variable length on my linux system. The sniffer running on another linux machine captures all the packages but after a undefined time/package number the sniffer suddenly stops and seems to crash the NIC. After rebooting I can sniff packages again but the same problem occures. What could be the problem? Thanks!

**Comment by DontKnowMy** [comment]
moreover sometimes the sniffer program stops as if the sniffer returned false but it definitely shouldn´t. Did someone experience problems like that before?

**Comment by mfontanini** [comment]
For sniffing purposed, libtins just uses libpcap under the hood doing nothing strange with it. If you run tcpdump on the receiver side instead of a libtins sniffer, does the same thing happen?

**Comment by DontKnowMy** [comment]
I tried and yes it seems the same error occurred:

[67193.527310] iwlwifi 0000:02:00.0: Microcode SW error detected.  Restarting 0x82000000.
[67193.527938] iwlwifi 0000:02:00.0:                 FH_TSSR_TX_ERROR_REG: 0X00000000
[67193.528115] iwlwifi 0000:02:00.0: Start IWL Error Log Dump:

**Comment by DontKnowMy** [comment]
The error above makes it necessary to restart the NIC.

The other "error" is when the sniffer just stops running without reason. After starting the sniffer again it works, why does the sniffer stop?

**Comment by mfontanini** [comment]
I think the sniffer stops if it encounters a fatal error when reading from libpcap. If it's sniffing in a loop and sniffing fails then the loop should probably stop.

**Comment by mfontanini** [comment]
Closing as the NIC issue is not libtins related.
