### ISSUE TITLE
RadioTap Header missing fields

### ISSUE THREAD

**Issue by sdeck51** [mfontanini/libtins#207]
Hello!

I was going to try making a packet interpreter of my own using libpcap but then I found out about this library. One of the important things I need is to be able to read the radiotap header and extract its information. Using some of the tutorial code along with looking at the documentation I made a little program just to try to get radiotap information.
```

#include <tins/tins.h>
#include <iostream>
#include <stddef.h>

using namespace Tins;

size_t counter(0);

bool count_packets(const PDU &pdu)
{
	counter ++;
	const IP &ip = pdu.rfind_pdu<IP>(); // Find the IP layer
    const TCP &tcp = pdu.rfind_pdu<TCP>(); // Find the TCP layer
    const RadioTap &radio = pdu.rfind_pdu<RadioTap>(); // Find the RadioTap layer
    std::cout << ip.src_addr() << ':' << tcp.sport() << " -> " 
              << ip.dst_addr() << ':' << tcp.dport() << std::endl;
	std::cout << radio.channel_freq() << std::endl;
	return true;
}

int main()
{
	FileSniffer sniffer("tcp3.pcap");
	sniffer.sniff_loop(count_packets);
	std::cout << "There are " << counter << " packets in the pcap file\n";
```

I took the counter tutorial code and added the ip/tcp code from another. After I found that that worked I tried it with the RadioTap. I can get the length of the file, but any other sort of information, like the channel frequency in the above code, yields "terminate called after throwing an instance of 'Tins::field_not_present'
  what():  Field not present
"

which I assume to mean it did not interprete the RadioTap header info. In Wireshark I can confirm that the information is in the packet.

The pcap file I'm using is simply two packets, both tcp sent using 802.11. It can be found[ here ](https://www.dropbox.com/s/41hnuauwie1fzzq/tcp.pcap?dl=0) Any help on what I could be doing wrong would be great as this library seems to be the solution I'm looking for, provided I can get the RadioTap information.

**Comment by mfontanini** [comment]
The first packet has several fields, including the one you're trying to print. The second packet has no fields at all (see attached screenshot). The first packet is being printed successfully and this fails on the second one, which makes sense as the field is not actually there in the latter.

![screenshot](https://cloud.githubusercontent.com/assets/969090/25836034/51ed0e26-3438-11e7-9d0b-e933a7163d0d.png)

**Comment by sdeck51** [comment]
Hey,

That was an extremely quick reply! Thanks for the explanation. I see my issue (and I feel dumb for not realizing that about the second packet). What is the best method for libtins to see if a field exists so I don't terminate?

Thanks!

**Comment by mfontanini** [comment]
You should call [`RadioTap::flags`](http://libtins.github.io/docs/latest/d7/d0e/classTins_1_1RadioTap.html#a607c1f7a5f60318f0e31e67a93b0930e) and make sure the right flag is set. e.g.

```c++
if ((radiotap.flags() & RadioTap::CHANNEL) != 0) {
     // now it's safe to call that
}
```

**Comment by sdeck51** [comment]
Ok so here's what I tried, still an issue with the second packet. Let me know what I did wrong

```
if ((radiotap.flags() & RadioTap::CHANNEL) != 0)
	{
		std::cout << (int)radiotap.channel_freq() << std::endl;
	}
	else 
	{
		std::cout << "No channel information" << std::endl;
	}
```

**Comment by mfontanini** [comment]
Sorry, the method you need to use is `present`:

```c++
if ((radio.present() & RadioTap::CHANNEL) != 0) {
```

**Comment by sdeck51** [comment]
Great, that appears to be working for channel_freq! What do I need for other members like rate() and db_signal()? Is there a list of what I need to check so I don't have to bother you so much? :p Thanks for replying so quickly.

**Comment by mfontanini** [comment]
Scroll up on the link I sent (the RadioTap documentation) and you'll see the definition of `PresentFlags`. That has all the constants you need to check for present fields.

**Comment by sdeck51** [comment]
Thanks. I'm still having some issues though, using that pcap file. When I try to find the data rate using rate() it doesn't come up even though the first packet has a rate of 39MB/s. Ive also tried another pcap file thats much larger and it'll show data rates that are twice the size(24 in wireshark, 48 in libtins).

**Comment by mfontanini** [comment]
On the capture you attached, there's no rate field. There's an "MCS" information and wireshark seems to know how to convert that to a rate, so the code is correct, there's actually no rate in that packet. In this case you need to get the MSC field and then compute that yourself.

Can you provide a capture where there's a 48 instead of 24? Please attach a capture file every time there's an issue with a specific packet, otherwise there's not much I can do.

**Comment by sdeck51** [comment]
https://www.dropbox.com/s/wffajz5rpgaqcvg/cap2.pcap?dl=0

http://i.imgur.com/PKZYYwe.png

```
sdeck51@sdeck51:~/Documents$ ./a.out cap2.pcap 
frequency: 2462
type: 00000000000000000000000011000000
rate: 48
flags: 00000000000000000000000000010000
signal str: -55
frequency: 2462
type: 00000000000000000000000011000000
rate: 48
flags: 00000000000000000000000000010000
signal str: -55
frequency: 2462
type: 00000000000000000000000011000000
rate: 48
flags: 00000000000000000000000000010000
signal str: -56
frequency: 2462
type: 00000000000000000000000011000000
rate: 48
flags: 00000000000000000000000000010000
signal str: -55
There are 4 packets in the pcap file
```

**Comment by mfontanini** [comment]
This should probably be documented in libtins, but if you check the [RadioTap definition](http://www.radiotap.org/fields/Rate.html), you'll see that the unit the rate uses is "500 Kbps". Therefore the value 48 * 500Kbps = 24 Mbps

**Comment by sdeck51** [comment]
Ah my bad. That works out then. Thanks for the help. Do you know anything about calculating preamble/duration/phy type? Wireshark has a 802.11 radio information section that I need those three values from/

http://i.imgur.com/D9E9feN.png

**Comment by mfontanini** [comment]
No problem. And no, I don't know anything about that. I only know some stuff about how the header itself is defined but not much about what everything means.

**Comment by sdeck51** [comment]
Sounds fine. Thanks for all your help. You're awesome. I'll see what I can figure out with the dur/pre/phy information.
