### ISSUE TITLE
Libtins crash when add mac address

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#208]
Hi 

Libtins is crashing after some time with below line.
pkt.dst_addr(m_dst_mac);

i  am getting contentiously ip packet. . i am trying to send this packet to destination using following code. where m_dst_mac is the destination server mac address. i could see , some initial packets are reaching to destination but after some time it is crash at the line where we add mac address. 
EthernetII  pkt = EthernetII() / ip;
	pkt.dst_addr(m_dst_mac);
	sender.send(pkt, iface);

Any suggestion.
How can i send the packet to destination without using mac address.

thanks
Bipin

**Comment by mfontanini** [comment]
What type is `m_dst_mac` and how is it initialized? That can't crash unless you're doing something pretty bad, like providing a null pointer or something like that.

**Comment by bipindas123** [comment]
Type of m_dst_mac is HWAddress<6> ;  i can see some initial packets are reaching to destination. After some time it is crashed.

**Comment by mfontanini** [comment]
Can you post your full code?

**Comment by bipindas123** [comment]
void CSATransportTri::SendRTPToRTPG(string strpayload)
{

	PacketSender sender;
	NetworkInterface iface = NetworkInterface::default_interface();
    HWAddress<6> dst_mac ("b8:a386:9848:9a");
	int msg_len = strpayload.length();
	unsigned char *msg = (unsigned  char *)malloc(msg_len + 1);

	copy(strpayload.begin(), strpayload.end(),msg);
	IPv6 ip = IPv6(msg,strpayload.length());

	std::cout << ip.src_addr() << ':' << ip.dst_addr() <<  std::endl;
	EthernetII  pkt = EthernetII() / ip;
	pkt.dst_addr(dst_mac);
	sender.send(pkt, iface);
	free(msg);
}


This function call happens at each 20 ms second.

**Comment by mfontanini** [comment]
Is this your actual code? Because the MAC address you're showing is malformed, so that's going to throw an exception when trying to parse it. Also, not that it's the cause of the issue, but you shouldn't be creating a PacketSender every 20ms, you should create one and then re-use it. Same for the network interface you're using, those are costly operations (e.g. opening a raw socket, querying the kernel, etc).

Your memory must be getting corrupted somewhere else and it's blowing up there. Setting the destination hardware address is just a `memcpy` so that won't fail.

**Comment by bipindas123** [comment]
No , this is not actual code. Using this code i reproduce the issue and minimize the code.

In my real code , i create interface and sender object only once.i reuse those object .  

The actual mac address is  b8:a3:86:98:48:9a . it was copy paste mistake
when i comment the line where adding the destination mac address, i am not getting any crash.( but packets are not reaching to destination)

**Comment by mfontanini** [comment]
Still, this is very likely some memory corruption issue unrelated to ethernet / the MAC address. You should run this using some tool like valgrind to detect memory corruptions.

**Comment by bipindas123** [comment]
sure , i am planing to do this.

**Comment by mfontanini** [comment]
Did you figure this one out?

**Comment by bipindas123** [comment]
yes. 
i found some ICMPv6 packets were coming but i am trying to get UDP packet from IP packets .
So i put a check of next header and handle accordingly.
