### ISSUE TITLE
Invalid handling of DLT_RAW link type on Sniffer

### ISSUE THREAD

**Issue by Gjergj** [mfontanini/libtins#210]
Trying to sniff on a tun0 interface created by openvpn throws unknown_link_type.
In BaseSniffer::next_packet   the call to pcap_datalink returns 12.

**Comment by Gjergj** [comment]
In BaseSniffer::next_packet  if I add:

```
else if (iface_type == 12) {
        handler = sniff_loop_eth_handler;
    }
```
or
```
else if (iface_type == 12) {
        handler = &sniff_loop_handler<RawPDU>;
    }
```

it fails to call the callbacks of Tins::TCPIP::StreamFollower;

**Comment by Gjergj** [comment]
In bpf.h I see this section about iface_type == 12

> /*
 * These are types that are different on some platforms, and that
 * have been defined by <net/bpf.h> for ages.  We use #ifdefs to
 * detect the BSDs that define them differently from the traditional
 * libpcap <net/bpf.h>
 *
 * XXX - DLT_ATM_RFC1483 is 13 in BSD/OS, and DLT_RAW is 14 in BSD/OS,
 * but I don't know what the right #define is for BSD/OS.
 */
#define DLT_ATM_RFC1483	11	/* LLC-encapsulated ATM */

#ifdef __OpenBSD__
#define DLT_RAW		14	/* raw IP */
#else
#define DLT_RAW		12	/* raw IP */
#endif

**Comment by mfontanini** [comment]
If you're going to extract RawPDUs, then you can just use `Sniffer::set_extract_raw_pdus` without changing the code at all. Then you'll get a `RawPDU` and you need to know the actual link type to be able to parse the packet and forward it to the stream follower. What type of packets do you get out of that interface?

**Comment by Gjergj** [comment]
I am trying to sniff tcp/ip packets and get the http with StreamFollower.
I tried to set  set_extract_raw_pdus to true but StreamFollower handlers still do not get called.
By: 
> and you need to know the actual link type to be able to parse the packet and forward it to the stream follower
you mean that I have to extend PDU and add a new protocol ?

**Comment by mfontanini** [comment]
Yes, it's not going to work because the Sniffer will extract a RawPDU and the StreamFollower needs an actual parsed packet (e.g. IP + TCP + data) to be able to do anything useful with it.

By what's the actual link type, I mean if you capture from that interface using e.g. wireshark, what type of packets do you get out of it? Is it Ethernet + something else?

**Comment by Gjergj** [comment]
[tun0.pcap.zip](https://github.com/mfontanini/libtins/files/1019437/tun0.pcap.zip)
Attched is a pcap

**Comment by mfontanini** [comment]
Okay, so it's an IP/IPv6 layer. I'll add something to handle DLT_RAW but anyway, you have to do the parsing yourself. So e.g. if you're using the stream follower, you'd have to do something like:

```c++
sniffer.sniff_loop([&](const PDU& packet) {
       IP ip = packet.rfind_pdu<RawPDU>().to<IP>();
       follower.process_packet(ip);
       return true;
});
```

**Comment by Gjergj** [comment]
So I have to create a new class by extending PDU as explained in
http://libtins.github.io/tutorial/new_protocols/  , register it and us it like this
`IP ip = packet.rfind_pdu<RawPDU>().to<IP>(); ` 
where IP is the new class?

**Comment by mfontanini** [comment]
No, the tiny snippet I posted above is all you need. Whenever you call sniff_loop, that will give you a RawPDU. You just need to parse it as an IP packet and then give it to your stream follower.

**Comment by Gjergj** [comment]
It works, thank you.
If anyone has the same issue as me here's a small piece of code so that it works with DLT_EN10MB and DLT_RAW:
```
Sniffer sniffer(m_ethInterface, config);
        if(sniffer.link_type() == DLT_RAW){
            sniffer.set_extract_raw_pdus(true);
        }
```

than in the Sniffer::sniff_loop callback
```
                if(sniffer.link_type() == DLT_RAW){
                    Tins::IP ip = packet.rfind_pdu<Tins::RawPDU>().to<IP>();
                    follower.process_packet(ip);
                }else{
                    follower.process_packet(packet);
                }
```

**Comment by mfontanini** [comment]
Note that if you actually get an IPv6 packet out of the interface, that won't work. I'll push a proper fix in a couple of days.
