### ISSUE TITLE
problem after installing to my ubuntu

### ISSUE THREAD

**Issue by jirapast** [mfontanini/libtins#215]
my example code

#include <tins/tins.h>
using namespace Tins;
int main() {
EthernetII eth;
}
$ g++  -std=c++11  -lpthread  -ltins  tins.cpp

after I try to test. I get this  error
------------------------------------------------------
/tmp/ccvchIAu.o: In function `main':
tins.cpp:(.text+0x68): undefined reference to `Tins::EthernetII::EthernetII(Tins::HWAddress<6ul, unsigned char> const&, Tins::HWAddress<6ul, unsigned char> const&)'
/tmp/ccvchIAu.o: In function `Tins::EthernetII::~EthernetII()':
tins.cpp:(.text._ZN4Tins10EthernetIID2Ev[_ZN4Tins10EthernetIID5Ev]+0xd): undefined reference to `vtable for Tins::EthernetII'
tins.cpp:(.text._ZN4Tins10EthernetIID2Ev[_ZN4Tins10EthernetIID5Ev]+0x20): undefined reference to `Tins::PDU::~PDU()'
collect2: error: ld returned 1 exit status
----------------------------------------------------------------
I a hobby programmer if I miss some important concept tell me pls.

**Comment by jirapast** [comment]
my example code 
----------------------------
#include <tins/tins.h>
using namespace Tins;
int main() {
    EthernetII eth;
}

**Comment by mfontanini** [comment]
Good morning thing I wrote the FAQ section on the website last week:
http://libtins.github.io/faq/#linking

**Comment by jirapast** [comment]
I solved it!
I used wrong order command when linking.
I used this command "$ g++ -std=c++11 -lpthread -ltins test.cpp"
But the correct order command must be 
"$ g++ test.cpp -std=c++11 -lpthread -ltins " or "$ g++ -std=c++11 test.cpp -lpthread -ltins "
Because the linker is search for LIB from LEFT to RIGHT. 
The file that contain the code must on the left of all LIB that must to include.
Thank you very much.
