### ISSUE TITLE
NPCAP as an alternative to WinPCAP

### ISSUE THREAD

**Issue by solvingJ** [mfontanini/libtins#220]
We're very interested in this project however the state of WinPCAP is untenable as a dependency for us. I searched past issues and the project sources in this repo and found no references to NPCAP.  Has there been any discussion about it, and/or the WinPCAP issue?

If not, I would strongly recommend investing some time in researching NPCAP, and would like to know any feedback that comes of it.

https://github.com/nmap/npcap#features

**Comment by mfontanini** [comment]
I just skimmed through NPCAP's readme and it seems like it's compatible
with PCAP/WinPCAP API-wise. If that's the case, then there should be no
issue in building libtins using it instead of WinPCAP. As long as
whatever's being used is pcap-compatible, it shouldn't matter what you use

**Comment by solvingJ** [comment]
That's great to hear, thanks for looking into it. If we do run into issues, would it be something you would be willing to support to any extent?

**Comment by mfontanini** [comment]
If you have any libtins specific issues, yes. Given that NPCAP's interface is the same as libpcap/WinPCAP, I don't think you should have issues with it.

**Comment by solvingJ** [comment]
Again, great to hear on both counts!  Thanks!

**Comment by solvingJ** [comment]
Mathias, 
If you don't mind, please email me as I'd like to ask you a few questions privately about the feasibility of using Libtins in our application.  
Regards,
Jerry

**Comment by solvingJ** [comment]
Sry, i just found that it was hidden and now i've unhidden it.
