### ISSUE TITLE
crash when getting UDP packet from IP packets

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#222]
Hi ,

i have a complete IP packet on buffer. i am able to convert this into IP packet using following code
IPv6 ip6PayLoad = IPv6(buf, length);
i can print source ip address as well as destination ip addres which shows correct ips.

i am trying to get UPD packet from ip6PayLoad using below line.
UDP udp = ip6PayLoad.inner_pdu()->rfind_pdu<UDP>();

but above line gets crash. 
Can you share me any reason or any other way i can extract this UDP packet.

**Comment by mfontanini** [comment]
Can you post a pcap that contains that file? Also you don't need to ask for
the inner PDU, just doing `ipv6->rfind_pdu<UDP>()` should do

**Comment by bipindas123** [comment]
i got the issue. Actually packet was ICMP packet . so i was getting crash when trying to get UDP from it.
