### ISSUE TITLE
Why is appveyor.yml in cmake folder?

### ISSUE THREAD

**Issue by solvingJ** [mfontanini/libtins#224]
I was trying to run our own tests on Appveyor and found the yml file for it is inside Cmake directory.  Why is this?

**Comment by mfontanini** [comment]
Appveyor let's you put the file anywhere and I wanted to avoid bloating the root directory with random files. No other reason

**Comment by solvingJ** [comment]
Ok, I see.  I really dislike the bloating of the root directory as well,  I wish travis allowed that as well.
