### ISSUE TITLE
87c0e3a breaks FileSniffer

### ISSUE THREAD

**Issue by fabianfreyer** [mfontanini/libtins#230]
https://github.com/mfontanini/libtins/commit/87c0e3a337e17c5bfcfee44419623c49a4995505 introduces a bug that causes sniffing using FileSniffer to cause a segmentation fault due to an uninitialized `pcap_sniffing_method_` in `src/sniffer.cpp:215`.

While debugging this, I also noticed that there are no tests for FileSniffer.

**Comment by mfontanini** [comment]
Ouch, that was embarrassing, sorry. There should be some tests for this, I'll try to add some soon enough.

**Comment by fabianfreyer** [comment]
Awesome, thanks for the quick response!
