### ISSUE TITLE
Possible crash on non-BROADCAST POINTTOPOINT interface

### ISSUE THREAD

**Issue by roadriverrail** [mfontanini/libtins#232]
I'm working on porting libtins to my project, and I noticed this code which looks like it could be a crash:

In network_interfaces.cpp: you define TINS_BROADCAST_ADDR as follows:

```
        #if defined(BSD) || defined(__FreeBSD_kernel__)   
            #define TINS_BROADCAST_ADDR(addr) (addr->ifa_dstaddr)
```
[...]
```
       #else
            #define TINS_BROADCAST_ADDR(addr) (addr->ifa_broadaddr)
```
Then a couple of lines of code later, you extract a broadcast address from the `ifaddrs*` as follows:

```
                   if ((addr->ifa_flags & (IFF_BROADCAST | IFF_POINTOPOINT))) {
                        info->bcast_addr = IPv4Address(                                                                                        
                            ((struct sockaddr_in *)TINS_BROADCAST_ADDR(addr))->sin_addr.s_addr);       
```

It looks like this code phrase is trying to handle the BSD case as well as the the non-BSD case all in one go.  Unfortunately, the manpage for `getifaddrs( )` states:

```
 The ifa_broadaddr field, which should only be referenced for non-P2P
     interfaces, references the broadcast address associated with ifa_addr, if
     one exists, otherwise it is NULL
```

So, on a non-BSD environment, this code phrase looks like it's going to reference the `addr->ifa_broadaddr` on a P2P non-broadcast interface, which will then create a segfault.  One of the interfaces I work with is a tunnel interface, which is P2P with no broadcast addr, so...there you go.

If BSD systems use `IFF_POINTTOPOINT` to indicate their broadcast address, then I'd suggest defining a `TINS_BROADCAST_FLAG` to go with the `TINS_BROADCAST_ADDR`.

That said, it may be the case that `getifaddrs( )` on your currently supported platforms populates both `ifa_broadaddr` and `ifa_dstaddr`.  My current implementation of that function does not.

**Comment by mfontanini** [comment]
But doesn't the check for the flag `IFF_BROADCAST` prevent this? If you have a non P2P interface that doesn't have a broadcast address, then `(addr->ifa_flags & (IFF_BROADCAST | IFF_POINTOPOINT)` will be 0, so it won't try to get the broadcast address. Does this actually crash for you? Which OS/distro are you using?

**Comment by roadriverrail** [comment]
Yeah, see, the boolean OR means that as long as `IFF_BROADCAST` OR `IFF_POINTOPOINT` is set you'll enter the block.  My reading of `getifaddrs( )` and related manpages is that `IFF_BROADCAST` and `IFF_POINTOPOINT` cannot be set at the same time.  That makes sense, since `ifa_broadaddr` and `ifa_dstaddr` are actually a union called `ifa_ifu`.  So, basically if you're on a NON-BSD platform looking at a P2P interface, you're actually mis-interpreting the `ifa_dstaddr` as an `ifa_broadaddr`.

**Comment by roadriverrail** [comment]
Unfortunately, I found this while working on something for my job, so I'm not free to give the platform information.  I can say it's Linux-based and that the `getifaddrs( )` implementation is not the one that ships with most major Linuces.  I'd be curious to see if/how this reproduces on actual Linux.  I'm also happy to give the correction in a PR, since it's just fixing libtins to follow the description of the manpages.  I'm not 100% sure how broadcast addresses work on BSD, though, so someone would have to check that out.

**Comment by mfontanini** [comment]
I see. That's fine though, the fix should be straightforward. Couldn't it just be replacing the condition with:

```c++
if ((addr->ifa_flags & (IFF_BROADCAST | IFF_POINTOPOINT)) != 0 &&
    TINS_BROADCAST_ADDR(addr) != 0)
```

That way it would only try to use it if it's actually there.

**Comment by roadriverrail** [comment]
You're right.  That's even tighter.

**Comment by roadriverrail** [comment]
Actually, since `ifa_broadaddr` and `ifa_dstaddr` are two fields of a union, I don't think you can rely on `TINS_BROADCAST_ADDR(addr) != 0` there.  It looks like that basically would just interpret a pointer-to-dstaddr as a pointer-to-broadaddr, and you'd get undefined bytes for your broadcast address.
