### ISSUE TITLE
Set Mode for a Dot11Beacon

### ISSUE THREAD

**Issue by paultag** [mfontanini/libtins#237]
It's not clear in the docs or source how to set the Mode to master/infrastructure when sending a Beacon, and most devices will read that as a client beacon. Is there a toggle in the source already?

**Comment by mfontanini** [comment]
That's platform independent and out of the scope of the library. I've personally always used `airmon-ng` on Linux.

**Comment by paultag** [comment]
Sorry, I'm a bit confused. I'm pretty green with 802.11 :)

Let's say I'm scanning for networks using tins. How can I tell if a network is Ad-Hoc or not?

**Comment by mfontanini** [comment]
There's currently no way to query the state of an interface (e.g. to see if it's on master mode). I'm not sure how easy it is to implement that check in a multi platform way, but I imagine it could be useful.

**Comment by paultag** [comment]
@mfontanini I still feel like we're not talking about the same thing.

I did some reading of the spec, and I think I'm talking about the least significant capabilities information, the ESS capabilities that denotes if the packet is coming from an STA or AP.

I think this means I want to set a flag on the Capabilities information on the IEEE 802.11 management frame. Knowing this new set of keywords, I might be able to set the right flag

**Comment by mfontanini** [comment]
Okay, that's way clearer, I was talking about a completely unrelated thing. Do you mean [`capability_information::ess`](http://libtins.github.io/docs/latest/d2/d63/classTins_1_1Dot11ManagementFrame_1_1capability__information.html#acb661bf02b520a668599694b7d00e9f9)?

**Comment by paultag** [comment]
I do, score! Thanks!

I wonder if there should be a pointer to learn about what ESS is, or maybe a pointer to it in the docs about a Beacon, since a lot of clients will drop beacons from a STA these days. I'm going to close this since it's doable :)

Thanks again!

**Comment by paultag** [comment]
(Setting that worked as expected, thank you!)
