### ISSUE TITLE
Options for "Communicating with Localhost" with Libtins

### ISSUE THREAD

**Issue by solvingj** [mfontanini/libtins#239]
We're currently looking for ways to "send packets" to localhost, and receive the responses in libtins.  This seems like it would be trivial, or at the very least possible, but there are so many options that after a day of trial and error, we're still not seeing the responses. In most of our tests, we can see our requests in wireshark, but we don't see any responses coming back.  It seems likely we're using the wrong combination of interfaces and options. 

Our current question is, have you done it, and if not how would you approach it?  Specific questions we're struggling with include: 

-Which IP to use for source address, physical IP or 127.0.0.1?  Same question for destination IP.
-What type of outer PDU should we send?  Layer 2 or 3?  Is Loopback PDU an option?
-For the "Sender", should we use physical or the Loopback adapter?
-For the "Sniffer", same question?
-Would response PDU's be Loopback PDU's (maybe it depends on where we sniff?)?  
-Any special mode flags we should use on the sniffer?

We're hoping you've perhaps done this before, or someone else has, and knows a working combination.  We're on windows, but we can test any suggested configurations which are known to work on Linux and work out the diff. 

Thanks again in advance!

**Comment by mfontanini** [comment]
On Linux I can just do this:

```c++
PacketSender sender;
auto pkt = IP("127.0.0.1", "127.0.0.1") / TCP(1234, 4444);
pkt.rfind_pdu<TCP>().flags(TCP::SYN);
sender.send(pkt, "lo"); 
```

And get a response out of it, but Windows is a different thing. Using layer 2 PDUs doesn't seem to generate a response, maybe something's filtering the packets. 

Why is it that you want to send packets to localhost?

**Comment by solvingj** [comment]
Great to know that about linux, and hopefully mac is similar.  It did seem like windows nuances we were dealing with, but after looking at how simple your code is, maybe we're overcomplicating by binding the sender to a particular adapter and such.  Let me see what happens if I copy your code.

**Comment by solvingj** [comment]
It's currently throwing a runtime exception on `sender.send(pkt, ni)` but it's not printing the details of the error.  I've tried interfaces: `Ethernet`, `Npcap Loopback Adapter`, and `Loopback Pseudo-Interface1`.  All throw exception on send.

**Comment by mfontanini** [comment]
Sorry, actually the interface name is pointless in there (I was trying to add a layer 2 PDU before and in that case it's needed for it to use "lo"). The thing is when you send using a layer 3 as the lowest layer, then the kernel will be involved (the kernel appends the ethernet layer, calculates checksums, etc) as this uses sockets to send the packet. When you use a layer 2 one, then the packet is basically copied as is into the network interface.

I imagine Windows isn't letting you send the packet using layer 3 as the lowest layer (they're known to apply some restrictions on which packets you can send using raw sockets). Now, once you start using a layer 2 PDU then you're using winpcap/npcap to send it so at that point you rely on them doing the right thing. Even if the packet is sent, you'd need the kernel to actually process the packet which seems like it doesn't happen on Linux (again, only when using layer 2 PDUs, using layer 3 works just fine).

**Comment by solvingj** [comment]
This is great insight. 

I'll look into the restrictions on raw sockets, maybe we can still use this case if we stay inside the lines. 

While sending layer 2, are Winpcap/npcap delivering data directly to the network interface driver at that point, or are they still going through windows filters?   Is it possible/likely that the NIC's will have unique behaviors about letting us send from specific source MAC or IP?  

Can you tell me which windows API's we're interacting with?  I looked for about two hours yesterday and didn't feel like I even found the right documentation. 

Thanks again for helping us at this level.

**Comment by mfontanini** [comment]
Nice, sounds like that should make it work.

**Comment by solvingj** [comment]
Update: 
It still looks like it should work, but the send_pcap flag seems to only affect Layer 3 packets and not Layer 2 packets.  In order to use this feature, we think we have to wrap our Layer 3 packet in a Loopback() packet (Layer2?) and send that, which means we'll need to also modify Libtins so that send_pcap is invoked for those packets as well.

**Comment by mfontanini** [comment]
I think you mean that it only affects layer 2 packets rather than layer 3, which is correct. What you say makes sense. Try Ethernet and Loopback and see if it works. If you manage to make it work by changing some code (e.g. making Loopback be sendable on Windows) please make a PR and I'll be happy to merge it!

**Comment by solvingj** [comment]
I'm sure you're correct, but I meant it the way I wrote it, so I think I misunderstand the problem a bit. I think of Loopback as Layer2 (since it encapsulates a layer 3).  It's probably neither technically, but indeed I think making loopback sendable will be the path forward.  I think klemens already has something working.

**Comment by mfontanini** [comment]
Yeah, Loopback should be layer 2. That's good to hear!

**Comment by mfontanini** [comment]
Closing as it seems like this is working and it's not libtins specific.
