### ISSUE TITLE
Libtins is not installing in win 32 bit

### ISSUE THREAD

**Issue by shalinsirwani** [mfontanini/libtins#240]
please give me exact description how to install libtins on windows 32 bit in code blocks.

**Comment by mfontanini** [comment]
What have you tried? Have you downloaded a precompiled version as specified in the [tutorial](http://libtins.github.io/download/#download-binary)? Are you linking it as specified [in there](http://libtins.github.io/download/#using-windows) as well?

**Comment by shalinsirwani** [comment]
I am trying to attach Libtins in "code blocks" .
Is it possible ?(without visual studio)

**Comment by mfontanini** [comment]
Code blocks is just an IDE, it probably uses gcc under the hood, so yes. You just need to figure out where to configure the include path and how to link the library.

**Comment by shalinsirwani** [comment]
Sir from where I download library for libtins ?

**Comment by shalinsirwani** [comment]
Sorry sir that message was incomplete .
My question was
From where I download .Lib file of libtins for windows?

**Comment by mfontanini** [comment]
That's specified in the link I sent on my first comment... Here: https://ci.appveyor.com/project/mfontanini/libtins/branch/master. Click one, go to artifacts and download. This is only for Visual Studio builds though, if you're using gcc you'll have to build the library yourself (again, the tutorial explains how to do that).

**Comment by shalinsirwani** [comment]
Sir will you suggest me what is the best tutorial for Linux kernel
understand.

From scratch.

**Comment by mfontanini** [comment]
I don't know any good tutorials on that, sorry. Closing this issue.
