### ISSUE TITLE
Is there a way to craft PDUs without copying the source buffers?

### ISSUE THREAD

**Issue by traceon** [mfontanini/libtins#241]
I am looking into using this library, the packet crafting side of it—it has a lot of really convenient solutions indeed—but one thing is alarming: all PDU constructors seem to copy the buffer, vector, or take ownership of the vector. This seems to be an overkill, because usually it requires lot of efforts to achieve zero-copy access to the received data and so on, and then have packet buffer copied to just (in my case) modify the packet header and retransmit it (total 2 copy, and heap allocations). Is there a way to improve performance in this case?

**Comment by mfontanini** [comment]
Unfortunately, there is no zero copy API. The library was designed that way and if it were to be changed, that would involve a complete re-write of it, there's no easy way around it.
