### ISSUE TITLE
What is the purpose of "INCLUDE(ExternalProject)" in CMakeLists.txt

### ISSUE THREAD

**Issue by solvingj** [mfontanini/libtins#245]
I cannot find the `ExternalProject` variable referenced anywhere else.  Can you just explain how it's intended to be used?

**Comment by mfontanini** [comment]
That's a module to import external projects. It's used to import googlemock: https://github.com/mfontanini/libtins/blob/master/CMakeLists.txt#L287

**Comment by solvingj** [comment]
I see, didn't know about the _Add convention.  Thanks!
