### ISSUE TITLE
get crash when use 2nd interface..

### ISSUE THREAD

**Issue by bipindas123** [mfontanini/libtins#249]
Hi 

i am trying to sniff packets using 2nd interface. i get crash when i create sniffer object.

Sniffer sniffer(interface.name(), config);  // Here interface is the object of 2nd interface.

it is fine with 1st interface but getting issue with 2nd interface.

thanks
Bipin

**Comment by mfontanini** [comment]
Please provide more information when creating issues. What operating system are you using? What's the name of the interface you're trying to use? When you say "crash" I imagine it throws an exception. Can you catch it and print its message?

**Comment by bipindas123** [comment]
i am using windows.  

i have default ethernet interface. Created another interface  whose name is "Ethernet 3" using "USB ethernet adapter" cable. 


printed all the interface and its ip address.
Interface name: {109A01AC-4BE4-4FE8-92C1-C6484B310AEF}169.254.178.9 (Local Area Connection* 2)
Interface name: {3ADA1A5C-3943-47C9-9127-1F53BA3C0522}172.27.1.246 (Ethernet 3)
Interface name: {5DE73DEE-E979-4779-A9D0-85E5B7B3F259}192.168.56.1 (VirtualBox Host-Only Network)
Interface name: {6EB44F92-CC59-11E5-BBA4-806E6F6E6963}127.0.0.1 (Loopback Pseudo-Interface 1)
Interface name: {7651926D-E524-4C4E-B672-2703DC05179E}172.27.1.245 (Ethernet) 

i will print the exception and let you know.

**Comment by bipindas123** [comment]
i catched  the exception and found  this is pcap_error.

catch (pcap_error p )
	{
		std::cout << "pcap_error";
	}

**Comment by mfontanini** [comment]
Can you print the exception's message? The type is not very useful by itself. e.g.

```c++
std::cout << p.what() << std::endl;
```

**Comment by bipindas123** [comment]
i fixed this issue. This was setup issue.

when i opened wireshark and try to get packet on 2nd interface, i could not see the 2nd interface. 
So i reinstall wireshark and restart machine. i could see the 2nd interface on wireshark.  

After this, i did not see exception issue .
