### ISSUE TITLE
Include Collision with LibPCAP - llc.h

### ISSUE THREAD

**Issue by solvingj** [mfontanini/libtins#250]
It seems that both Libtins and LibPCAP have a header file named `llc.h` in the root of the include path. In our testing, `llc.h` from LibPCAP is found first, and thus Libtins fails to compile. 

I could not find any prior reports of the issue, so I wondered what we could be doing wrong or different. 

I remembered that we seem to be the first people to use MSVC with NPCap (which includes LibPCAP's directory via git submodule).  My guess is that there's a "race condition" on searching the include folders for `llc.h` based on various factors including the compiler used, folder names, etc.  Perhaps if you extract LibPCAP and Libtins with their default folder names, and build with GCC or Clang, Libtins comes up first (reliably, even if somewhat by luck).  Unfortunately, with MSVC, LibPCAP comes up first. 

I do see that the include statements in libtins use the appropriate quotes form in it's include statements as in: `#include "llc.h"`.  In theory, MSVC should search the "Local Folders" first, followed by other include paths.  But here, we're going through CMake to MSVC, so maybe CMake presents LibPCAP's include directory and Libtins include directory as equals when passing to MSVC. I'm not an expert here I must admit. 

We did find it curious that the Libtins include folder structure does follow the modern standard `include/tins` , but that the include statements use `tins` as the root instead of the standard `include`. It made us wonder why the `tins` folder exists, and why isn't everything just in the root of `include`.  Perhaps you were planning to migrate to the qualified paths in your `#include` statements?

**Comment by mfontanini** [comment]
Interesting. Are you using the libpcap and libtins parent directory as the include path? e.g. if your directory structure looks like

```
include/pcap/llc.h
include/tins/llc.h
# rest of the files 
```
Are you using `include` as the include directory? I don't see how a file inside `tins` that includes "llc.h" would find `include/libpcap/llc.h` as that's on a completely unrelated directory. Are you by any chance using `include/pcap` as an include directory as well?

**Comment by solvingj** [comment]
I'm not using any of it yet, this occurs just when building Libtins using NPCap/LibPCap as a dependency.  It's my understanding that we need to include the headers of LibPCAP during compilation and link to it to build Libtins.  With MSVC, both the include paths are passed to the compiler using  `/I` for include,  so /I<libtins_repo_root/include> /I<libpcap_repo_root>. 

I got it to compile by replacing the include statement in the following three files: 
loopback.cpp
dot3.cpp
llc.cpp

Before: "llc.h"
After:   "../include/tins/llc.h"

**Comment by mfontanini** [comment]
Ah, I see. Those are private libpcap headers, meaning they're not actually meant to be installed. You should probably install libpcap somewhere and then use the installation directory as an include directory.

But besides that, I think it's not a bad idea to change the libtins include directives to use paths relative to the include directory. Not using `../` but instead using `tins/<file>.h` and using `include` as the include directory while building the library.

**Comment by solvingj** [comment]
Wow, well i think that would be good as it would be more like the vast majority of modern libraries i've seen.  `#include <tins/llc.h>` right?

Good tip on the LibPCap, i'll give that a try tomorrow. Thanks again for your amazing support.

**Comment by mfontanini** [comment]
Yeah, I'm actually changing the include paths as I write this. I'll push a fix in a few minutes. No problem!

**Comment by mfontanini** [comment]
I just pushed a fix. Can you check and see if this works for you? Hopefully this will build on appveyor as well

**Comment by solvingj** [comment]
sure thing

**Comment by solvingj** [comment]
Works, amazing job !

**Comment by mfontanini** [comment]
Btw, I'll develop into master later today.
