### ISSUE TITLE
Cannot compile when using flag to disable dot11

### ISSUE THREAD

**Issue by lenigoor** [mfontanini/libtins#258]
When building the library and therefore running
`~/libtins/build$ cmake ../ -DLIBTINS_ENABLE_DOT11=0`
results into a huge list of errors. The first (partial) error is:

`In file included from /home/leon/libtins/src/../include/tins/utils/radiotap_parser.h:36:0,
                 from /home/leon/libtins/src/utils/radiotap_parser.cpp:31:
/home/leon/libtins/src/../include/tins/pdu_option.h:55:65: error: ‘PDU’ has not been declared
         uint8_t convert(const uint8_t* ptr, uint32_t data_size, PDU::endian_type endian,`

I'm using Ubuntu 16.04 with g++ version 5.4.0. Would someone be willing to look into this?

**Comment by mfontanini** [comment]
Sorry about this one, I added some features and never checked building with that flag on. Fixed!

**Comment by lenigoor** [comment]
Awesome, thanks for the quick response and fix!
