### ISSUE TITLE
Large variation  in packet send latency?

### ISSUE THREAD

**Issue by Tin-Voyager** [mfontanini/libtins#262]
I am writing a tool using libtins to test packet receive/transmit times within my development network.

I have noticed that there seems to be a large variation in the latency between calling PacketSender::send and the packet actually being transmitted. Approximately every 10-15 packets, one will take about 5 times longer to transmit?

I was wondering if it could be due to the way libtins handles sockets? Is a socket kept open between transmits or is it closed after each one and then re-opened? I should say that all the packets are being sent at layer 2.

I'm also working from libtins 3.4

**Comment by ajcollins** [comment]
Are you able to provide a minimal test case, and information on your operating system? Does the following trigger the behaviour?

```c++
#include <tins/tins.h>
#include <iostream>

using std::cout;
using std::endl;

using namespace Tins;

// Note: on macOS this may run out of buffer space

int main(int argc, char* argv[]) {
    if(argc != 2) {
        cout << "Usage: " <<* argv << " <interface>" << endl;
        return 1;
    }

    // All packets will be sent through the provided interface
    PacketSender sender;
    sender.default_interface(argv[1]);

    auto pkt = EthernetII("ab:cd:ef:fe:dc:ba", "fe:dc:ba:ab:cd:ef") /
               IP("192.168.1.1", "192.168.1.2") /
               UDP(1096, 1096) /
               RawPDU("Payload");

    for (int i=0; i<5000; i++)
        sender.send(pkt);
}
```

**Comment by Tin-Voyager** [comment]
Thanks for getting back to me so quickly. 

Once I’m back in the office I’ll get on with your suggestions. 

For info I’m working on Ubuntu 16.04.2 LTS x64.

**Comment by Tin-Voyager** [comment]
Thanks for the code snippet

I ran it (with changes IP/MAC addresses) and timed the packets on the sending and receiving machines. The results were similar to the issue I am experiencing. 

On the receiving device, of the 5000 packets received approximately 4700 were <= 1ms. The times for the other 300 packets varied widely with 6 packets > 20ms and 1 > 65ms.

On the sending device, of the 5000 packets sent approximately 4800 were <= 1ms. The times for the other 200 packets went as high as 19ms. 

I should say that I am testing on a wireless network.

**Comment by ajcollins** [comment]
Thanks for confirming that the little bit of test code provides the same sort of behaviour. I saw something similar locally to what you saw with that code, but didn’t want to bias your investigation.

My (untested) hypothesis is that this may linked to the network stack, CPU scheduling, and possibly processor affinity, rather than anything libtins specific.

For example, using the code below, you’ll get the send(..) duration printed to std::out.

A few thoughts to investigate:
- Reducing the process’ niceness (e.g. using nice -20) might help.
- Using taskset command to set the process affinity and avoid being changed between cores. 
- Whether changing your NIC’s options (TSO, GRO etc) has any affect.

You could potentially accommodate the interval by including the high resolution timer value in your packet, to allow you to remove the scheduling jitter at the receiving end if required.

```c++
#include <tins/tins.h>
#include <iostream>
#include <thread>

using std::cout;
using std::endl;

using namespace Tins;
using namespace std::chrono_literals;

// Note: on macOS this may run out of buffer space
int main(int argc, char* argv[]) {
    if(argc != 2) {
        cout << "Usage: " <<* argv << " <interface>" << endl;
        return 1;
    }

    // All packets will be sent through the provided interface
    PacketSender sender;
    sender.default_interface(argv[1]);

    auto pkt = EthernetII("ab:cd:ef:fe:dc:ba", "fe:dc:ba:ab:cd:ef") /
               IP("192.168.1.1", "192.168.1.2") /
               UDP(1096, 1096) /
               RawPDU("Payload");

    for (int i=0; i<5000; ++i) {
        auto start = std::chrono::high_resolution_clock::now();
        sender.send(pkt);
        auto end = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double, std::milli> elapsed = end-start;
        std::cout << elapsed.count() << "\n"; // ms
    }
}
```

**Comment by Tin-Voyager** [comment]
Sorry for the delayed response, needed to take my time with looking into the suggestions above. 

Processor niceness - I played around with this from +19 to -20, made very little difference.
Taskset- working on this currently. 
NIC options - tried disabling gso and gro to no joy. 

I think as you say I’m coming up against areas which libtins has no control over. 

If anyone has any other days I’m more than happy to try them out.

**Comment by mfontanini** [comment]
Have you tried running your application with `strace`? The calls to `send` may just be blocking because you're sending too many packets so the output buffer gets full.

**Comment by ajcollins** [comment]
That’s a good point; I’d forgotten `send` blocking. 

In which case you should also be able to increase the buffer size if that’s the problem.

```
sysctl -w net.core.wmem_max=1048576
sysctl -w net.core.rmem_max=1048576
```

This can then either be persisted, or set in your code.

**Comment by Tin-Voyager** [comment]
Thanks gents, I’ll try those settings once I’m back in the office.

**Comment by steven-chien** [comment]
https://github.com/mfontanini/libtins/issues/180
Have you tried setting immediate mode?

**Comment by Tin-Voyager** [comment]
Thanks @steven-chien. 

I’m still working on this issue, just been a little sidetracked with a new project given to me by my manager.

**Comment by Tin-Voyager** [comment]
I’m going to close this issue. I wasn’t able to resolve the issue but feels like I’m coming up against kernel/IP/Networking barriers. Thank you for everyone’s help, been massively helpful. Keep up the good work.
