### ISSUE TITLE
Non intuitive adding of IPv6 extension headers

### ISSUE THREAD

**Issue by laudrup** [mfontanini/libtins#270]
Hi there,

As I wrote in a previous issue (#268) I'm using your excellent library for testing a packet parser.

I have upgraded to version 4.0 and as you promised things are indeed working as intended now. Thanks a lot for that.

One minor issue I had though, was that if I simply add an extension header like:

```c++
Tins::IPv6 ipv6_header;
ipv6_header.add_header(Tins::IPv6::ExtensionHeader::HOP_BY_HOP);
```
It will craft an invalid package, since libtins will automatically and correctly add the type and header field but not pad the extra 6 bytes required for this to be a valid IPv6 extension header. It was not a big deal, since I could easily add the padding myself, but it took me a while to realize that.

Unless I've misunderstood something, I think it might be worth considering handling that in a bit more intuitive way. One way I could think of was to make an IPv6 extension header it's own type (possibly inheriting from the PDUOption class) that ensures that and possibly implementing some of the well known IPv6 extension headers by inheriting from that class. Not sure how that would fit into your current design though.

It could also be a simple documentation issue.

If you like my idea (or have a better idea) I will be more than happy to have a go at improving that and sending you a pull request if that's any help.

Thanks a lot.

**Comment by mfontanini** [comment]
Makes sense, IPv6 should probably handle this padding the option. I'll push a fix in a bit. Thanks!

**Comment by mfontanini** [comment]
I just pushed that commit which should fix this ^. IPv6 will now pad all options with zeroes at the end so they end up being a multiple of 8 bytes long. I'm not sure if using zeroes works for all types of options though.

**Comment by laudrup** [comment]
Nice, thanks a lot. I'll check it out.

How do you feel about extending the handling of IPv6 extension headers, so libtins knows about at least some of the well known types?

As I said, I'd be happy to try to implement that if you think it might make sense?

Thanks.

**Comment by mfontanini** [comment]
Sorry, I completely forgot about this one. That actually sounds good. The same logic is implemented on IP/TCP/DHCP/DNS so it only makes sense to do the same here.

**Comment by laudrup** [comment]
Cool.

So my idea was something like this (this hop-by-hop header being used as an example):

```
class HopByHopExtensionHeader : public PDUOption<uint8_t, IPv6>
{
public:
  HopByHopExtensionHeader::HopByHopExtensionHeader()
    : PDUOption(IPv6::ExtensionHeader::HOP_BY_HOP)
  {
  }
  // Implement hop-by-hop header specific stuff here...
};
```
It doesn't seem like you are doing this anywhere else (inheriting from the PDUOption class).

Would this be the right way to go or am I missing something?

Thanks.

**Comment by mfontanini** [comment]
`PDUOption` is not really meant to be inherited. It's just really meant to be an intermediate representation between packet < - > actual representation of the options.

The way I've been defining things would be to have `IPv6` define `option` to be `PDUOption<uint8_t, IPv6>`. Then implement the extension headers in some way (possibly using some separate inheritance) and have a way to convert from/to that `PDUOption`. e.g. see how this is done in [Dot11](https://github.com/mfontanini/libtins/blob/master/include/tins/dot11/dot11_mgmt.h#L638).

**Comment by laudrup** [comment]
Thanks a lot.

That definitely makes sense as well.

I'll look at the Dot11 implementation for inspiration and see when I can come up with a pull request.

**Comment by laudrup** [comment]
I've created a pull request here #287.

I hope you'll have time to look at it at some point.

Of course feel free to comment on whatever you might have issues with or at least tell me why you would never want to merge it :-)

For now, I think this issue should better just be closed. If there's anything to be discussed, I hope we can do that in the pull request.
