### ISSUE TITLE
Memory leak in PDU move operator

### ISSUE THREAD

**Issue by Larsjep** [mfontanini/libtins#272]
Hi,

First I would like to thank you for this great library.

In my use case, I discovered a memory leak.
I tracked it down to the PDU move assignment operator:

```
        PDU& operator=(PDU &&rhs) TINS_NOEXCEPT {
            std::swap(inner_pdu_, rhs.inner_pdu_);
            rhs.inner_pdu_ = 0;
            if (inner_pdu_) {
                inner_pdu_->parent_pdu(this);
            }
            return* this;
        }
```

As I see it there is missing a 
```delete inner_pdu_;```
as the first line.

Best regards
  Lars

**Comment by mfontanini** [comment]
Ugh this is bad, I'm sorry about it. Just pushed a fix, I'll merge into master in a bit.

**Comment by Larsjep** [comment]
Thanks, do you plan to make a patch release?

**Comment by mfontanini** [comment]
Yeah there should probably be a path release for this. I'll push that sometime this week when I find some time for it.
