### ISSUE TITLE
the installer does not respect CMAKE_INSTALL_LIBDIR variable

### ISSUE THREAD

**Issue by blshkv** [mfontanini/libtins#273]
I noticed a hardcoded path ```CMAKE_INSTALL_LIBDIR``` in the CMakeLists.txt and this may be fine.
However, I must install libraries into ```lib64``` in my setup. I have changed this variable accordingly however both static and shared libraries are getting installed into /usr/lib.

Could you fix it please?

Thank you.

**Comment by mfontanini** [comment]
Can't you use CMAKE_INSTALL_PREFIX? I thought that was the CMake way to specify an install prefix.

**Comment by blshkv** [comment]
I can't because it is prefix for the lib path, see the following code:
```
SET(pkgconfig_libdir      ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR})
```

**Comment by blshkv** [comment]
Also:
```
# The library output directory
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
```

**Comment by mfontanini** [comment]
Alright, I'll look into this. I have a bit of a backlog of issues on a couple of projects, libtins being one of them, so I'll try to catch up on all of that this weekend.

**Comment by blshkv** [comment]
looks good, thank you!
