### ISSUE TITLE
Segfault in RadioTap constructor

### ISSUE THREAD

**Issue by banburybill** [mfontanini/libtins#295]
I've been doing some fuzzing with my libtins application, and have hit a segfault in the RadioTap constructor. Dereferencing parser.current_option_ptr() fails. The offending pointer isn't null. I'm trying to work out how this happens, but know nothing about RadioTap, so it's taking a while.

    total_sz = input.size();
    RadioTapParser parser(options_payload_);
    if (parser.skip_to_field(FLAGS)) {
        const uint8_t flags_value = *parser.current_option_ptr();
        if ((flags_value & FCS) != 0) {
            if (TINS_UNLIKELY(total_sz < sizeof(uint32_t))) {
                throw malformed_packet();
            }
            total_sz -= sizeof(uint32_t);
            if (TINS_UNLIKELY((flags_value & FAILED_FCS) != 0)) {
                throw malformed_packet();
            }
        }
    }

**Comment by mfontanini** [comment]
Damn, that sucks. I did a bunch of fuzzing on that class and fixed a couple of issues but something must have slipped. Do you happen to have some payload that causes this issue?

**Comment by banburybill** [comment]
This pcap does the damage. Apologies in advance if it works for you and it's my app that's at fault :-)
I've not had time today to look further into this.

[radio-tap-crash.pcap.gz](https://github.com/mfontanini/libtins/files/2010004/radio-tap-crash.pcap.gz)

**Comment by mfontanini** [comment]
Sweet, I'll definitely fix this today. Thanks for the report!

**Comment by mfontanini** [comment]
Such a stupid issue, created https://github.com/mfontanini/libtins/pull/296 for it. I'll merge once the PR build succeeds.

**Comment by banburybill** [comment]
I realised cycling home yesterday that it must be a missing off-the-end check, but you beat me to the fix by miles :-) Thanks.
