### ISSUE TITLE
the Frame Length does not get written correctly

### ISSUE THREAD

**Issue by pepper-jk** [mfontanini/libtins#300]
When looking at packets in .pcap files there are two lengths defined in a header:
* the **Frame Length**, which provides the length of the packet, which was actually send in real world
* the **Capture Length**, which provides the length of the packet, which is stored in the pcap

![packet_header](https://user-images.githubusercontent.com/19859589/41036766-6bc7c734-6991-11e8-87cb-29754281164a.png)

This allows the capture to be a lot smaller then the real traffic that was monitored, while still providing the information about how much data was transferred. This **information gets lost** when using Libtins to read a .pcap and write it out again.

This is due to the **[Packet](https://github.com/mfontanini/libtins/blob/a6817528bc237970bca4d0351195151552f01db6/include/tins/packet.h#L315) data structure**, which only stores the [PDUs content](https://github.com/mfontanini/libtins/blob/a6817528bc237970bca4d0351195151552f01db6/include/tins/pdu.h) and its timestamp.

As far as I looked into it the sniffer does not read the information either since there is no data structure to store it in.

As you can see the **Frame Length** and **Capture Length** are set to the **size of the packet**, when writing:
https://github.com/mfontanini/libtins/blob/a6817528bc237970bca4d0351195151552f01db6/src/packet_writer.cpp#L72-L80

I'm not sure if you consider this a bug, or if you do not want handle this type of "metadata".

This was noticed when using the [ID2T-toolkit](https://git.tk.informatik.tu-darmstadt.de/SPIN/ID2T-toolkit) to inject attack packets into a .pcap file. ID2T uses libtins for reading and writing pcaps, while not modifying the original packets, but only adding new packets on top.

Before:

    $ capinfos resources/201804041400_200000PDUs.pcap 
    File name:           resources/201804041400_200000PDUs.pcap
    File type:           Wireshark/... - pcapng
    File encapsulation:  Ethernet
    File timestamp precision:  microseconds (6)
    Packet size limit:   file hdr: (not set)
    Packet size limit:   inferred: 34 bytes - 96 bytes (range)
    Number of packets:   200 k
    File size:           17 MB
    Data size:           125 MB
    Capture duration:    2.482684 seconds
    First packet time:   2018-04-04 07:00:00.448274
    Last packet time:    2018-04-04 07:00:02.930958
    Data byte rate:      50 MBps
    Data bit rate:       404 Mbps
    Average packet size: 627.71 bytes
    Average packet rate: 80 kpackets/s
    SHA256:              62924a980159433b2592b4f9dac85885ecfd87426469ddd89184eb3d5a5c9ad9
    RIPEMD160:           0f7a0a79bff641f369b7b75a791f56a36390e505
    SHA1:                f5ec986efedfada2d12946e73f303b712cd86e91
    Strict time order:   True
    Capture application: Editcap 2.6.1
    Number of interfaces in file: 1
    Interface #0 info:
                         Encapsulation = Ethernet (1 - ether)
                         Capture length = 96
                         Time precision = microseconds (6)
                         Time ticks per second = 1000000
                         Number of stat entries = 0
                         Number of packets = 200000

After:

    $ ./id2t -i resources/201804041400_200000PDUs.pcap -T -a Portscan
    $ capinfos resources/ID2T_results/201804041400_200000PDUs_20180606-133149.pcap
    File name:           resources/ID2T_results/201804041400_200000PDUs_20180606-133149.pcap
    File type:           Wireshark/tcpdump/... - pcap
    File encapsulation:  Ethernet
    File timestamp precision:  microseconds (6)
    Packet size limit:   file hdr: 65535 bytes
    Number of packets:   188 k
    File size:           14 MB
    Data size:           11 MB
    Capture duration:    2.482684 seconds
    First packet time:   2018-04-04 07:00:00.448274
    Last packet time:    2018-04-04 07:00:02.930958
    Data byte rate:      4,708 kBps
    Data bit rate:       37 Mbps
    Average packet size: 61.87 bytes
    Average packet rate: 76 kpackets/s
    SHA256:              53021108ebde42256610dbb62f6f9c4548f39351c2f429ccea4d1a01279eb2c6
    RIPEMD160:           49b9712bd8b4e3c2a9ebea1f79c9f0210f7d0977
    SHA1:                84c914da7eeb12a8330028a61ab772353b3e7da1
    Strict time order:   True
    Number of interfaces in file: 1
    Interface #0 info:
                         Encapsulation = Ethernet (1 - ether)
                         Capture length = 65535
                         Time precision = microseconds (6)
                         Time ticks per second = 1000000
                         Number of stat entries = 0
                         Number of packets = 188933

Please note that the 12k packets that are missing are hardly responsible for the dramatic loss of **data size**.

[This](https://git.tk.informatik.tu-darmstadt.de/SPIN/ID2T-toolkit/issues/130) is the corresponding issue for ID2T.

p.s. The [resource .pcap file](http://www.fukuda-lab.org/mawilab/v1.1/2018/04/04/20180404.html) was edited with:

    $ editcap -r 201804041400.pcap 201804041400_200000PDUs.pcap 0-200000

**Comment by mfontanini** [comment]
Your fix doesn't work because [IP::write_serialization](https://github.com/mfontanini/libtins/blob/master/src/ip.cpp#L450) will overwrite the total length of the packet so that if its sent over the network, the field has the proper value.

In order to check if this is the case, you can edit the [fix](https://github.com/pepper-jk/libtins/commit/d3d56f8267164a1fd3b4a48c59d9463f38d8cf15#diff-1c8e01fecf4470b72033021ac3a34702L36) you provided so that the `len` field is initialized before `pdu.serialize()` is called. 

For a proper solution to this, there could be some virtual method that computes the size the packet is advertising (maybe `advertised_size`) which defaults to `header_size() + trailer_size()` but can be overriden by subclasses that support this sort of partial initialization.

**Comment by pepper-jk** [comment]
Thanks for the fast reply. Changing the order really did the trick.

I'll now try to implement the proper solution you suggested.

**Comment by pepper-jk** [comment]
Was fixed with pull request #324.
