### ISSUE TITLE
compile issue on win 10 using vs2015

### ISSUE THREAD

**Issue by c0mradee** [mfontanini/libtins#328]
I've installed vs2015 and downloaded the precompilled win32 vs2015 libtins version and tried compiling http_requests.cpp, running as admin and I've included wpcak lib file and tins.lib file and all other required files getting an error.
![compile-error](https://user-images.githubusercontent.com/35645684/51477207-5d572880-1d90-11e9-91ae-40c057b553be.jpg)

**Comment by mfontanini** [comment]
The `Sniffer::sniff_loop` callback doesn't support `Packet` in older versions of VS because of some compiler error. This should work in VS2017.
