### ISSUE TITLE
How to get access to the interface Name/device in the sniff loop callback handler ??

### ISSUE THREAD

**Issue by chirayu-patel** [mfontanini/libtins#349]
Is there any way to get access to the interface Name/device name in the sniff loop callback handler ??

**Comment by chirayu-patel** [comment]
Can anyone update on this plz ??

**Comment by mfontanini** [comment]
Can't you just bind it in the callback? The interface is something you provide so you should be able to keep track of it.

**Comment by chirayu-patel** [comment]
Thanks !! That worked .. This is what I used : 

string interface(interfaceName);
namespace ph = std::placeholders;
sniffer.sniff_loop(std::bind(dns_callback_handler,ph::_1,interface));
