### ISSUE TITLE
Compiling on Windows Ultimate x64, linking to Qt Creator.

### ISSUE THREAD

**Issue by niemal** [mfontanini/libtins#35]
Hello there,

First of all I'd like to state that this is a really interesting library and that it's pretty unique (couldn't find anything else doing the same in C++). I have been trying for a couple hours to link the library with Qt Creator and I haven't managed to succeed... (Same for Visual Studio 2013)

Winpcap linking works just fine.

- Linking winpcap (works).
INCLUDEPATH += C:\WpdPack\Include
LIBS += -L C:\WpdPack\Lib\x64 -lwpcap - lpacket

- Linking libtins (doesn't work).
LIBS += -L C:\libtins -ltins

I also compiled the library multiple times incase that was the problem. (Compiled with VS, compiled with cmake, compiled with C++11 flag and without, etc)

I would appreciate any help as I am really keen on this specific library, thank you.

**Comment by mfontanini** [comment]
Closing since this is more likely to be a QtCreator configuration issue than a libtins one.
