### ISSUE TITLE
Sniffer timeout

### ISSUE THREAD

**Issue by NeptuniumIO** [mfontanini/libtins#41]
Sniffer is working without any issues however, the timeout configuration does not end the sniffer. 

	using namespace Tins;
	bool callback(const PDU &pdu) {
	    const RawPDU &data = pdu.rfind_pdu<RawPDU>();
	    const RawPDU::payload_type& payload = data.payload();
	    return true;
	}

	int main() {
	    SnifferConfiguration config;
	    config.set_timeout(5);
	    Sniffer("lo", config).sniff_loop(callback, 1);
	    return 0;
	}

**Comment by roee88** [comment]
I tried implementing it as you described but got some weird behavior (Ubuntu 14.10). It seems like select  always waits the specified timeout even if there are packets to read (e.g. set timeout to 5 seconds it will wait 5 seconds and  then return 1, set timeout to 10 seconds it will wait 10 seconds and then return 1).
Here is the implementation (on subclass of Sniffer):

Packet SnifferWithTimeout::next_packet(long long timeout_ms)
{
#ifndef _WIN32
	// set timeout
	timeval tv;
	tv.tv_sec = timeout_ms / 1000;
	tv.tv_usec = (timeout_ms % 1000) * 1000;

	// Set fd set
	pcap_fd = get_fd();
	fd_set rdfds;
	FD_ZERO(&rdfds);
	FD_SET(pcap_fd, &rdfds);

	// Select
	int retval = select(pcap_fd + 1, &rdfds, NULL, NULL, &tv);
	if (retval != -1 && retval)
	{
		return next_packet();
	}
#else
	auto event_h = pcap_getevent(get_pcap_handle());
	auto result = WaitForSingleObject(event_h, (DWORD)timeout_ms);
	if (result == WAIT_OBJECT_0) {
		return next_packet();
	}
#endif
	return Packet();
}

**Comment by mfontanini** [comment]
This is stated on the [pcap_get_selectable_fd manpage](http://www.tcpdump.org/manpages/pcap_get_selectable_fd.3pcap.html), and it looks like there's a workaround there

**Comment by mfontanini** [comment]
On Windows, if you use events, you'll find the same problem, and I think there's no workaround in that platform. I needed to sniff on multiple interfaces, and had to end up spawning one thread for each of them since using events would sometimes buffer packets for up to 30 seconds.

**Comment by roee88** [comment]
The timeout of libpcap works for me on ubuntu (haven't tested on windows yet, I really hope it works there the same, let me know if you know otherwise). It doesn't work with libtins's sniff_loop because next() uses pcap_loop and not pcap_dispatch.

Tested with a simple subclass of Sniffer (next_packet is called from a loop that monitors remaining time, had to copy sniff_loop_eth_handler and a few related stuff from sniffer.cpp)

	Packet SnifferWithTimeout::next_packet(long long timeout_ms)
	{
		set_timeout(timeout_ms);

		sniff_data data;
		data.packet_processed = false;
		if (pcap_dispatch(get_pcap_handle(), 1, sniff_loop_eth_handler, (u_char*)&data) < 0)
			return Packet();

		if (data.packet_processed)
			return Packet(data.pdu, data.tv);

		return Packet();
	}
