### ISSUE TITLE
unresolved external symbols

### ISSUE THREAD

**Issue by GetALife** [mfontanini/libtins#438]
Hey!

I tried today to use libtins (I included into visual studio the include directory from libtins) but I get some errors:
![E2vOfhY](https://user-images.githubusercontent.com/74838478/114284477-e2ee4e00-9a58-11eb-9cac-dba4f5fcbb62.png)

I defined NOMINMAX.
Anyone knows what's the problem?

**Comment by laudrup** [comment]
Libtins is not a header only library. You need to link with it as well, so you cannot just use the headers and expect things to work.

There is some documentation [here](http://libtins.github.io/download/#using-windows).

But you should basically look into how to use an external library with a C++ project.

Unfortunately, this is not as trivial as one could wish, but this is hardly related to libtins.

You need to provide some more details than just a screenshot with linker errors if you want some help.
