### ISSUE TITLE
DNS decompression loops

### ISSUE THREAD

**Issue by gaya-cohen** [mfontanini/libtins#443]
Parsing malformed DNS packets places the library in a while-true state.
Attached is a capture file.

[loop_each_other_responses.cap.gz](https://github.com/mfontanini/libtins/files/6515629/loop_each_other_responses.cap.gz)
![image](https://user-images.githubusercontent.com/84508985/118974767-dde7bd00-b97b-11eb-9ffb-72f015191efb.png)

Notice the function DNS::compose_name in dns.cpp only contains a check for the offset not being too low or high, but not a check for whether the offset loops. 

![image](https://user-images.githubusercontent.com/84508985/119263136-77b2a280-bbe6-11eb-8b9e-58650d55bcfa.png)
#444

**Comment by mfontanini** [comment]
Closing as #444 fixed it. Thanks for raising the issue and PR!
