### ISSUE TITLE
Tagging a new release / fixup release with GCC 13 patch

### ISSUE THREAD

**Issue by osmith42** [mfontanini/libtins#513]
Hello,

building open5gs against libtins fails on Debian Testing and Unstable because of https://github.com/mfontanini/libtins/pull/496.

Would you mind tagging a new release from master, or a fixup release that adds just this patch?

Thanks!

**Comment by mfontanini** [comment]
It was about time to create a new release, [here's](https://github.com/mfontanini/libtins/releases/tag/v4.5) the latest tag. Cheers!
