### ISSUE TITLE
Radiotap parsing fails on Arduino Yun (OpenWrt)

### ISSUE THREAD

**Issue by haralduna** [mfontanini/libtins#55]
I am using libtins successfully for live packet capture under OpenWrt. However, parsing of the radiotap header fails, only giving garbage. I have collected a pcap file taken with tcpdump from the Yun. This file shows valid header information in Wireshark, but the header is not correctly read by libtins (on my Ubuntu machine). This leads me to believe that the radiotap header from the Yun (Atheros AR9331) is not read correctly by libtins.

**Comment by haralduna** [comment]
I can provide the pcap dump file on request.

**Comment by haralduna** [comment]
Code failing on Yun:
bool BeaconSniffer::callback(PDU &pdu) {
        // Get the Dot11 layer
        const RadioTap *rtap = pdu.find_pdu<RadioTap>();        
        std::cout
                << std::hex << std::uppercase
//              << "|pl:" << (uint32_t)rtap->channel_plus()
                << "|tp:" << (uint16_t)rtap->channel_type()
                << std::dec
                << "|fq:" << (uint16_t)rtap->channel_freq()
                << "|rt:" << (uint16_t)rtap->rate()
                << "|s1:" << 256-(uint8_t)rtap->dbm_signal();
//              << "|s2:" << (uint8_t)rtap->db_signal()
//              << "|ns:" << (uint8_t)rtap->dbm_noise()
//              << "|sq:" << (uint16_t)rtap->signal_quality();

**Comment by mfontanini** [comment]
Could you please attach the pcap file?

Thanks!

**Comment by haralduna** [comment]
Den 03. mars 2015 16:37, skrev Matias Fontanini:
> Could you please attach the pcap file?
>
> Thanks!
> On Mar 3, 2015 5:07 AM, "haralduna" <notifications@github.com> wrote:
>
> > I can provide the pcap dump file on request.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mfontanini/libtins/issues/55#issuecomment-76941829>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mfontanini/libtins/issues/55#issuecomment-76968584>.
>
It was already added, check my updated comment

**Comment by haralduna** [comment]
I did some more experiments on the target, with this code:

bool Capture::onePacket(PDU &pdu) {
    const RadioTap *rtap = pdu.find_pdu<RadioTap>();
    if (rtap->present() & RadioTap::PresentFlags::FHSS)
        std::cout << std::hex << std::uppercase << "|tp:" << (uint16_t) rtap->channel_type() << std::dec;
    if (rtap->present() & RadioTap::PresentFlags::CHANNEL_PLUS)
        std::cout << "|pl:" << (uint32_t) rtap->channel_plus() << std::dec;
    if (rtap->present() & RadioTap::PresentFlags::CHANNEL)
        std::cout << "|fq:" << (uint16_t) rtap->channel_freq();
    if (rtap->present() & RadioTap::PresentFlags::RATE)
        std::cout << "|rt:" << (uint16_t) rtap->rate();
    if (rtap->present() & RadioTap::PresentFlags::DBM_SIGNAL)
        std::cout << "|s1:" << 256 - (uint8_t) rtap->dbm_signal();
    if (rtap->present() & RadioTap::PresentFlags::DB_SIGNAL)
        std::cout << "|s2:" << (uint8_t) rtap->db_signal();
    if (rtap->present() & RadioTap::PresentFlags::DBM_NOISE)
        std::cout << "|ns:" << (uint8_t) rtap->dbm_noise();
    if (rtap->present() & RadioTap::PresentFlags::TSTF)
        std::cout << "|ts:" << (uint64_t) rtap->tsft();
    std::cout << std::endl;
    return true;
}

.. and this was the result:

|fq:15009|rt:156|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15009|rt:163|s1:256|ts:2080
|fq:15009|rt:178|s1:256|ts:2080
|fq:15009|rt:179|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15009|rt:215|s1:256|ts:2080
|fq:15009|rt:215|s1:256|ts:2080
|fq:15009|rt:220|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15009|rt:224|s1:256|ts:2080
|fq:15009|rt:225|s1:256|ts:2080
|fq:15009|rt:226|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15009|s1:256|ts:2080
|fq:15010|s1:256|ts:2080
|fq:15010|rt:7|s1:256|ts:2080

**Comment by haralduna** [comment]
I am using the latest version of libtins on both Ubuntu and target:
commit 88c122ffcb9195dd7f7f708334cbf3f25625e372
Merge: fb97b2b c05f93a
Author: Matias Fontanini <matias.fontanini@gmail.com>
Date:   Tue Feb 10 07:49:41 2015 -0800

**Comment by mfontanini** [comment]
Great. I'll have a look at this in a while. So I guess the platform you are
using this on is big endian?

**Comment by haralduna** [comment]
Yes it is big endian (ar9331):
![skjermbilde fra 2015-03-03 17 10 24](https://cloud.githubusercontent.com/assets/11294027/6466510/59bd2bfc-c1c8-11e4-815e-d6e3c904d72a.png)

**Comment by mfontanini** [comment]
That looks really bad. The TSTF field is the first one, and the value is completely wrong. There are tests that cover that part of the code, so that is very strange.

I'll get a big endian environment tonight and see if I can reproduce the error. I'll let you know when I have any news on this. 

Thanks for the bug report!

**Comment by haralduna** [comment]
Den 03. mars 2015 22:11, skrev Matias Fontanini:
>
> That looks really bad. The TSTF field is the first one, and the value 
> is completely wrong. There are tests that cover that part of the code, 
> so that is very strange.
>
> I'll get a big endian environment tonight and see if I can reproduce 
> the error. I'll let you know when I have any news on this.
>
> Thanks for the bug report!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mfontanini/libtins/issues/55#issuecomment-77035345>.
>
Thank you for looking into this. I really need this fixed.
Please tell me if there is something I can do to.
Maybe some debug printouts would be helpful.

**Comment by mfontanini** [comment]
Yeah, I hope I can reproduce this error. Otherwise, I might ask you to give me a hand.

**Comment by haralduna** [comment]
Den 03. mars 2015 22:51, skrev Matias Fontanini:
>
> Yeah, I hope I can reproduce this error. Otherwise, I might ask you to 
> give me a hand.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mfontanini/libtins/issues/55#issuecomment-77044133>.
>
I added a printout:

diff --git a/src/radiotap.cpp b/src/radiotap.cpp
index 6f7dd82..5a43f98 100644
--- a/src/radiotap.cpp
+++ b/src/radiotap.cpp
@@ -76,6 +76,11 @@ RadioTap::RadioTap(const uint8_t *buffer, uint32_t 
total_sz)
      const uint8_t *buffer_start = buffer;
      std::memcpy(&_radio, buffer, sizeof(_radio));
      uint32_t radiotap_hdr_size = length();
+
+    for (unsigned char i = 0; i < radiotap_hdr_size; i++) {
+        printf("%02x|", *(buffer + i));
+    }
+
      check_size(total_sz, radiotap_hdr_size);
      // We start on the first flags field, skipping version, pad and 
length.
      const flags_type* current_flags = (const flags_type*)(buffer + 
sizeof(uint32_t));


00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|5d|04|e8|6c|eb|01|00|00|10|18|6c|09|c0|00|bb|00|00|00|bb|00| 
# correct
00|00|27|00|2b|40|08|a0|20|08|00|00|00|00|00|00|d1|04|e8|6c|eb|01|00|00|10|00|6c|09|80|04|bb|00|00|00|27|00|04|bb|00|
00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|83|09|e8|6c|eb|01|00|00|10|02|6c|09|c0|00|b5|00|00|00|b5|00| 
# misinterpret
|fq:27880|tp:1EB|rt:9|s1:256|ts:2080
00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|88|0a|e8|6c|eb|01|00|00|10|30|6c|09|c0|00|bc|00|00|00|bc|00|
|fq:27880|tp:1EB|rt:10|s1:256|ts:2080
00|00|0e|00|00|80|0a|00|00|00|01|07|04|05|

Please note:
- 6c09 is the frequency (090c = 2412MHz) / green
- c000 -> 00c0 is channel type / brown
- timestamp is blue
- rate is yellow
- flags is red (CFP, preamble, WEP, etc..)
- It seems the two first frames are discarded (another bug?)

/So it is simply an 8 byte misalignment!/

**Comment by haralduna** [comment]
After adding 8 bytes to extra flags it works (32 bit flags + 32 bit 
padding I guess):

00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|83|43|e0|25|ec|01|00|00|10|02|6c|09|c0|00|ac|00|00|00|ac|00|
|fq:2412|tp:C0|rt:2|s1:84|ts:2113759363971
00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|ca|55|e0|25|ec|01|00|00|10|02|6c|09|c0|00|a9|00|00|00|a9|00|
|fq:2412|tp:C0|rt:2|s1:87|ts:2113759368650
00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|7b|57|e0|25|ec|01|00|00|10|02|6c|09|c0|00|ad|00|00|00|ad|00|
00|00|24|00|2f|40|00|a0|20|08|00|00|00|00|00|00|02|59|e0|25|ec|01|00|00|10|30|6c|09|c0|00|ba|00|00|00|ba|00|
|fq:2412|tp:C0|rt:48|s1:70|ts:2113759369474
00|00|0e|00|00|80|0a|00|00|00|00|07|04|04|

- Still packets are discarded it seems (in red above)

**Comment by mfontanini** [comment]
I think I know what the issue is. All fields in radiotap have to be aligned to their size. So a 8 byte field has to be aligned to 8 bytes. The TSFT field is not being aligned (missalignment only happens if the ext field is 1, since the flags field is twice as large). So all fields for which ext == 1 and TSFT == 1 will fail. This is also failing on little endian architectures. 

I'll fix this later, and will let you know so you can try it on your device.

**Comment by haralduna** [comment]
Den 04. mars 2015 19:25, skrev Matias Fontanini:
>
> I think I know what the issue is. All fields in radiotap have to be 
> aligned to their size. So a 8 byte field has to be aligned to 8 bytes. 
> The TSFT field is not being aligned (missalignment only happens if the 
> ext field is 1, since the flags field is twice as large). So all 
> fields for which ext == 1 and TSFT == 1 will fail. This is also 
> failing on little endian architectures.
>
> I'll fix this later, and will let you know so you can try it on your 
> device.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mfontanini/libtins/issues/55#issuecomment-77215243>.
>
I already submitted a fix (pull-request), and the latest version now 
works for me.

I have added an alignment to 8 byte for the start of the radiotap data. 
That is clearly correct when the TSFT field is present. However, from 
the log I got from the Yun, I can see that this alignment is also done 
(in the case of the ext=1) when there is no TSFT. There is no clear 
indication of this in any radiotap documentation I can find.

(When EXT==0 in the first flaggroup, there will always be an 8 byte 
alignment, so I guess, in order to avoid trouble for older 
implementation, the radiotap data always starts on 8 byte alignment.)

/Harald

**Comment by mfontanini** [comment]
That's strange. It should only align to 8 bytes if there is an 8 byte field. 

I think your fix won't always work. For example, in the pcap you uploaded, the 9th packet has the MCS information field (which is currently not implemented), which seems to be 3 bytes long, and it's aligned to 3 bytes. So if you align to 8, I think you would be completely missing the field and probably parsing the frame incorrectly. This is just by looking at the pcap, so I might be wrong.

**Comment by mfontanini** [comment]
Good news! The biggest problem was that there are some optional fields present which were not supported by libtins (in fact, wireshark doesn't interpret them either). So that's why it looked like there was padding were there actually wasn't.

I added two of the packets as part of tests and they're working on Linux. I still have to add the new fields to the header struct when compiling in big endian though. The code is on the branch ```radiotap_fixes```. I'll see if I can get this working tonight.
