### ISSUE TITLE
not able to compile project depending on include order libtins/boost::asio

### ISSUE THREAD

**Issue by swoertz** [mfontanini/libtins#58]
I am using libtins in a project together with boost::asio (ssl wrapper) amoung some other libraries. If I include tins/tins.h after boost/asio/ssl.hpp I am not able to compile the code. If I include tins first it compiles without any errors.

I am attaching a minimal example with an empty main-block and just the two include lines which reproduces the problem.

My guess is that CERT in the QueryType in libtins dns header collides with the CERT data structure in openssl. Would an enum class or wrapping it in a struct help?

> error msg
> https://gist.github.com/anonymous/f9642cf29775a4137c0d 

```
 $ g++ ok.cc -ltins -lboost_system -lssl -lcrypto -std=c++11
```
>https://gist.github.com/anonymous/f9b26e298dcf9f2fa47a

```
$ g++ fails.cc -ltins -lboost_system -lssl -lcrypto -std=c++11
```
>https://gist.github.com/anonymous/37ee0798607d39eeff90

UPDATE:
kernel version: 3.12.37-2
libtins version: 3.1-1
boost version: boost 1.57.0-3
g++ (GCC) 4.9.2 20150204 (prerelease)

**Comment by mfontanini** [comment]
How can anyone create a macro called ```CERT```? I just don't understand it. 

I'll have to change the name of the enum member to ```CERTIFICATE``` I guess. Thanks for the bug report!

**Comment by swoertz** [comment]
Wouldn't it be better to use c++11's ```enum class``` or wrap it in a ```struct```. It's more work I guess, but it would be correctly namespaced afterwards and it's maybe worth not having to think about it any longer...

see https://stackoverflow.com/questions/11439846/suggestion-to-resolve-an-enum-ambiguity-name-clash

**Comment by mfontanini** [comment]
The problem would persist. The conflicting ```CERT``` is a preprocessor macro, so even if you use ```enum class```, it will still break. 

Example snippet:

```c++
#include <boost/asio/ssl.hpp>

enum class foo {
    BAR,
    CERT
};

int main() {
  return 0;
}
```

**Comment by swoertz** [comment]
You're right.
