### ISSUE TITLE
Example of packet injection

### ISSUE THREAD

**Issue by xybu** [mfontanini/libtins#61]
Hello,

First of all, thanks for this good library! It can make my life much easier.

My question is, is it possible that you modify the payload of a packet before it gets sent in sniffer mode? If I want to do packet injection, can I leverage this library? If so, might you give an example?

Thanks a lot!

**Comment by mfontanini** [comment]
You can sniff a packet, modify it, and re-send it using libtins. The only issue is dropping the original one so the receiver doesn't get two packets. This could be done via iptables rules, I'm sure there has to be some article describing how to do it.
