### ISSUE TITLE
Compilation fails on VS2013

### ISSUE THREAD

**Issue by blazeable** [mfontanini/libtins#64]
I'm trying to compile the latest sources using VS2013 targeting x64, but I'm getting compilation errors in include/tins/internals.h. VS2013 doesn't like this template:
`template <class T, class P, class=void>`
`struct accepts_type : std::false_type { };`

`template <class T, class P>`
`struct accepts_type<T, P, `
`    typename std::enable_if<`
`        std::is_same< decltype(  std::declval<T>()(std::declval<P>())  ), bool>::value`
`    >::type `
`> : std::true_type { };`

Which would be a bug (or lack of support) in VS2013, as it compiles fine elsewhere.

However, I'm getting this even when configuring with LIBTINS_ENABLE_CXX11=0. It seems the TINS_IS_CXX11 definition in cxxstd.h does not check the HAVE_CXX11 macro from config.h.

**Comment by mfontanini** [comment]
That shouldn't happen if you set that option to 0. Remember that CMake
caches options, so if you set it to 1 and then to 0, it won't work. Have
you tried that on a clean compilstion?

As for the error. I'll see if there's any workarounds.

Thanks for the info.

**Comment by mfontanini** [comment]
Sorry, you're right. The switch doesn't do anything on VS, since VS uses C++11 by default. I'll add a quick fix now, just disabling that section of code, and try to fix it tonight.

**Comment by mfontanini** [comment]
Okay, I've just pushed a fix that disables that part of the code when using Visual Studio, so you should now be able to compile it. 

Sorry for the troubles. I'll have a look at this later, although I just tried a few things and apparently VS doesn't like the use of ```decltype``` and ```declval``` there. Hopefully there's some workaround for this. I'll keep you updated.

**Comment by blazeable** [comment]
Thanks for the fix, I was able to build the libtins library with LIBTINS_ENABLE_CXX11=1 defined :) However I'm getting compilation errors in the example projects, seems the build system isn't adding the pcap and openssl directories to the include path for some of the generated VS projects. Looking into it.

**Comment by c0mradee** [comment]
> I'm trying to compile the latest sources using VS2013 targeting x64, but I'm getting compilation errors in include/tins/internals.h. VS2013 doesn't like this template:
> `template <class T, class P, class=void>`
> `struct accepts_type : std::false_type { };`
> 
> `template <class T, class P>`
> `struct accepts_type<T, P,`
> `typename std::enable_if<`
> `std::is_same< decltype( std::declval<T>()(std::declval<P>()) ), bool>::value`
> `>::type`
> `> : std::true_type { };`
> 
> Which would be a bug (or lack of support) in VS2013, as it compiles fine elsewhere.
> 
> However, I'm getting this even when configuring with LIBTINS_ENABLE_CXX11=0. It seems the TINS_IS_CXX11 definition in cxxstd.h does not check the HAVE_CXX11 macro from config.h.

Hi, I am trying to compile it on windows I have cmake, installing vs2017 community with c++ support now and I have MinGW g++ and gcc also. Can you help?

**Comment by mfontanini** [comment]
What is the problem?
