### ISSUE TITLE
MPLS and 802.1ad support

### ISSUE THREAD

**Issue by fabiomargarido** [mfontanini/libtins#68]
Hi there.

I've recently become aware of libtins and it seems like and awesome fit for some projects I'm working on. Thanks for your work.

It would be nice though to have support for QinQ and MPLS labels. It seems to me that MPLS might be a little more involved, but QinQ should be fairly straightforward to implement.

Best regards.

**Comment by mfontanini** [comment]
I think QinQ should work. Are you sure it doesn't? Packets should be basically parsed as Dot1Q + Dot1Q + EthernetII for example.

**Comment by fabiomargarido** [comment]
Hi Matias, sorry for the delay.

I have not tested the incoming packet case. What I did verify is that when you do:

```
EthernetII eth = EthernetII() / Dot1Q() / Dot1Q() / IP() / TCP();
PacketWriter writer("/tmp/test_tins.pcap", PacketWriter::ETH2);
```

The generated pcap file contains two 802.1Q tags (0x8100) and not a 802.1AD tag no top.

I haven't run any MPLS tests myself because from the documentation I figured there was no support.

Thanks.

**Comment by mfontanini** [comment]
Hey! It's been a while, but I've been doing a lot of changes recently. Adding support for 802.1ad and MPLS were one of them :). I've just pushed 802.1ad tagging and MPLS has been pushed a few days ago. All of this is still in the develop branch, but it should be working.
