### ISSUE TITLE
no matching call for callback()

### ISSUE THREAD

**Issue by sanketplus** [mfontanini/libtins#69]
I added tins in Qt and while running following code:

void MainWindow::on_pushButton_clicked()
{
     //Sniffer("eth0").Tins::Sniffer::sniff_loop(callback);

    Sniffer sniffer("wlan0", Sniffer::PROMISC);

        // Only capture udp packets sent to port 53
        sniffer.set_filter("udp and dst port 53");

        // Start the capture
        sniffer.sniff_loop(callback);
}

bool MainWindow::callback(const PDU &pdu) {
    const IP &ip = pdu.rfind_pdu<IP>(); // Find the IP layer
    const TCP &tcp = pdu.rfind_pdu<TCP>(); // Find the TCP layer
    std::cout << ip.src_addr() << ':' << tcp.sport() << " -> "
              << ip.dst_addr() << ':' << tcp.dport() << std::endl;
    return true;
}

I get this error:

/home/sanket/workspace/canBeFinal/mainwindow.cpp:30: error: no matching function for call to 'Tins::Sniffer::sniff_loop(<unresolved overloaded function type>)'
         sniffer.sniff_loop(callback);
                                    ^
../canBeFinal/mainwindow.cpp: In member function 'void MainWindow::on_pushButton_clicked()':
../canBeFinal/mainwindow.cpp:30:36: error: no matching function for call to 'Tins::Sniffer::sniff_loop(<unresolved overloaded function type>)'
sniffer.sniff_loop(callback);
^
../canBeFinal/mainwindow.cpp:30:36: note: candidate is:
In file included from /usr/local/include/tins/tins.h:54:0,
from ../canBeFinal/mainwindow.h:5,
from ../canBeFinal/mainwindow.cpp:1:
/usr/local/include/tins/sniffer.h:577:10: note: void Tins::BaseSniffer::sniff_loop(Functor, uint32_t) [with Functor = bool (MainWindow::*)(const Tins::PDU&); uint32_t = unsigned int]
void Tins::BaseSniffer::sniff_loop(Functor function, uint32_t max_packets) {
^
/usr/local/include/tins/sniffer.h:577:10: note: no known conversion for argument 1 from '<unresolved overloaded function type>' to 'bool (MainWindow::*)(const Tins::PDU&)'
make: *** [mainwindow.o] Error 1
15:07:15: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project canBeFinal (kit: Desktop Qt 5.3 GCC 64bit)
When executing step 'Make'
15:07:15: Elapsed time: 00:01.

I have defined callback() function in Header file already.

Please help. Thank You.

**Comment by sanketplus** [comment]
Function "callback" should be static.

**Comment by mfontanini** [comment]
The callback doesn't need to be static. You can use any functor that respects one of the valid signatures (have a look at the docs). If you want to use a non-static member function, you can use ```std::bind``` (or ```boost::bind``` if you're using C++03) to achieve this. 

Have a look at the examples, [this one](https://github.com/mfontanini/libtins/blob/master/examples/arpmonitor.cpp#L48) uses ```std::bind```.
