### ISSUE TITLE
Failure to parse DNS packets

### ISSUE THREAD

**Issue by Yotamki** [mfontanini/libtins#74]
Hi,

I've traced failures to parse "trivial" dnames in DNS queries to DNS::compose_name.

I've changed ptr into end: (line 330 @ head)
was: if(index < 0x0c || (&records_data[0] + (index - 0x0c)) >= ptr)
now: if(index < 0x0c || (&records_data[0] + (index - 0x0c)) >= end)

Does this make sense to you? I can provide a buffer/PCAP file that re-produces this issue.

Thanks in advance,
Yotam.

**Comment by mfontanini** [comment]
That check should be fine, since pointers in DNS records can only point to previous labels (I've just checked this on the RFC to make sure). So I think this check should be fine. Maybe that allows it to work for some other reason. 

Could you attach a pcap file that reproduces the problem? Thanks!

**Comment by Yotamki** [comment]
Thanks for the quick response. After the change, I get fewer malformed DNS packets, without issues so far. But, I refer to your judgement here.

I can't upload PCAPs here. Can you reconstruct from the below hexdump? (Wireshark presents the packet without issue)

hexdump malformed_dns_libtins_obfs.pcap

0000000 c3d4 a1b2 0002 0004 0000 0000 0000 0000
0000010 0000 0100 0001 0000 92ea 554f 0000 0000
0000020 0049 0000 0049 0000 8750 6c89 3f1f 4bac
0000030 99c8 0060 0008 8045 3b00 a6d7 0000 11e6
0000040 85f6 0101 0101 0202 0202 60ea 3500 2700
0000050 b1ba e102 2001 0100 0000 0000 0000 7607
0000060 7265 6973 6e6f 6204 6e69 c064 001b 0010
0000070 0003
0000071

**Comment by Yotamki** [comment]
Hi Matias,

Please see the attached.

10x in advance,

On 10 May 2015 at 20:08, Matias Fontanini <notifications@github.com> wrote:

> That check should be fine, since pointers in DNS records can only point to
> previous labels (I've just checked this on the RFC to make sure). So I
> think this check should be fine. Maybe that allows it to work for some
> other reason.
>
> Could you attach a pcap file that reproduces the problem? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mfontanini/libtins/issues/74#issuecomment-100669064>.
>



-- 
Yotam Shtossel
*NorthBit*
+972 52 8727476
LinkedIn <https://www.linkedin.com/company/2778497>

**Comment by mfontanini** [comment]
Okay, so this packet seems to violate he RFC. I guess wireshark has softer rules and doesn't complain about it. It's also a pretty dumb violation because they're basically using 2 bytes to represent the last null byte, when they could just use a null byte instead of an offset field.

I'm going to apply your change anyway. This will soften the rules but it seems like it's necessary. I'll let you know when this is pushed, since I'm going to add a few tests to make sure this doesn't break or hang if a specially crafted packet is parsed.

Thanks!
