### ISSUE TITLE
Expose select-like interface for Sniffer class

### ISSUE THREAD

**Issue by fabiomargarido** [mfontanini/libtins#76]
I've noticed the BaseSniffer class has a get_fd() method that is never called. Would it be possible to create a parameter in the sniffer to control the maximum amount of time it blocks if no packets are received?

What I'd like to achieve is an implementation which handles packets in sniff_loop as they arrive (setting timeout to 0), but which would be able to periodically check for a stop condition if no packets are received.

Thanks in advance.

**Comment by mfontanini** [comment]
I think setting timeouts on pcap doesn't work at all on Linux. You can always get the fd and then do a select over it, which allows you to set a timeout on it. If you're using Windows, you can do the same by using pcap_getevent.

**Comment by fabiomargarido** [comment]
Calling ```config.set_timeout()``` with different values did make a difference in my Ubuntu 15.04 environment.

I could use ```get_fd()``` and ```select()``` on it, but not together with ```sniff_loop()```. What I had in mind was something along the lines of:

```c++
SnifferConfiguration config;
config.set_promisc_mode(true);
config.set_timeout(0);
config.set_reception_timeout(2000);

Sniffer sniffer("eth0", config);

do {
    // returns every two seconds
    keep_sniffing = sniffer->sniff_loop(make_sniffer_handler(handler, &Handler::handle));
} while (keep_running && keep_sniffing);
```

**Comment by mfontanini** [comment]
Well, you can always use ```Sniffer::next_packet``` instead of ```sniff_loop```. That way you could get packets until 2 seconds pass, while using select to timeout.

**Comment by mfontanini** [comment]
Closing this as you should be able to have this behavior by using timeouts and/or select + `Sniffer::get_fd`.
