### ISSUE TITLE
getter and setter of handshakes, features and issues

### ISSUE THREAD

**Issue by prasad24582** [mfontanini/libtins#77]
Hi,

We are using libtins library in one of my project. Its simply superb. 
We need some following features,
1. In crypto.cpp, is it possible to change private variable to protected in class WPA2Decrypter. So that, if any body wants to derive and over load function "decrypt". 
2. Getter and Setter for captured handshakes, so that even if we restart application, we can apply stored handshakes.

If you are okay to make above features from my side, I can do it and send patch to you. you can review and apply patch if its okay. Please throw you thoughts.

Found following issues:
1. In SessionKeys::SessionKeys(const RSNHandshake &hs, const pmk_type &pmk)  function, looks like some memory corruption occurring on variable uint8_t MIC[16] because my application getting segment fault when returning from that constructor. If I do malloc, not getting that issue.
2. when trying cross compile source code on gcc version 4.8.3 by enabling C++11, it was not enabling and it is showing error "pcap_get_pfring_id" not found, however we are not using this variable in libtins.
3.  If I enable C++11, am getting following errors(I am using GCC version 4.8.3):
Cross Compile command:

"cmake ../libtins/ -DCMAKE_FIND_ROOT_PATH=/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/ -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_CXX_COMPILER=/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++  -DLIBTINS_ENABLE_WPA2=1 -DCMAKE_INSTALL_PREFIX:PATH=/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/ -DLIBTINS_ENABLE_CXX11=1 -DPCAP_INCLUDE_DIR=/home/openwrt/libtins/pcap/install_pcap/include/ -DPCAP_LIBRARY=/home/openwrt/libtins/pcap/install_pcap/lib/"

-- Looking for pcap_get_pfring_id - not found
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": not supported
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": not supported
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": not supported
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": not supported
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": not supported
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": not supported
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": not supported
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": not supported
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": not supported
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": not supported
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": not supported
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": not supported
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": not supported
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": not supported
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": not supported
CMake Error at CMakeLists.txt:72 (MESSAGE):
  C++11 features requested but the compiler does not support them.

I commented out all check points and added  "-std=c++11" flag in flags.make file, its working. Am not sure, what went wrong while configuring to enable c++11 features.

Could you please help me to solve above issues.

Please let me know if you need further information.

Thanks and Regards,
Prasad

**Comment by mfontanini** [comment]
Sure, if you want to make a patch for those things, that would be great!

Regarding bugs:

* I had a look at that SessionKeys issue this weekend. Even if it sounds strange, it seems to be a compiler error. I managed to reproduce that on gcc 4.7.2. On the other hand, 4.8.3 seems to work just fine. Which compiler version are you using?
* pcap_get_pfring_id shouldn't be a problem. I always get that message, it's not an error, just an information message.
* That's really strange, it seems like you're using the wrong compiler or something, since g++ 4.8 shouldn't complain about that. Could you provide the full output of CMake when you call it for the first time on a clean build directory?

Thanks!

**Comment by prasad24582** [comment]
Thank you for spontaneous response. Will make work on it and share you patch. 

1. I am using CXX compiler identification is GNU 4.8.3(toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2 & mips-openwrt-linux-uclibc-g++)

Host Machine:
#gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

2. Just saw error about pcap_get_pfring_id, if it's not creating problem, simply we can ignore it. 

3. /home/openwrt/libtins/templibtins/build$ cmake ../libtins/ -DCMAKE_FIND_ROOT_PATH=/home/openwrt/openwrt/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/ -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_CXX_COMPILER=/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++  -DLIBTINS_ENABLE_WPA2=1 -DCMAKE_INSTALL_PREFIX:PATH=/home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/ -DLIBTINS_ENABLE_CXX11=1 -DPCAP_INCLUDE_DIR=/home/openwrt/libtins/pcap/install_pcap/include/ -DPCAP_LIBRARY=/home/openwrt/libtins/pcap/install_pcap/lib/
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++
-- Check for working CXX compiler: /home/openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Build will generate a shared library. Use LIBTINS_BUILD_SHARED=0 to perform a static build
-- Found PCAP: /home/openwrt/libtins/pcap/install_pcap/lib
-- Performing Test PCAP_LINKS_SOLO
WARNING: Target "cmTryCompileExec4061726383" requests linking to directory "/home/openwrt/libtins/pcap/install_pcap/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
WARNING: Target "cmTryCompileExec3055402174" requests linking to directory "/home/openwrt/libtins/pcap/install_pcap/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Looking for pcap_get_pfring_id - not found
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": not supported
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": not supported
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": not supported
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": not supported
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": not supported
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": not supported
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": not supported
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": not supported
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": not supported
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": not supported
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": not supported
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": not supported
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": not supported
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": not supported
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": not supported
CMake Error at CMakeLists.txt:72 (MESSAGE):
  C++11 features requested but the compiler does not support them.


-- Configuring incomplete, errors occurred!
See also "/home/openwrt/libtins/templibtins/build/CMakeFiles/CMakeOutput.log".
See also "/home/openwrt/libtins/templibtins/build/CMakeFiles/CMakeError.log".

Please let me know if need to share CMakeOutput.log, will share you with you.

**Comment by mfontanini** [comment]
Hmmm that's strange. I'll have a look at the crash. I did manage to reproduce it on gcc 4.7.2, but it seemed like it was only triggered on that version. 

The C++11 issue is strange. The CMake module that detects C++11 was taken from somewhere else, so I'm not really familiar with what it's doing. I'll try cross compiling tonight and see if it happens to me too. Could one try just one thing? I see that the C++11 module is checking the variable CROSS_COMPILING variable. Could you set it explicitly when calling CMake? Like ```cmake -DCROSS_COMPILING=1 ..```. Don't know if that's going to do anything, but I guess it's worth trying.

**Comment by prasad24582** [comment]
yes, you are right about cross compile, Added -DCROSS_COMPILING=1 flag and it done magic. you are the boss. Thank you so much. 

About capturing handshakes, I done some sort of changing handshakes.h, which will store the keys into file(application will send application name to libtins), I don't wanna do it because others may not want to save them into file. So, if they like to save they can call getter(callback) to save. I want to save efforts by taking your suggestion to set/get handshakes. Can you throw any idea about it.

**Comment by mfontanini** [comment]
I think this would require changing a few things to make it work. I'll have a look at it later and see how it could be added.

**Comment by prasad24582** [comment]
created one patch, could you please this is okay with you. 
Please let me know if any changes or suggestions.

--- ../libtins/include/tins/crypto.h	2015-05-14 17:17:36.410184530 -0400
+++ ../../libtins/include/tins/crypto.h	2015-05-14 11:29:03.645093592 -0400
@@ -66,7 +66,13 @@
             
             SessionKeys();
             SessionKeys(const RSNHandshake &hs, const pmk_type &pmk);
+            SessionKeys(const ptk_type &rptk, const bool &ccmp){
+                std::copy( rptk.begin(), rptk.end(), ptk.begin());
+                is_ccmp = ccmp; 
+            }
             SNAP *decrypt_unicast(const Dot11Data &dot11, RawPDU &raw) const;
+            ptk_type getptk() const{return ptk;}
+            bool getccmp() const {return is_ccmp;}
         private:
             SNAP *ccmp_decrypt_unicast(const Dot11Data &dot11, RawPDU &raw) const;
             SNAP *tkip_decrypt_unicast(const Dot11Data &dot11, RawPDU &raw) const;
@@ -232,7 +238,7 @@
          * failed, true otherwise.
          */
         bool decrypt(PDU &pdu);
-    private:
+    protected:
         typedef std::map<std::string, WPA2::SupplicantData> pmks_map;
         typedef std::map<address_type, WPA2::SupplicantData> bssids_map;
         typedef std::pair<address_type, address_type> addr_pair;
@@ -254,6 +260,7 @@
         bssids_map aps;
         keys_map keys;
     };
+
     #endif // HAVE_WPA2_DECRYPTION
 
     /**

Please review it and apply if its okay with you.

Thank you.
Prasad
