### ISSUE TITLE
extract_addr_pair verses extract_addr_pair_dst

### ISSUE THREAD

**Issue by prasad24582** [mfontanini/libtins#81]
Hi Matias,

While going throw code, observed both member functions extract_addr_pair and extract_addr_pair_dst using same set of conditional checks. you intentionally kept like that? 

Just wants to bring to your notice.

Thanks and Regards,
Prasad

**Comment by mfontanini** [comment]
One of these returns the source address and the other the destination address. So even if they check similar things, they return different attributes. 

Thanks for the notification though.
