### ISSUE TITLE
Variable MIC(SessionKeys - Crypto.cpp) throwing exception(memory corruption)

### ISSUE THREAD

**Issue by prasad24582** [mfontanini/libtins#82]
Hi Matias,

Variable MIC(SessionKeys - Crypto.cpp)  creating memory corruption, While applying for handshakes, it's crashing application. 

My Compiler Environment:
mips-openwrt-linux-g++ (OpenWrt/Linaro GCC 4.8-2014.04 r45586) 4.8.3

If I allocate dynamic memory (uint8_t *MIC = (uint8_t *)malloc(16);), then its working.

Could you please look into this issue.

Thanks and Regards,
Prasad

**Comment by mfontanini** [comment]
Some people posted about this on the forum. I once debugged this on raspberry pi and made sure it was a gcc on ARM bug. Then someone also reported this happening on kali linux, for which I got kali and tested it, and there didn't seem to be anything wrong that could cause this, so I just assumed it was still some sort of obscure compiler bug, although I know this sounds super unlikely.

I'm going to try this again and see if I can make an equivalent code that works on all platforms. 

Thanks for the notification, it seems it's time to find a fix for this once and for all.

**Comment by mfontanini** [comment]
Well so it was actually a bug... The MIC variable should be 20 bytes long so it fits the SHA output when using CCMP mode. So for TKIP (which uses MD5), 16 bytes was enough, but not for the other. The funny thing is that this works just fine (and by "works" I mean running valgrind doesn't show any sort of errors) in my current setup. But well, I guess I shouldn't blame the compiler next time! 

Can you test the latest commit and let me know if it works? Thanks!

**Comment by prasad24582** [comment]
Sure, will test it and update you.

**Comment by prasad24582** [comment]
Hi Matias, it worked. Thank you so much. Sorry for late reply.

Regards,
Prasad
