### ISSUE TITLE
Does this work on non-rooted android devices?

### ISSUE THREAD

**Issue by Dushyanth-Reddy** [mfontanini/libtins#83]
Does this library work on non-rooted android devices? one of the issues were talking about "It should be enough to add only pcap.h and pcap/bpf.h include files. That are the only includes that libtins is using*, and you don't actually need the libpcap.so binaries." Will it work with just these two header files? does any of them need root access on the device?
Please respond at the earliest.

**Comment by mfontanini** [comment]
No, I don't think it works without rooting an android device. Basically on any Linux you need root privileges to sniff packets (or CAP_NET_ADMIN capabilities on your app), so you most likely need the same on android.

**Comment by Dushyanth-Reddy** [comment]
Thanks for the update.
