### ISSUE TITLE
Examples on TCPStreamFollower?

### ISSUE THREAD

**Issue by jiamo** [mfontanini/libtins#85]
The features say "Following and reassembling TCP streams on the fly." Does this mean I can export(print) the followed tcp data  in right sequnce before the follow don't finish.  Do we have some examples to achieve this ?

**Comment by mfontanini** [comment]
Seems like there's no example for TCP stream reassembly. I should add one :P. But yes, it basically follows and reassembles TCP streams and lets you process it every time new data arrives and also at the end of the stream in case you want to process the entire stream data and not the intermediate stages of it.

In the mean time, you can have a look at the [TCPStreamFollower](http://libtins.github.io/docs/latest/d5/d1a/classTins_1_1TCPStreamFollower.html) class documentation.

There's also a test for ```TCPStreamFollower``` that might come in handy to see how the class is used: https://github.com/mfontanini/libtins/blob/master/tests/src/tcp_stream.cpp

**Comment by ekse** [comment]
I wrote a toy program that uses the TCP stream reassembly, it simply dumps the client and server to files. Maybe this could be adapted to provide as an example program. 

https://github.com/ekse/code/blob/master/sec/tcp_streams_dump/main.cpp
