### ISSUE TITLE
Can PDU object can have payload_type method (virual)?

### ISSUE THREAD

**Issue by jiamo** [mfontanini/libtins#86]
So   `PDU *p = (PDU *) &somethingchildobject`  and to make `p->payload_type()` return the real child class  object 's payload_type.

**Comment by mfontanini** [comment]
Can you explain this with an actual example? I think what you want is can be achieved with the (virtual) method ```PDU::pdu_type```:

```c++
TCP tcp;
PDU* pdu = &tcp;
assert(pdu->pdu_type() == PDU::TCP);
```

**Comment by jiamo** [comment]
something like `assert(pdu->payload_type() == tcp.payload_type()`

**Comment by mfontanini** [comment]
Well... the PDU type will be the same, so:

```c++
assert(pdu->pdu_type() == tcp.pdu_type());
```

**Comment by jiamo** [comment]
I know , in ethernetII , the payload_type is the next layer type. what I expect is same as the func pdu_type , but I want is the next_pdu_type.

**Comment by einarjon** [comment]
What you want seems to be pdu->inner_pdu()->pdu_type().

Since inner_pdu() can return NULL this can't be called without checking for
NULL. I don't see the point in making a virtual function for this, but I am
not Matias.

Regards
Einar Jón

**Comment by mfontanini** [comment]
Okay, now I see what you mean. I agree with Einar, what you basically want is an equivalent of checking if there's an ```inner_pdu``` and then calling ```pdu_type```. 

I don't think this should be a method (btw it wouldn't need to be virtual). What would you return if there's no ```inner_pdu```? It's simpler and clearer if in your code you just check:

```c++
if (pdu->inner_pdu()) {
    PDU::pdu_flag next_pdu_type = pdu->inner_pdu()->pdu_type();
    // whatever.
}
```

**Comment by jiamo** [comment]
Ok got it.
