### ISSUE TITLE
IPv6Address obj return in6_addr or IPv4Address obj return in_addr

### ISSUE THREAD

**Issue by jiamo** [mfontanini/libtins#87]
in_addr in6_addr struce in ` <netinet/in.h>` , can IPv4Address offer a method to return this struct ip addr?

**Comment by mfontanini** [comment]
Is this really required? It's a one liner anyway (didn't try this but it should work):

```c++
IPv4Address addr4 = "192.168.0.1";
in_addr x = { addr4 };

IPv6Address addr6 = "ff00::1";
in6_addr y;
addr6.copy(y.s6_addr);
```
