### ISSUE TITLE
Get size of data read from pcap file

### ISSUE THREAD

**Issue by kaatish** [mfontanini/libtins#93]
I want to know exactly how much data was read from a pcap file using a sniff_loop(). Currently, I am just adding the Tins::Packet.pdu()->size() in the handle function which is called from sniff_loop using std::bind.

The addition of all pdu sizes for a file comes very close to the file size but its not exact. For eg., for a 642M pcap file, the sum is 608341004 bytes.

Am I calculating the size of packets read correctly? Is there a significant amount of extraneous data in the pcap file that prevents the summation of packet sizes to be equal to the file size?

**Comment by mfontanini** [comment]
Well, for every packet, the libpcap file format adds a header (just a few bytes) + there's an initial header at the beginning of the file. That means that the sum of all packet sizes won't be the same as the size of the file.

If you want to know how much total data was read, just get the file size. If you want to know how many packet data was read, then adding the PDU sizes is the way to go.

**Comment by kaatish** [comment]
Thank you for answering this.
