### ISSUE TITLE
Modifying Ethernet headers on TCPStream objects

### ISSUE THREAD

**Issue by rodopoulos** [mfontanini/libtins#94]
Hello,

first of all, congratulations on the awesome lib. 

So, I'm implementing an application to replay a victim's web session on my screen. For this, I ARP spoofed both victim and gateway and then relayed the packets they sent to me to the right destiny. This is handled by a sniffer callback, aplied in a sniff_loop(), which basically listen for DNS probes and TCP on port 80. Meanwhile, before sending PDUs with a proper HTTP payload, I need make some little modifications, like adding headers, copying them in a buffer and perform a SSL Stripping, if necessary. 

I read the documentation and bumped on the `TCPStreamFollower` class, which will perfectly solve my problem with the callback funcions. But, there's a major issue: before sending the PDUs, I need to modify the Ethernet headers, to properly manage the relay. However, `TCPStream` class doesn't have access to this headers.

I tried to think in a workaround, combining `sniff_loop()` and `follow_stream()`, maybe using the FowardIterators, but nothing came up. I'm totally new to this lib, I managed to figure out some stuff, but now I'm really stuck and despairingly looking for a workaround. 

Thanks in advice

Ps: if you need some code, I'll gladly post it here. For now, I didn't think it would be necessary.

**Comment by mfontanini** [comment]
Hi,

```TCPStreamFollower``` is pretty basic right now. I'm soon going to enhance it so it's easier to use and you'll have better access to each stream's information. What you'd need here is to basically have access to the client and server MAC addresses for a given stream, right? I think the new design would allow that.

I'll keep you updated on this. I've been pretty busy lately, but I'll have some time to do this after this weekend.

Cheers!

**Comment by rodopoulos** [comment]
Thanks Matias,

It's a shame that I didn't find your lib before. I'm implementing this as my graduation project, so I'm on a lttle hurry and surely would be great if I requested for these features before. 

Well, for now, I need a workaround. Maybe, I can implement my interpretation from TCP Stream Follower, creating a stream follower when receiving a TCP SYN, then follow this with the follower. Does this sound ok or is there any easier way, using tools in the lib? I'm very sorry for bothering you with this, but I'm out of ideias and really need to finish this.

**Comment by mfontanini** [comment]
I think if you're short on time, just copy the TCPStreamFollower and modify the class to fit your needs. I guess you could store the data you need on the TCPStream, probably on its StreamInfo. 

This should be pretty simple to implement. Let me know if you need any help.

**Comment by mfontanini** [comment]
Closing this as I think you would be able to use the new StreamFollower class to do this
