### ISSUE TITLE
Read pcap file in batches

### ISSUE THREAD

**Issue by kaatish** [mfontanini/libtins#95]
I want to read a pcap file in batches. I intend to run some functions on the data gathered after each batch read and then resume reading the file from the last point. This goes on till the end of file is reached. What is the proper way of doing this?

Is it possible to somehow pause the sniff_loop when reading from a file and resume from the same position in the pcap file to read more packets?

Or should I just do this by using ```sniffer.next_packet()```?

**Comment by mfontanini** [comment]
Yeah I think you should use ```Sniffer::next_packet```. Just loop using the chunk size you want and call that member function to fetch new packets. 

I think that if you return false on the callback for ```sniff_loop```, this would work too. I haven't tried it, but the pcap handle keeps its state, so as long as you always use the same ```FileSniffer```, you'll continue reading from where you stopped.

**Comment by kaatish** [comment]
It actually does work with sniff_loop. The packet reading is resumed with every sniff_loop call. Perhaps this could be added to the documentation?

**Comment by mfontanini** [comment]
Sure :)

**Comment by kaatish** [comment]
I have another question, which is related to this one. I can create a separate issue if you want. What is the right way to detect that a pcap file has reached end of file using sniff_loop. Currently, I have a hacky way of doing it. I just detect if the bool function used for the return in sniff_loop is true after sniff_loop has exited. This could mean that the loop ended due to end of file and not due to the supplied stopping condition.

Is there a better way of doing it?

**Comment by mfontanini** [comment]
That's why I think it's better to use ```next_packet```. It's much more straightforward:

```c++
Packet pkt;
do {
    // Process a chunk
    for (int i = 0; i < chunk_size; ++i) {
        pkt = sniffer.next_packet();
        if (!pkt) {
            // stop if 
            break;
        }
        process_packet(pkt);
    }
} while (pkt);
```

Didn't test the code, but something like that should work.

**Comment by kaatish** [comment]
I think this answers my question. Should I start a separate issue to add to documentation the fact that sniffer_loop can resume from the last point?

**Comment by mfontanini** [comment]
Sorry for the delay. I'll do it later today for sure, don't worry.

**Comment by mfontanini** [comment]
Docs are updated :D
