### ISSUE TITLE
Callback/functors could have a void* attribute

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#97]
For example let's take:

IPv4ReassemblerProxy(Functor func)
: functor_(func) {}

the IPv4ReassemblerProxy could have an additional void* attribute :

IPv4ReassemblerProxy(Functor func, void* user_data)
: functor_(func),user_data_(user_data) {}

and pass the user_data to the functor :

bool operator()(PDU &pdu) {
    if(reassembler.process(pdu) != IPv4Reassembler::FRAGMENTED)
        return functor_(pdu, user_data_);
    ...

Why ?

When wrapping libtins in python, i need to call python callbacks given in python space by the end user. A python callback can be seen as a PyObject*.

So my IPv4ReassemblerProxy functor's job is only to call the python callback. To be able to do that, i need that the Functor can see a reference to the PyObject*. With a void* user_data, i can push the PyObject* :

bool functor(PDU &pdu, void* user_data) {
    ((PyObject*) user_data)->__call__(pdu);
    ...
}

I hope it's clear enough :) The technique is usual for C libraries. If you have another idea to call python callbacks from C++, please.

**Comment by mfontanini** [comment]
You shouldn't need that. The whole point of using a template Functor type on functions that require a callback is that you can provide any type you want there. On the other hand, if you used function pointers, that would force you to use ```void*``` like most C libraries do, since the parameters are static.

Here you can just bind the second parameter before providing the callback to ```sniff_loop``` or whatever function you're using:

```c++
bool my_callback(const PDU& pdu, PyObject* object) {
    object->call(pdu);
    return true;
}

int main() {
    Sniffer sniffer = /*...*/;
    PyObject* object = /*...*/;
    // Construct the callback. Use my_callback, and:
    // - Forward the first parameter (the PDU).
    // - Bind the PyObject to the callback, so every time the callback is executed, 
    //   the PyObject will also be forwarded.
    auto callback = std::bind(&my_callback, std::placeholders::_1, object);
    sniffer.sniff_loop(callback);
}
```

Note that you can use ```boost::bind``` rather than ```std::bind``` if you're not using C++11.

**Comment by stephane-martin** [comment]
"bind" is unknown to me, have to dig in C++ more... urg, thanks.

**Comment by mfontanini** [comment]
You don't actually need bind. You could write your own proxy:

```c++
struct my_proxy {
    my_proxy(PyObject* object) : object(object) { }
   
    // This is what sniff_loop will end up calling
    bool operator()(const PDU& pdu) {
       object->call(pdu);
       return true;
    }

    PyObject* object;
};

int main() {
    Sniffer sniffer = /*...*/;
    PyObject* object = /*...*/;
   
    // Build a proxy around this PyObject
    my_proxy proxy(object);
    // Now use it on sniff_loop
    sniffer.sniff_loop(proxy);
}
```

Didn't compile that, but something like that should work

**Comment by stephane-martin** [comment]
Agreed, i just stop to think functors as C functions. Thx.

**Comment by stephane-martin** [comment]
Well, dealing with the cython oddities and functors was a lot of pain. So instead i just used IPv4Reassembler and implemented the callback machinery directly at the cython level. No use of the Proxy object.

Interestingly, after quite many tests, i did not encounter a single case of IP fragmentation. When downloading large files over HTTP, i do see a lot of 1500 bytes or so packets, but they are not marked as fragmented?! Same when uploading a big file.

So i guess TCP clients and servers are clever enough to send chunks of data < 1500 bytes so that it is contained in a non-fragmented IP packet.... or i have a bug somewhere.

Would you have a good test case of fragmented traffic so that i can test the IPv4Reassembler wrapper correctly ?

**Comment by mfontanini** [comment]
Yeah, IP fragmentation is pretty expensive, so each peer won't use fragmentation unless it really needs to. For TCP I don't think you'd ever see it, since it's just simpler to actually send less data rather than to fragment the packet. I think you would only see it if you're sending pretty big UDP packets.

Therefore, an easy way to make the kernel fragment a packet is sending a big UDP packet (one that's over your interface's MTU, which is likely to be 1500):

```bash
# Print 1600 A characters and send them through netcat
python -c "print 'A'*1600" | nc -u 8.8.8.8 53
```

By doing that, I see this on tcpdump:

```
15:08:39.213555 IP (tos 0x0, ttl 64, id 45709, offset 0, flags [+], proto UDP (17), length 1500)
    10.0.2.15.58969 > 8.8.8.8.53: 16705 op8+ [b2&3=0x4141] [16705a] [16705q] [16705n] [16705au][|domain]
15:08:39.213666 IP (tos 0x0, ttl 64, id 45709, offset 1480, flags [none], proto UDP (17), length 149)
    10.0.2.15 > 8.8.8.8: ip-proto-17
```

**Comment by mfontanini** [comment]
Closing this as the initial question was answered.
