### ISSUE TITLE
free memory after IP packet has been reassembled ?

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#98]
I'm not completely sure, but it seems that in IPv4Reassembler::process(PDU &pdu), the fragmented IP packets are *serialized* and stored in IPv4Fragment objects, which in turn are stored as a vector in IPv4Stream objects. The streams are owned by the IPv4Reassembler object.

So it looks like the allocated memory for IPv4Fragment objects is only released when the IPv4Reassembler object is destroyed, right ? Well if that's so, that could only happen in a very long time, with a lot of occupied mem meanwhile.

**Comment by mfontanini** [comment]
Nice catch! Yes, I think that ```streams.erase``` in ```IPv4Reassembler::process``` shouldn't be inside that if at all, that should be done every time a stream is reassembled. I'll fix this later today.

Thanks!
