### ISSUE TITLE
TTL size in DNS::Resource

### ISSUE THREAD

**Issue by stephane-martin** [mfontanini/libtins#99]
(sorry, this is going to be a little pedantic)

**uint32_t** ttl() const { return ttl_; }

but

void ttl(**uint16_t** data)

and https://www.ietf.org/rfc/rfc1035.txt:
"TTL             positive values of a signed 32 bit number."

**Comment by mfontanini** [comment]
That's not being pedantic, that's a bug :). I'l add it to the fix-list for tonight. 

Anything you find, just let me know. There's a bunch of stuff in the library that's there but I've barely used it, so there might be errors like this.
